/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.Execute;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Execute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ExecuteImpl#getSubProcedureName <em>Sub Procedure Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExecuteImpl extends StructureImpl implements Execute
{
  /**
   * The default value of the '{@link #getSubProcedureName() <em>Sub Procedure Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubProcedureName()
   * @generated
   * @ordered
   */
  protected static final String SUB_PROCEDURE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSubProcedureName() <em>Sub Procedure Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubProcedureName()
   * @generated
   * @ordered
   */
  protected String subProcedureName = SUB_PROCEDURE_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExecuteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXECUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSubProcedureName()
  {
    return subProcedureName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSubProcedureName(String newSubProcedureName)
  {
    String oldSubProcedureName = subProcedureName;
    subProcedureName = newSubProcedureName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXECUTE__SUB_PROCEDURE_NAME, oldSubProcedureName, subProcedureName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXECUTE__SUB_PROCEDURE_NAME:
        return getSubProcedureName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXECUTE__SUB_PROCEDURE_NAME:
        setSubProcedureName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXECUTE__SUB_PROCEDURE_NAME:
        setSubProcedureName(SUB_PROCEDURE_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXECUTE__SUB_PROCEDURE_NAME:
        return SUB_PROCEDURE_NAME_EDEFAULT == null ? subProcedureName != null : !SUB_PROCEDURE_NAME_EDEFAULT.equals(subProcedureName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (subProcedureName: ");
    result.append(subProcedureName);
    result.append(')');
    return result.toString();
  }

} //ExecuteImpl
