/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.HTMLTYPE;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ObjectImpl#getObjName <em>Obj Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ObjectImpl#getHtmltype <em>Htmltype</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ObjectImpl#getObjectDef <em>Object Def</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectImpl extends MinimalEObjectImpl.Container implements org.xtext.example.mydsl.myDsl.Object
{
  /**
   * The default value of the '{@link #getObjName() <em>Obj Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjName()
   * @generated
   * @ordered
   */
  protected static final String OBJ_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getObjName() <em>Obj Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjName()
   * @generated
   * @ordered
   */
  protected String objName = OBJ_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getHtmltype() <em>Htmltype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmltype()
   * @generated
   * @ordered
   */
  protected HTMLTYPE htmltype;

  /**
   * The default value of the '{@link #getObjectDef() <em>Object Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectDef()
   * @generated
   * @ordered
   */
  protected static final String OBJECT_DEF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getObjectDef() <em>Object Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectDef()
   * @generated
   * @ordered
   */
  protected String objectDef = OBJECT_DEF_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OBJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getObjName()
  {
    return objName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObjName(String newObjName)
  {
    String oldObjName = objName;
    objName = newObjName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OBJECT__OBJ_NAME, oldObjName, objName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HTMLTYPE getHtmltype()
  {
    return htmltype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHtmltype(HTMLTYPE newHtmltype, NotificationChain msgs)
  {
    HTMLTYPE oldHtmltype = htmltype;
    htmltype = newHtmltype;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.OBJECT__HTMLTYPE, oldHtmltype, newHtmltype);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHtmltype(HTMLTYPE newHtmltype)
  {
    if (newHtmltype != htmltype)
    {
      NotificationChain msgs = null;
      if (htmltype != null)
        msgs = ((InternalEObject)htmltype).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OBJECT__HTMLTYPE, null, msgs);
      if (newHtmltype != null)
        msgs = ((InternalEObject)newHtmltype).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.OBJECT__HTMLTYPE, null, msgs);
      msgs = basicSetHtmltype(newHtmltype, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OBJECT__HTMLTYPE, newHtmltype, newHtmltype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getObjectDef()
  {
    return objectDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObjectDef(String newObjectDef)
  {
    String oldObjectDef = objectDef;
    objectDef = newObjectDef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OBJECT__OBJECT_DEF, oldObjectDef, objectDef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.OBJECT__HTMLTYPE:
        return basicSetHtmltype(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.OBJECT__OBJ_NAME:
        return getObjName();
      case MyDslPackage.OBJECT__HTMLTYPE:
        return getHtmltype();
      case MyDslPackage.OBJECT__OBJECT_DEF:
        return getObjectDef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.OBJECT__OBJ_NAME:
        setObjName((String)newValue);
        return;
      case MyDslPackage.OBJECT__HTMLTYPE:
        setHtmltype((HTMLTYPE)newValue);
        return;
      case MyDslPackage.OBJECT__OBJECT_DEF:
        setObjectDef((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OBJECT__OBJ_NAME:
        setObjName(OBJ_NAME_EDEFAULT);
        return;
      case MyDslPackage.OBJECT__HTMLTYPE:
        setHtmltype((HTMLTYPE)null);
        return;
      case MyDslPackage.OBJECT__OBJECT_DEF:
        setObjectDef(OBJECT_DEF_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OBJECT__OBJ_NAME:
        return OBJ_NAME_EDEFAULT == null ? objName != null : !OBJ_NAME_EDEFAULT.equals(objName);
      case MyDslPackage.OBJECT__HTMLTYPE:
        return htmltype != null;
      case MyDslPackage.OBJECT__OBJECT_DEF:
        return OBJECT_DEF_EDEFAULT == null ? objectDef != null : !OBJECT_DEF_EDEFAULT.equals(objectDef);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (objName: ");
    result.append(objName);
    result.append(", objectDef: ");
    result.append(objectDef);
    result.append(')');
    return result.toString();
  }

} //ObjectImpl
