function(){return function(){var h,l=this;function aa(a){return void 0!==a}function ba(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&aa(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function m(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){return"function"==ca(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){ia=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.fa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.da=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};var ma=window;function na(a){if(Error.captureStackTrace)Error.captureStackTrace(this,na);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(na,Error);na.prototype.name="CustomError";var oa;function pa(a,b){return 0==a.lastIndexOf(b,0)}function qa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function sa(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",n=e[g]||"",r=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var z=r.exec(k)||["","",""],J=p.exec(n)||["","",""];if(0==z[0].length&&0==J[0].length)break;c=ta(0==z[1].length?0:parseInt(z[1],10),0==J[1].length?0:parseInt(J[1],10))||ta(0==z[2].length,0==J[2].length)||ta(z[2],J[2])}while(0==c)}return c}function ta(a,b){return a<b?-1:a>b?1:0}
function ua(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var va=Array.prototype;function wa(a,b){if(m(a))return m(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function t(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function xa(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}function ya(a,b,c){var d=c;t(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function za(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Aa(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Ba(a,b){var c;a:{c=a.length;for(var d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:m(a)?a.charAt(c):a[c]}function Ca(a){return va.concat.apply(va,arguments)}
function Da(a,b,c){return 2>=arguments.length?va.slice.call(a,b):va.slice.call(a,b,c)};var Ea={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Fa="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ga=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ha=/^#(?:[0-9a-f]{3}){1,2}$/i,Ia=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ja=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function u(a,b){this.code=a;this.a=v[a]||Ka;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}q(u,Error);var Ka="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=Ka;v[30]=Ka;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=Ka;v[9]="unknown command";u.prototype.toString=function(){return this.name+": "+this.message};var La;a:{var Ma=l.navigator;if(Ma){var Na=Ma.userAgent;if(Na){La=Na;break a}}La=""}function w(a){return-1!=La.indexOf(a)};function Oa(){return w("Opera")||w("OPR")}function Pa(){return(w("Chrome")||w("CriOS"))&&!Oa()&&!w("Edge")};function Qa(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var Ra=Oa(),x=w("Trident")||w("MSIE"),Sa=w("Edge"),Ta=w("Gecko")&&!(-1!=La.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Ua=-1!=La.toLowerCase().indexOf("webkit")&&!w("Edge"),Va=w("Macintosh"),Wa=w("Windows");function Xa(){var a=La;if(Ta)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Sa)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ua)return/WebKit\/(\S+)/.exec(a)}
function Ya(){var a=l.document;return a?a.documentMode:void 0}var Za=function(){if(Ra&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Xa())&&(a=b?b[1]:"");return x&&(b=Ya(),b>parseFloat(a))?String(b):a}(),$a={};function ab(a){return $a[a]||($a[a]=0<=sa(Za,a))}var bb=l.document,cb=bb&&x?Ya()||("CSS1Compat"==bb.compatMode?parseInt(Za,10):5):void 0;!Ta&&!x||x&&9<=cb||Ta&&ab("1.9.1");x&&ab("9");function db(a,b){this.x=aa(a)?a:0;this.y=aa(b)?b:0}h=db.prototype;h.clone=function(){return new db(this.x,this.y)};h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){var c=da(b)?b:a;this.x*=a;this.y*=c;return this};function eb(a,b){this.width=a;this.height=b}h=eb.prototype;h.clone=function(){return new eb(this.width,this.height)};h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=da(b)?b:a;this.width*=a;this.height*=c;return this};function fb(a){return a?new gb(y(a)):oa||(oa=new gb)}
function hb(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,k;if(k="function"==typeof e.split)k=0<=wa(e.split(/\s+/),c);k&&(a[d++]=g)}a.length=d;return a}return b}
function ib(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function jb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function kb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(x&&!(9<=cb)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?lb(a,b):!c&&jb(e,b)?-1*mb(a,b):!d&&jb(f,a)?mb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=y(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,d)}function mb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return lb(d,a)}function lb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function y(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var nb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ob={IMG:" ",BR:"\n"};
function pb(a,b,c){if(!(a.nodeName in nb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ob)b.push(ob[a.nodeName]);else for(a=a.firstChild;a;)pb(a,b,c),a=a.nextSibling}function qb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function gb(a){this.a=a||l.document||document}function rb(a,b,c,d){return hb(a.a,b,c,d)}gb.prototype.contains=jb;var sb=w("Firefox"),tb=Qa()||w("iPod"),ub=w("iPad"),vb=w("Android")&&!(Pa()||w("Firefox")||Oa()||w("Silk")),wb=Pa(),xb=w("Safari")&&!(Pa()||w("Coast")||Oa()||w("Edge")||w("Silk")||w("Android"))&&!(Qa()||w("iPad")||w("iPod"));/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function yb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var zb=x&&!(9<=cb),Ab=x&&!(8<=cb);function Bb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Cb(a,b){var c=Ab&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Bb(b,a,b.nodeName,c)};function Db(a){this.b=a;this.a=0}function Eb(a){a=a.match(Fb);for(var b=0;b<a.length;b++)Gb.test(a[b])&&a.splice(b,1);return new Db(a)}var Fb=RegExp("\\$?(?:(?![0-9-])[\\w-]+:)?(?![0-9-])[\\w-]+|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Gb=/^\s/;function A(a,b){return a.b[a.a+(b||0)]}function B(a){return a.b[a.a++]}function Hb(a){return a.b.length<=a.a};function C(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(zb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),zb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Ib(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Ab&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Jb(a,b,c,d,e){return(zb?Kb:Lb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new D)}
function Kb(a,b,c,d,e){if(a instanceof Mb||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=Nb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],k=0;b=f[k++];)Ib(b,c,d)&&g.push(b);f=g}for(k=0;b=f[k++];)"*"==a&&"!"==b.tagName||E(e,b);return e}Ob(a,b,c,d,e);return e}
function Lb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!x?(b=b.getElementsByName(d),t(b,function(b){a.a(b)&&E(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),t(b,function(b){b.className==d&&a.a(b)&&E(e,b)})):a instanceof F?Ob(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),t(b,function(a){Ib(a,c,d)&&E(e,a)}));return e}
function Pb(a,b,c,d,e){var f;if((a instanceof Mb||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Nb(a);if("*"!=g&&(f=xa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=xa(f,function(a){return Ib(a,c,d)}));t(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||E(e,a)});return e}return Qb(a,b,c,d,e)}function Qb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Ib(b,c,d)&&a.a(b)&&E(e,b);return e}
function Ob(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Ib(b,c,d)&&a.a(b)&&E(e,b),Ob(a,b,c,d,e)}function Nb(a){if(a instanceof F){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function D(){this.b=this.a=null;this.s=0}function Rb(a){this.node=a;this.a=this.b=null}function Sb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f=null,g=0;c&&d;){var f=c.node,k=d.node;f==k||f instanceof Bb&&k instanceof Bb&&f.a==k.a?(f=c,c=c.a,d=d.a):0<kb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.s=g;return a}
D.prototype.unshift=function(a){a=new Rb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.s++};function E(a,b){var c=new Rb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.s++}function Tb(a){return(a=a.a)?a.node:null}D.prototype.f=function(){var a=Tb(this);return a?C(a):""};function Ub(a,b){return new Vb(a,!!b)}function Vb(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function G(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.c?b.b:b.a;return c.node};function H(a){this.m=a;this.b=this.i=!1;this.f=null}function I(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Wb(a,b){a.i=b}function Xb(a,b){a.b=b}function K(a,b){var c=a.a(b);return c instanceof D?+c.f():+c}function L(a,b){var c=a.a(b);return c instanceof D?c.f():""+c}function Yb(a,b){var c=a.a(b);return c instanceof D?!!c.s:!!c};function Zb(a,b,c){H.call(this,a.m);this.c=a;this.j=b;this.B=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==$b&&(c.b||c.i||4==c.m||0==c.m||!b.f?b.b||b.i||4==b.m||0==b.m||!c.f||(this.f={name:c.f.name,C:b}):this.f={name:b.f.name,C:c})}q(Zb,H);
function ac(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof D&&c instanceof D){e=Ub(b);for(d=G(e);d;d=G(e))for(b=Ub(c),f=G(b);f;f=G(b))if(a(C(d),C(f)))return!0;return!1}if(b instanceof D||c instanceof D){b instanceof D?e=b:(e=c,c=b);e=Ub(e);b=typeof c;for(d=G(e);d;d=G(e)){switch(b){case "number":d=+C(d);break;case "boolean":d=!!C(d);break;case "string":d=C(d);break;default:throw Error("Illegal primitive type for comparison.");}if(a(d,c))return!0}return!1}return e?"boolean"==typeof b||"boolean"==
typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Zb.prototype.a=function(a){return this.c.u(this.j,this.B,a)};Zb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+I(this.j);return a+=I(this.B)};function bc(a,b,c,d){this.a=a;this.R=b;this.m=c;this.u=d}bc.prototype.toString=function(){return this.a};var cc={};
function M(a,b,c,d){if(cc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new bc(a,b,c,d);return cc[a.toString()]=a}M("div",6,1,function(a,b,c){return K(a,c)/K(b,c)});M("mod",6,1,function(a,b,c){return K(a,c)%K(b,c)});M("*",6,1,function(a,b,c){return K(a,c)*K(b,c)});M("+",5,1,function(a,b,c){return K(a,c)+K(b,c)});M("-",5,1,function(a,b,c){return K(a,c)-K(b,c)});M("<",4,2,function(a,b,c){return ac(function(a,b){return a<b},a,b,c)});
M(">",4,2,function(a,b,c){return ac(function(a,b){return a>b},a,b,c)});M("<=",4,2,function(a,b,c){return ac(function(a,b){return a<=b},a,b,c)});M(">=",4,2,function(a,b,c){return ac(function(a,b){return a>=b},a,b,c)});var $b=M("=",3,2,function(a,b,c){return ac(function(a,b){return a==b},a,b,c,!0)});M("!=",3,2,function(a,b,c){return ac(function(a,b){return a!=b},a,b,c,!0)});M("and",2,2,function(a,b,c){return Yb(a,c)&&Yb(b,c)});M("or",1,2,function(a,b,c){return Yb(a,c)||Yb(b,c)});function dc(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");H.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}q(dc,H);dc.prototype.a=function(a){a=this.c.a(a);return ec(this.j,a)};dc.prototype.toString=function(){var a;a="Filter:"+I(this.c);return a+=I(this.j)};function fc(a,b){if(b.length<a.P)throw Error("Function "+a.o+" expects at least"+a.P+" arguments, "+b.length+" given");if(null!==a.H&&b.length>a.H)throw Error("Function "+a.o+" expects at most "+a.H+" arguments, "+b.length+" given");a.ba&&t(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});H.call(this,a.m);this.j=a;this.c=b;Wb(this,a.i||za(b,function(a){return a.i}));Xb(this,a.aa&&!b.length||a.Z&&!!b.length||za(b,function(a){return a.b}))}
q(fc,H);fc.prototype.a=function(a){return this.j.u.apply(null,Ca(a,this.c))};fc.prototype.toString=function(){var a="Function: "+this.j;if(this.c.length)var b=ya(this.c,function(a,b){return a+I(b)},"Arguments:"),a=a+I(b);return a};function gc(a,b,c,d,e,f,g,k,n){this.o=a;this.m=b;this.i=c;this.aa=d;this.Z=e;this.u=f;this.P=g;this.H=aa(k)?k:g;this.ba=!!n}gc.prototype.toString=function(){return this.o};var hc={};
function N(a,b,c,d,e,f,g,k){if(hc.hasOwnProperty(a))throw Error("Function already created: "+a+".");hc[a]=new gc(a,b,c,d,!1,e,f,g,k)}N("boolean",2,!1,!1,function(a,b){return Yb(b,a)},1);N("ceiling",1,!1,!1,function(a,b){return Math.ceil(K(b,a))},1);N("concat",3,!1,!1,function(a,b){return ya(Da(arguments,1),function(b,d){return b+L(d,a)},"")},2,null);N("contains",2,!1,!1,function(a,b,c){b=L(b,a);a=L(c,a);return-1!=b.indexOf(a)},2);N("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
N("false",2,!1,!1,function(){return!1},0);N("floor",1,!1,!1,function(a,b){return Math.floor(K(b,a))},1);N("id",4,!1,!1,function(a,b){function c(a){if(zb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ba(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=L(b,a).split(/\s+/),f=[];t(d,function(a){a=c(a);!a||0<=wa(f,a)||f.push(a)});f.sort(kb);var g=new D;t(f,function(a){E(g,a)});return g},1);
N("lang",2,!1,!1,function(){return!1},1);N("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);N("local-name",3,!1,!0,function(a,b){var c=b?Tb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);N("name",3,!1,!0,function(a,b){var c=b?Tb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);N("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
N("normalize-space",3,!1,!0,function(a,b){return(b?L(b,a):C(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);N("not",2,!1,!1,function(a,b){return!Yb(b,a)},1);N("number",1,!1,!0,function(a,b){return b?K(b,a):+C(a.a)},0,1);N("position",1,!0,!1,function(a){return a.b},0);N("round",1,!1,!1,function(a,b){return Math.round(K(b,a))},1);N("starts-with",2,!1,!1,function(a,b,c){return pa(L(b,a),L(c,a))},2);N("string",3,!1,!0,function(a,b){return b?L(b,a):C(a.a)},0,1);
N("string-length",1,!1,!0,function(a,b){return(b?L(b,a):C(a.a)).length},0,1);N("substring",3,!1,!1,function(a,b,c,d){c=K(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?K(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=L(b,a);if(Infinity==d)return a.substring(e);b=Math.round(d);return a.substring(e,c+b)},2,3);N("substring-after",3,!1,!1,function(a,b,c){b=L(b,a);a=L(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
N("substring-before",3,!1,!1,function(a,b,c){b=L(b,a);a=L(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);N("sum",1,!1,!1,function(a,b){for(var c=Ub(b.a(a)),d=0,e=G(c);e;e=G(c))d+=+C(e);return d},1,1,!0);N("translate",3,!1,!1,function(a,b,c,d){b=L(b,a);c=L(c,a);var e=L(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);N("true",2,!1,!1,function(){return!0},0);function F(a,b){this.j=a;this.c=aa(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function ic(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}F.prototype.a=function(a){return null===this.b||this.b==a.nodeType};F.prototype.f=function(){return this.j};
F.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=I(this.c));return a};function jc(a){H.call(this,3);this.c=a.substring(1,a.length-1)}q(jc,H);jc.prototype.a=function(){return this.c};jc.prototype.toString=function(){return"Literal: "+this.c};function Mb(a,b){this.o=a.toLowerCase();this.c=b?b.toLowerCase():"http://www.w3.org/1999/xhtml"}Mb.prototype.a=function(a){var b=a.nodeType;return 1!=b&&2!=b?!1:"*"!=this.o&&this.o!=a.nodeName.toLowerCase()?!1:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Mb.prototype.f=function(){return this.o};Mb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function kc(a){H.call(this,1);this.c=a}q(kc,H);kc.prototype.a=function(){return this.c};kc.prototype.toString=function(){return"Number: "+this.c};function lc(a,b){H.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.G||c.c!=mc||(c=c.B,"*"!=c.f()&&(this.f={name:c.f(),C:null}))}}q(lc,H);function nc(){H.call(this,4)}q(nc,H);nc.prototype.a=function(a){var b=new D;a=a.a;9==a.nodeType?E(b,a):E(b,a.ownerDocument);return b};nc.prototype.toString=function(){return"Root Helper Expression"};function oc(){H.call(this,4)}q(oc,H);oc.prototype.a=function(a){var b=new D;E(b,a.a);return b};oc.prototype.toString=function(){return"Context Helper Expression"};
function pc(a){return"/"==a||"//"==a}lc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof D))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=Ub(b,e.c.a),g;if(e.i||e.c!=qc)if(e.i||e.c!=rc)for(g=G(f),b=e.a(new yb(g));null!=(g=G(f));)g=e.a(new yb(g)),b=Sb(b,g);else g=G(f),b=e.a(new yb(g));else{for(g=G(f);(b=G(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new yb(g))}}return b};
lc.prototype.toString=function(){var a;a="Path Expression:"+I(this.j);if(this.c.length){var b=ya(this.c,function(a,b){return a+I(b)},"Steps:");a+=I(b)}return a};function sc(a,b){this.a=a;this.b=!!b}
function ec(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Ub(b),f=b.s,g,k=0;g=G(e);k++){var n=a.b?f-k:k+1;g=d.a(new yb(g,n,f));if("number"==typeof g)n=n==g;else if("string"==typeof g||"boolean"==typeof g)n=!!g;else if(g instanceof D)n=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!n){n=e;g=n.f;var r=n.a;if(!r)throw Error("Next must be called at least once before remove.");var p=r.b,r=r.a;p?p.a=r:g.a=r;r?r.b=p:g.b=p;g.s--;n.a=null}}return b}
sc.prototype.toString=function(){return ya(this.a,function(a,b){return a+I(b)},"Predicates:")};function tc(a,b,c,d){H.call(this,4);this.c=a;this.B=b;this.j=c||new sc([]);this.G=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=zb?a.toLowerCase():a,this.f={name:a,C:b.C});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}q(tc,H);
tc.prototype.a=function(a){var b=a.a,c=null,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.C?L(c.C,a):null,f=1);if(this.G)if(this.i||this.c!=uc)if(a=Ub((new tc(vc,new F("node"))).a(a)),b=G(a))for(c=this.u(b,d,e,f);null!=(b=G(a));)c=Sb(c,this.u(b,d,e,f));else c=new D;else c=Jb(this.B,b,d,e),c=ec(this.j,c,f);else c=this.u(a.a,d,e,f);return c};tc.prototype.u=function(a,b,c,d){a=this.c.f(this.B,a,b,c);return a=ec(this.j,a,d)};
tc.prototype.toString=function(){var a;a="Step:"+I("Operator: "+(this.G?"//":"/"));this.c.o&&(a+=I("Axis: "+this.c));a+=I(this.B);if(this.j.a.length){var b=ya(this.j.a,function(a,b){return a+I(b)},"Predicates:");a+=I(b)}return a};function wc(a,b,c,d){this.o=a;this.f=b;this.a=c;this.b=d}wc.prototype.toString=function(){return this.o};var xc={};function O(a,b,c,d){if(xc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new wc(a,b,c,!!d);return xc[a]=b}
O("ancestor",function(a,b){for(var c=new D,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);O("ancestor-or-self",function(a,b){var c=new D,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var mc=O("attribute",function(a,b){var c=new D,d=a.f();if("style"==d&&b.style&&zb)return E(c,new Bb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof F&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)zb?f.nodeValue&&E(c,Cb(b,f)):E(c,f);else(f=e.getNamedItem(d))&&(zb?f.nodeValue&&E(c,Cb(b,f)):E(c,f));return c},!1),uc=O("child",function(a,b,c,d,e){return(zb?Pb:Qb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new D)},!1,!0);O("descendant",Jb,!1,!0);
var vc=O("descendant-or-self",function(a,b,c,d){var e=new D;Ib(b,c,d)&&a.a(b)&&E(e,b);return Jb(a,b,c,d,e)},!1,!0),qc=O("following",function(a,b,c,d){var e=new D;do for(var f=b;f=f.nextSibling;)Ib(f,c,d)&&a.a(f)&&E(e,f),e=Jb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);O("following-sibling",function(a,b){for(var c=new D,d=b;d=d.nextSibling;)a.a(d)&&E(c,d);return c},!1);O("namespace",function(){return new D},!1);
var yc=O("parent",function(a,b){var c=new D;if(9==b.nodeType)return c;if(2==b.nodeType)return E(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&E(c,d);return c},!1),rc=O("preceding",function(a,b,c,d){var e=new D,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var n=[];for(b=f[g];b=b.previousSibling;)n.unshift(b);for(var r=0,p=n.length;r<p;r++)b=n[r],Ib(b,c,d)&&a.a(b)&&E(e,b),e=Jb(a,b,c,d,e)}return e},!0,!0);
O("preceding-sibling",function(a,b){for(var c=new D,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var zc=O("self",function(a,b){var c=new D;a.a(b)&&E(c,b);return c},!1);function Ac(a){H.call(this,1);this.c=a;this.i=a.i;this.b=a.b}q(Ac,H);Ac.prototype.a=function(a){return-K(this.c,a)};Ac.prototype.toString=function(){return"Unary Expression: -"+I(this.c)};function Bc(a){H.call(this,4);this.c=a;Wb(this,za(this.c,function(a){return a.i}));Xb(this,za(this.c,function(a){return a.b}))}q(Bc,H);Bc.prototype.a=function(a){var b=new D;t(this.c,function(c){c=c.a(a);if(!(c instanceof D))throw Error("Path expression must evaluate to NodeSet.");b=Sb(b,c)});return b};Bc.prototype.toString=function(){return ya(this.c,function(a,b){return a+I(b)},"Union Expression:")};function Cc(a,b){this.a=a;this.b=b}function Dc(a){for(var b,c=[];;){P(a,"Missing right hand side of binary expression.");b=Ec(a);var d=B(a.a);if(!d)break;var e=(d=cc[d]||null)&&d.R;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].R;)b=new Zb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Zb(c.pop(),c.pop(),b);return b}function P(a,b){if(Hb(a.a))throw Error(b);}function Fc(a,b){var c=B(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Ic(a){a=B(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Jc(a){a=B(a.a);if(2>a.length)throw Error("Unclosed literal string");return new jc(a)}function Kc(a){var b=B(a.a),c=b.indexOf(":");if(-1==c)return new Mb(b);var d=b.substring(0,c);a=a.b(d);if(!a)throw Error("Namespace prefix not declared: "+d);b=b.substr(c+1);return new Mb(b,a)}
function Lc(a){var b,c=[],d;if(pc(A(a.a))){b=B(a.a);d=A(a.a);if("/"==b&&(Hb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new nc;d=new nc;P(a,"Missing next location step.");b=Mc(a,b);c.push(b)}else{a:{b=A(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":B(a.a);b=Dc(a);P(a,'unclosed "("');Fc(a,")");break;case '"':case "'":b=Jc(a);break;default:if(isNaN(+b))if(!ic(b)&&/(?![0-9])[\w]/.test(d)&&"("==A(a.a,1)){b=B(a.a);
b=hc[b]||null;B(a.a);for(d=[];")"!=A(a.a);){P(a,"Missing function argument list.");d.push(Dc(a));if(","!=A(a.a))break;B(a.a)}P(a,"Unclosed function argument list.");Ic(a);b=new fc(b,d)}else{b=null;break a}else b=new kc(+B(a.a))}"["==A(a.a)&&(d=new sc(Nc(a)),b=new dc(b,d))}if(b)if(pc(A(a.a)))d=b;else return b;else b=Mc(a,"/"),d=new oc,c.push(b)}for(;pc(A(a.a));)b=B(a.a),P(a,"Missing next location step."),b=Mc(a,b),c.push(b);return new lc(d,c)}
function Mc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==A(a.a))return d=new tc(zc,new F("node")),B(a.a),d;if(".."==A(a.a))return d=new tc(yc,new F("node")),B(a.a),d;var f;if("@"==A(a.a))f=mc,B(a.a),P(a,"Missing attribute name");else if("::"==A(a.a,1)){if(!/(?![0-9])[\w]/.test(A(a.a).charAt(0)))throw Error("Bad token: "+B(a.a));c=B(a.a);f=xc[c]||null;if(!f)throw Error("No axis with name: "+c);B(a.a);P(a,"Missing node name")}else f=uc;c=A(a.a);if(/(?![0-9])[\w]/.test(c.charAt(0)))if("("==
A(a.a,1)){if(!ic(c))throw Error("Invalid node type: "+c);c=B(a.a);if(!ic(c))throw Error("Invalid type name: "+c);Fc(a,"(");P(a,"Bad nodetype");e=A(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Jc(a);P(a,"Bad nodetype");Ic(a);c=new F(c,g)}else c=Kc(a);else if("*"==c)c=Kc(a);else throw Error("Bad token: "+B(a.a));e=new sc(Nc(a),f.a);return d||new tc(f,c,e,"//"==b)}
function Nc(a){for(var b=[];"["==A(a.a);){B(a.a);P(a,"Missing predicate expression.");var c=Dc(a);b.push(c);P(a,"Unclosed predicate expression.");Fc(a,"]")}return b}function Ec(a){if("-"==A(a.a))return B(a.a),new Ac(Ec(a));var b=Lc(a);if("|"!=A(a.a))a=b;else{for(b=[b];"|"==B(a.a);)P(a,"Missing next union location path."),b.push(Lc(a));a.a.a--;a=new Bc(b)}return a};function Oc(a){switch(a.nodeType){case 1:return ja(Pc,a);case 9:return Oc(a.documentElement);case 11:case 10:case 6:case 12:return Qc;default:return a.parentNode?Oc(a.parentNode):Qc}}function Qc(){return null}function Pc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Pc(a.parentNode,b):null};function Rc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Eb(a);if(Hb(c))throw Error("Invalid XPath expression.");b?ea(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var d=Dc(new Cc(c,b));if(!Hb(c))throw Error("Bad token: "+B(c));this.evaluate=function(a,b){var c=d.a(new yb(a));return new Q(c,b)}}
function Q(a,b){if(0==b)if(a instanceof D)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof D))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof D?a.f():""+a;break;case 1:this.numberValue=a instanceof D?+a.f():+a;break;case 3:this.booleanValue=a instanceof D?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var d=
Ub(a);c=[];for(var e=G(d);e;e=G(d))c.push(e instanceof Bb?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:d=Tb(a);this.singleNodeValue=d instanceof Bb?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}Q.ANY_TYPE=0;Q.NUMBER_TYPE=1;Q.STRING_TYPE=2;Q.BOOLEAN_TYPE=3;Q.UNORDERED_NODE_ITERATOR_TYPE=4;Q.ORDERED_NODE_ITERATOR_TYPE=5;Q.UNORDERED_NODE_SNAPSHOT_TYPE=6;Q.ORDERED_NODE_SNAPSHOT_TYPE=7;Q.ANY_UNORDERED_NODE_TYPE=8;Q.FIRST_ORDERED_NODE_TYPE=9;function Sc(a){this.lookupNamespaceURI=Oc(a)}
function Tc(a){a=a||l;var b=a.document;b.evaluate||(a.XPathResult=Q,b.evaluate=function(a,b,e,f){return(new Rc(a,e)).evaluate(b,f)},b.createExpression=function(a,b){return new Rc(a,b)},b.createNSResolver=function(a){return new Sc(a)})}ba("wgxpath.install",Tc);var R={};R.I=function(){var a={ga:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
R.u=function(a,b,c){var d=y(a);if(!d.documentElement)return null;(x||vb)&&Tc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):R.I;if(x&&!ab(7))return d.evaluate.call(d,b,a,e,c,null);if(!x||9<=cb){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var n=g[k],r=n.namespaceURI;if(r&&!f[r]){var p=n.lookupPrefix(r);if(!p){var z=r.match(".*/(\\w+)/?$");z?p=z[1]:p="xhtml"}f[r]=p}}var J={},ka;for(ka in f)J[f[ka]]=ka;e=function(a){return J[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(Gc){if("TypeError"===Gc.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):R.I,d.evaluate(b,a,e,c,null);throw Gc;}}catch(Hc){if(!Ta||"NS_ERROR_ILLEGAL_VALUE"!=Hc.name)throw new u(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Hc);}};R.J=function(a,b){if(!a||1!=a.nodeType)throw new u(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
R.v=function(a,b){var c=function(){var c=R.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=y(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||R.J(c,a);return c};
R.w=function(a,b){var c=function(){var c=R.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=y(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();t(c,function(b){R.J(b,a)});return c};function Uc(a){return(a=a.exec(La))?a[1]:""}var Vc=function(){if(sb)return Uc(/Firefox\/([0-9.]+)/);if(x||Sa||Ra)return Za;if(wb)return Uc(/Chrome\/([0-9.]+)/);if(xb&&!(Qa()||w("iPad")||w("iPod")))return Uc(/Version\/([0-9.]+)/);if(tb||ub){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(La))return a[1]+"."+a[2]}else if(vb)return(a=Uc(/Android\s+([0-9.]+)/))?a:Uc(/Version\/([0-9.]+)/);return""}();var Wc={},Xc,Yc;function Zc(a){return $c?Xc(a):x?0<=sa(cb,a):ab(a)}function ad(a){return $c?Yc(a):vb?0<=sa(bd,a):0<=sa(Vc,a)}
var $c=function(){if(!Ta)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(b){return!1}var c=a.classes,a=a.interfaces,d=c["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),c=c["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=c.platformVersion,f=c.version;Xc=function(a){return 0<=d.compare(e,""+a)};Yc=function(a){return 0<=d.compare(f,""+a)};return!0}(),cd;if(vb){var dd=/Android\s+([0-9\.]+)/.exec(La);cd=dd?dd[1]:"0"}else cd="0";
var bd=cd,ed=x&&!(8<=cb),fd=x&&!(9<=cb);vb&&ad(2.3);vb&&ad(4);xb&&ad(6);function gd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=gd.prototype;h.clone=function(){return new gd(this.top,this.right,this.bottom,this.left)};h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof gd?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function S(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=S.prototype;h.clone=function(){return new S(this.left,this.top,this.width,this.height)};h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof S?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function T(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}function hd(a,b){var c;if(c=ed&&"value"==b&&T(a,"OPTION"))c=null===id(a,"value");c?(c=[],pb(a,c,!1),c=c.join("")):c=a[b];return c}var jd=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function kd(a){var b=[];t(a.split(jd),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function id(a,b){b=b.toLowerCase();if("style"==b)return kd(a.style.cssText);if(ed&&"value"==b&&T(a,"INPUT"))return a.value;if(fd&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}
function ld(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return T(a)?a:null}
function U(a,b){var c=ua(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=fd?"styleFloat":"cssFloat";var d;a:{d=c;var e=y(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||md(a,c);if(null===d)d=null;else if(0<=wa(Fa,c)){b:{var f=d.match(Ia);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ja))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Ea[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Ga,"#$1$1$2$2$3$3")),!Ha.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function md(a,b){var c=a.currentStyle||a.style,d=c[b];!aa(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?aa(d)?d:null:(c=ld(a))?md(c,b):null}
function nd(a,b,c){function d(a){var b=od(a);return 0<b.height&&0<b.width?!0:T(a,"PATH")&&(0<b.height||0<b.width)?(a=U(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=U(a,"overflow")&&za(a.childNodes,function(a){return 3==a.nodeType||T(a)&&d(a)})}function e(a){return pd(a)==V&&Aa(a.childNodes,function(a){return!T(a)||e(a)||!d(a)})}if(!T(a))throw Error("Argument to isShown must be of type Element");if(T(a,"BODY"))return!0;if(T(a,"OPTION")||T(a,"OPTGROUP"))return a=qb(a,function(a){return T(a,"SELECT")}),
!!a&&nd(a,!0,c);var f=qd(a);if(f)return!!f.M&&0<f.rect.width&&0<f.rect.height&&nd(f.M,b,c);if(T(a,"INPUT")&&"hidden"==a.type.toLowerCase()||T(a,"NOSCRIPT"))return!1;f=U(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=rd(a))&&d(a)?!e(a):!1}function sd(a){function b(a){if("none"==U(a,"display"))return!1;a=ld(a);return!a||b(a)}return nd(a,!1,b)}var V="hidden";
function pd(a){function b(a){function b(a){if(a==g)return!0;var d=U(a,"display");return pa(d,"inline")||"absolute"==c&&"static"==U(a,"position")?!1:!0}var c=U(a,"position");if("fixed"==c)return r=!0,a==g?null:g;for(a=ld(a);a&&!b(a);)a=ld(a);return a}function c(a){var b=a;if("visible"==n)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:U(b,"overflow-x"),y:U(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new gb(f)).a;
a=b.scrollingElement?b.scrollingElement:Ua||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=x&&ab("10")&&b.pageYOffset!=a.scrollTop?new db(a.scrollLeft,a.scrollTop):new db(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new db(a.scrollLeft,a.scrollTop);return a}var e=td(a),f=y(a),g=f.documentElement,k=f.body,n=U(g,"overflow"),r;for(a=b(a);a;a=b(a)){var p=c(a);if("visible"!=p.x||"visible"!=p.y){var z=od(a);if(0==z.width||0==z.height)return V;
var J=e.right<z.left,ka=e.bottom<z.top;if(J&&"hidden"==p.x||ka&&"hidden"==p.y)return V;if(J&&"visible"!=p.x||ka&&"visible"!=p.y){J=d(a);ka=e.bottom<z.top-J.y;if(e.right<z.left-J.x&&"visible"!=p.x||ka&&"visible"!=p.x)return V;e=pd(a);return e==V?V:"scroll"}J=e.left>=z.left+z.width;z=e.top>=z.top+z.height;if(J&&"hidden"==p.x||z&&"hidden"==p.y)return V;if(J&&"visible"!=p.x||z&&"visible"!=p.y){if(r&&(p=d(a),e.left>=g.scrollWidth-p.x||e.right>=g.scrollHeight-p.y))return V;e=pd(a);return e==V?V:"scroll"}}}return"none"}
function od(a){var b=qd(a);if(b)return b.rect;if(T(a,"HTML"))return a=y(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new eb(a.clientWidth,a.clientHeight),new S(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new S(0,0,0,0)}b=new S(c.left,c.top,c.right-c.left,c.bottom-c.top);x&&a.ownerDocument.body&&(a=y(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function qd(a){var b=T(a,"MAP");if(!b&&!T(a,"AREA"))return null;var c=b?a:T(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name&&(d=R.v('/descendant::*[@usemap = "#'+c.name+'"]',y(c)))&&(e=od(d),!b&&"default"!=a.shape.toLowerCase())){var f=ud(a);a=Math.min(Math.max(f.left,0),e.width);b=Math.min(Math.max(f.top,0),e.height);c=Math.min(f.width,e.width-a);f=Math.min(f.height,e.height-b);e=new S(a+e.left,b+e.top,c,f)}return{M:d,rect:e||new S(0,0,0,0)}}
function ud(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new S(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new S(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new S(b,c,d-b,e-c)}return new S(0,0,0,0)}function td(a){a=od(a);return new gd(a.top,a.left+a.width,a.top+a.height,a.left)}
function vd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function wd(a){var b=[];xd(a,b);var c=b;a=c.length;for(var b=Array(a),c=m(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=vd.call(void 0,c[d]));return vd(b.join("\n")).replace(/\xa0/g," ")}
function yd(a,b,c){if(T(a,"BR"))b.push("");else{var d=T(a,"TD"),e=U(a,"display"),f=!d&&!(0<=wa(zd,e)),g=aa(a.previousElementSibling)?a.previousElementSibling:ib(a.previousSibling),g=g?U(g,"display"):"",k=U(a,"float")||U(a,"cssFloat")||U(a,"styleFloat");!f||"run-in"==g&&"none"==k||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var n=sd(a),r=null,p=null;n&&(r=U(a,"white-space"),p=U(a,"text-transform"));t(a.childNodes,function(a){c(a,b,n,r,p)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||qa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function xd(a,b){yd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Ad(a,b,f,g):T(a)&&xd(a,b)})}var zd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Ad(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";qa(c," ")&&pa(a," ")&&(a=a.substr(1));b.push(c+a)}
function rd(a){if(fd){if("relative"==U(a,"position"))return 1;a=U(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Bd(a)}function Bd(a){var b=1,c=U(a,"opacity");c&&(b=Number(c));(a=ld(a))&&(b*=Bd(a));return b};var Cd={D:function(a){return!(!a.querySelectorAll||!a.querySelector)},v:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,"Compound class names not permitted");if(Cd.D(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new u(32,"An invalid or illegal class name was specified");}var d=rb(fb(b),"*",a,b);return d.length?d[0]:null},w:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,
"Compound class names not permitted");if(Cd.D(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new u(32,"An invalid or illegal class name was specified");}return rb(fb(b),"*",a,b)}};var Dd={v:function(a,b){if(!ea(b.querySelector)&&x&&Zc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);var c;try{c=b.querySelector(a)}catch(d){throw new u(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},w:function(a,b){if(!ea(b.querySelectorAll)&&x&&Zc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);try{return b.querySelectorAll(a)}catch(c){throw new u(32,
"An invalid or illegal selector was specified");}}};var Ed={D:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},v:function(a,b){var c=fb(b),d=m(a)?c.a.getElementById(a):a;if(!d)return null;if(id(d,"id")==a&&jb(b,d))return d;c=rb(c,"*");return Ba(c,function(c){return id(c,"id")==a&&jb(b,c)})},w:function(a,b){if(!a)return[];if(Ed.D(b,a))try{return b.querySelectorAll("#"+Ed.W(a))}catch(c){return[]}var d=rb(fb(b),"*",null,b);return xa(d,function(b){return id(b,"id")==a})},W:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var W={},Fd={};W.S=function(a,b,c){var d;try{d=Dd.w("a",b)}catch(e){d=rb(fb(b),"A",null,b)}return Ba(d,function(b){b=wd(b);return c&&-1!=b.indexOf(a)||b==a})};W.N=function(a,b,c){var d;try{d=Dd.w("a",b)}catch(e){d=rb(fb(b),"A",null,b)}return xa(d,function(b){b=wd(b);return c&&-1!=b.indexOf(a)||b==a})};W.v=function(a,b){return W.S(a,b,!1)};W.w=function(a,b){return W.N(a,b,!1)};Fd.v=function(a,b){return W.S(a,b,!0)};Fd.w=function(a,b){return W.N(a,b,!0)};var Gd={v:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},w:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Hd={className:Cd,"class name":Cd,css:Dd,"css selector":Dd,id:Ed,linkText:W,"link text":W,name:{v:function(a,b){var c=rb(fb(b),"*",null,b);return Ba(c,function(b){return id(b,"name")==a})},w:function(a,b){var c=rb(fb(b),"*",null,b);return xa(c,function(b){return id(b,"name")==a})}},partialLinkText:Fd,"partial link text":Fd,tagName:Gd,"tag name":Gd,xpath:R};
function Id(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Hd[c];if(d&&ea(d.v))return d.v(a[c],b||ma.document)}throw Error("Unsupported locator strategy: "+c);};Ua||$c&&ad(3.6);x&&Zc(10);vb&&ad(4);function Jd(a,b){this.A={};this.l=[];this.b=this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)Kd(this,arguments[d],arguments[d+1])}else if(a){var e;if(a instanceof Jd)for(d=Ld(a),Md(a),e=[],c=0;c<a.l.length;c++)e.push(a.A[a.l[c]]);else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)Kd(this,d[c],e[c])}}function Ld(a){Md(a);return a.l.concat()}
Jd.prototype.clear=function(){this.A={};this.b=this.a=this.l.length=0};function Md(a){if(a.a!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];Object.prototype.hasOwnProperty.call(a.A,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.a!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],Object.prototype.hasOwnProperty.call(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}Jd.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.A,a)?this.A[a]:b};
function Kd(a,b,c){Object.prototype.hasOwnProperty.call(a.A,b)||(a.a++,a.l.push(b),a.b++);a.A[b]=c}Jd.prototype.forEach=function(a,b){for(var c=Ld(this),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};Jd.prototype.clone=function(){return new Jd(this)};var Nd={};function X(a,b,c){fa(a)&&(a=Ta?a.g:a.h);a=new Od(a);!b||b in Nd&&!c||(Nd[b]={key:a,shift:!1},c&&(Nd[c]={key:a,shift:!0}));return a}function Od(a){this.code=a}X(8);X(9);X(13);var Pd=X(16),Qd=X(17),Rd=X(18);X(19);X(20);X(27);X(32," ");X(33);X(34);X(35);X(36);X(37);X(38);X(39);X(40);X(44);X(45);X(46);X(48,"0",")");X(49,"1","!");X(50,"2","@");X(51,"3","#");X(52,"4","$");X(53,"5","%");X(54,"6","^");X(55,"7","&");X(56,"8","*");X(57,"9","(");X(65,"a","A");X(66,"b","B");X(67,"c","C");X(68,"d","D");
X(69,"e","E");X(70,"f","F");X(71,"g","G");X(72,"h","H");X(73,"i","I");X(74,"j","J");X(75,"k","K");X(76,"l","L");X(77,"m","M");X(78,"n","N");X(79,"o","O");X(80,"p","P");X(81,"q","Q");X(82,"r","R");X(83,"s","S");X(84,"t","T");X(85,"u","U");X(86,"v","V");X(87,"w","W");X(88,"x","X");X(89,"y","Y");X(90,"z","Z");var Sd=X(Wa?{g:91,h:91}:Va?{g:224,h:91}:{g:0,h:91});X(Wa?{g:92,h:92}:Va?{g:224,h:93}:{g:0,h:92});X(Wa?{g:93,h:93}:Va?{g:0,h:0}:{g:93,h:null});X({g:96,h:96},"0");X({g:97,h:97},"1");
X({g:98,h:98},"2");X({g:99,h:99},"3");X({g:100,h:100},"4");X({g:101,h:101},"5");X({g:102,h:102},"6");X({g:103,h:103},"7");X({g:104,h:104},"8");X({g:105,h:105},"9");X({g:106,h:106},"*");X({g:107,h:107},"+");X({g:109,h:109},"-");X({g:110,h:110},".");X({g:111,h:111},"/");X(144);X(112);X(113);X(114);X(115);X(116);X(117);X(118);X(119);X(120);X(121);X(122);X(123);X({g:107,h:187},"=","+");X(108,",");X({g:109,h:189},"-","_");X(188,",","<");X(190,".",">");X(191,"/","?");X(192,"`","~");X(219,"[","{");
X(220,"\\","|");X(221,"]","}");X({g:59,h:186},";",":");X(222,"'",'"');var Td=new Jd;Kd(Td,1,Pd);Kd(Td,2,Qd);Kd(Td,4,Rd);Kd(Td,8,Sd);(function(a){var b=new Jd;t(Ld(a),function(c){Kd(b,a.get(c).code,c)});return b})(Td);Ta&&Zc(12);function Y(a){na.call(this,a)}q(Y,na);Ua||Ta&&Zc(3.5)||x&&Zc(8);var Ud={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Y("Illegal Index: "+a);if(b.length<=c)throw new Y("Index out of range: "+a);return[b[c]]},name:function(a,b){return xa(b,function(b){return hd(b,"name")==a})},value:function(a,b){return xa(b,function(b){return hd(b,"value")===a})}};function Vd(a,b){return(new RegExp(a)).test(b)}function Wd(a,b){return(new RegExp(a,"i")).test(b)}function Xd(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Yd={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Xd(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Xd(a))).test(b)},regex:Vd,regexi:Wd,regexpi:Wd,regexp:Vd};
function Zd(a){var b="glob",c=/^([a-zA-Z-]+):(.*)/.exec(a);if(c){var d=c[1],c=c[2];Yd[d.toLowerCase()]&&(b=d.toLowerCase(),a=c)}d=Yd[b];if(!d)throw new Y("Cannot find pattern matching strategy: "+b);"glob"==b?(0==a.indexOf("glob:")&&(a=a.substring(5)),d=Yd.glob):"exact"==b&&0==a.indexOf("exact:")&&(a=a.substring(6));a=ja(d,a);a.ea=b;return a};function $d(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=$d(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Wc.ca&&ad(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={Y:function(a,b){return pa(a,"//")?Z.T(a,b):pa(a,"document.")?Z.K(a,b):Z.L(a,b)},U:function(a,b){return ae(b||y(ma),function(b){return b.alt==a})},V:function(a,b){return ae(b||y(ma),function(b){return b.className==a})},K:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},X:function(a,b){return Id({id:a},b)},L:function(a,b){return Z.id(a,b)||Z.name(a,b)},o:function(a,b){var c=b||y(ma);fb(c);var d;d=hb(document,"*",null,c);c=a.split(" ");for(c[0]="name="+c[0];c.length;){var e=
c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=Ud[d];if(!g)throw new Y("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},$:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,k=g.$wdc_;k||(k=g.$wdc_={},k.O=la());k.O||(k.O=la());f=k;if(!(null!==f&&d in f))throw new u(10,"Element does not exist in cache");var n=f[d];if(null!==n&&"setInterval"in n){if(n.closed)throw delete f[d],new u(23,
"Window has been closed.");c=n}else{for(g=n;g;){if(g==e.documentElement){c=n;break a}g=g.parentNode}delete f[d];throw new u(10,"Element is no longer attached to the DOM");}}return c}catch(r){return null}},T:function(a,b){var c=qa(a,"/"),d={xpath:a};try{var e=Id(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Id(d,b)}};Z.alt=Z.U;Z["class"]=Z.V;Z.dom=Z.K;Z.id=Z.X;Z.identifier=Z.L;Z.implicit=Z.Y;
Z.link=function(a,b){for(var c=(b||y(ma)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";Ta&&"1.8"<=Za||Ua||x?g=$d(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Ua)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");g=f;f=ra(g);if(Zd(a)(f))return e}return null};Z.name=Z.o;Z.stored=Z.$;Z.xpath=Z.T;function be(a,b,c,d){var e=Z[a];if(!e)throw new Y("Unrecognised locator type: '"+a+"'");c=e.call(null,b,c);if(null!=c)return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=be(a,b,f,d.frames[e]),null!=c))return c}return null}function ae(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType){if(b(e))return e;if(e=ae(e,b))return e}}return null};function ce(a){var b=Zd(a);return{F:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].text))return c.options[d];throw new Y("Option with label '"+a+"' not found");},a:function(c){c=c.options[c.selectedIndex].text;if(!b(c))throw new Y("Expected text ("+a+") did not match: "+c);}}}
var de={id:function(a){var b=Zd(a);return{F:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].id))return c.options[d];throw new Y("Option with id '"+a+"' not found");},a:function(c){c=c.options[c.selectedIndex].id;if(!b(c))throw new Y("Expected id ("+a+") did not match: "+c);}}},index:function(a){var b=Number(a);if(isNaN(b)||0>b)throw new Y("Illegal Index: "+a);return{F:function(a){if(a.options.length<=b)throw new Y("Index out of range.  Only "+a.options.length+" options available");
return a.options[b]},a:function(a){if(b!=a.selectedIndex)throw new Y("Selected index ("+a.selectedIndex+") does not match expected index: "+b);}}},label:ce,text:ce,value:function(a){var b=Zd(a);return{F:function(c){for(var d=0;d<c.options.length;d++)if(b(c.options[d].value))return c.options[d];throw new Y("Option with value '"+a+"' not found");},a:function(c){c=c.options[c.selectedIndex].value;if(!b(c))throw new Y("Expected value ("+a+") did not match: "+c);}}}};ba("_",function(a,b){var c;if(m(a))if(m(a)){(c=a.match(/^([A-Za-z]+)=.+/))?(c=c[1].toLowerCase(),c={type:c,string:a.substring(c.length+1)}):(c={string:"",type:""},c.string=a,c.type=pa(a,"//")?"xpath":pa(a,"document.")?"dom":"identifier");var d=ma||ma;c=be(c.type,c.string,d.document,d);if(null==c)throw new Y("Element "+a+" not found");}else c=a;else c=a;if(!aa(c.options))throw new Y("Specified element is not a Select (has no options)");var d="label",e=b,f=b.match(/^([a-zA-Z]+)=(.*)/);f&&(d=f[1],e=
f[2]);if(f=de[d])d=f(e);else throw new Y("Unknown option locator type: "+d);return d.F(c)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
