function(){return function(){var n,p=this;function aa(a){return void 0!==a}function ba(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&aa(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){return"function"==ca(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){ia=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function r(a,b){function c(){}c.prototype=b.prototype;a.Ka=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Aa=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var la=window;function na(a){if(Error.captureStackTrace)Error.captureStackTrace(this,na);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(na,Error);na.prototype.name="CustomError";var oa;function pa(a,b){return 0==a.lastIndexOf(b,0)}function qa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function sa(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var A=m.exec(h)||["","",""],K=k.exec(l)||["","",""];if(0==A[0].length&&0==K[0].length)break;c=ta(0==A[1].length?0:parseInt(A[1],10),0==K[1].length?0:parseInt(K[1],10))||ta(0==A[2].length,0==K[2].length)||ta(A[2],K[2])}while(0==c)}return c}function ta(a,b){return a<b?-1:a>b?1:0}
function ua(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var va=Array.prototype;function wa(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function t(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function xa(a,b){for(var c=a.length,d=[],e=0,f=q(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function ya(a,b){for(var c=a.length,d=Array(c),e=q(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function za(a,b,c){var d=c;t(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function Aa(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Ba(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function Ca(a,b){var c;a:{c=a.length;for(var d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:q(a)?a.charAt(c):a[c]}function Da(a){return va.concat.apply(va,arguments)}function Ea(a,b,c){return 2>=arguments.length?va.slice.call(a,b):va.slice.call(a,b,c)};var Fa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ga="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ha=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ia=/^#(?:[0-9a-f]{3}){1,2}$/i,Ja=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ka=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function u(a,b){this.code=a;this.a=v[a]||La;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}r(u,Error);var La="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=La;v[30]=La;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=La;v[9]="unknown command";u.prototype.toString=function(){return this.name+": "+this.message};var Ma;a:{var Na=p.navigator;if(Na){var Oa=Na.userAgent;if(Oa){Ma=Oa;break a}}Ma=""}function w(a){return-1!=Ma.indexOf(a)};function Pa(){return w("Opera")||w("OPR")}function Qa(){return(w("Chrome")||w("CriOS"))&&!Pa()&&!w("Edge")};function Ra(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var Sa=Pa(),x=w("Trident")||w("MSIE"),Ta=w("Edge"),y=w("Gecko")&&!(-1!=Ma.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Ua=-1!=Ma.toLowerCase().indexOf("webkit")&&!w("Edge");function Va(){var a=Ma;if(y)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ta)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ua)return/WebKit\/(\S+)/.exec(a)}function Wa(){var a=p.document;return a?a.documentMode:void 0}
var Xa=function(){if(Sa&&p.opera){var a;var b=p.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Va())&&(a=b?b[1]:"");return x&&(b=Wa(),b>parseFloat(a))?String(b):a}(),Ya={};function Za(a){return Ya[a]||(Ya[a]=0<=sa(Xa,a))}var $a=p.document,ab=$a&&x?Wa()||("CSS1Compat"==$a.compatMode?parseInt(Xa,10):5):void 0;!y&&!x||x&&9<=ab||y&&Za("1.9.1");x&&Za("9");function bb(a,b){this.x=aa(a)?a:0;this.y=aa(b)?b:0}n=bb.prototype;n.clone=function(){return new bb(this.x,this.y)};n.toString=function(){return"("+this.x+", "+this.y+")"};n.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};n.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};n.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};n.scale=function(a,b){var c=da(b)?b:a;this.x*=a;this.y*=c;return this};function cb(a,b){this.width=a;this.height=b}n=cb.prototype;n.clone=function(){return new cb(this.width,this.height)};n.toString=function(){return"("+this.width+" x "+this.height+")"};n.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};n.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};n.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
n.scale=function(a,b){var c=da(b)?b:a;this.width*=a;this.height*=c;return this};function z(a){return a?new db(B(a)):oa||(oa=new db)}
function eb(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=wa(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;return a}return b}
function fb(a){return a.scrollingElement?a.scrollingElement:Ua||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function gb(a){return a?a.parentWindow||a.defaultView:window}function hb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function ib(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function jb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(x&&!(9<=ab)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?kb(a,b):!c&&ib(e,b)?-1*lb(a,b):!d&&ib(f,a)?lb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(p.Range.START_TO_END,d)}function lb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return kb(d,a)}function kb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var mb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},nb={IMG:" ",BR:"\n"};
function ob(a,b,c){if(!(a.nodeName in mb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in nb)b.push(nb[a.nodeName]);else for(a=a.firstChild;a;)ob(a,b,c),a=a.nextSibling}function pb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function db(a){this.a=a||p.document||document}function qb(a,b,c,d){return eb(a.a,b,c,d)}function rb(a){return fb(a.a)};var sb=w("Firefox"),tb=Ra()||w("iPod"),ub=w("iPad"),vb=w("Android")&&!(Qa()||w("Firefox")||Pa()||w("Silk")),wb=Qa(),xb=w("Safari")&&!(Qa()||w("Coast")||Pa()||w("Edge")||w("Silk")||w("Android"))&&!(Ra()||w("iPad")||w("iPod"));/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function yb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var zb=x&&!(9<=ab),Ab=x&&!(8<=ab);function Bb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Cb(a,b){var c=Ab&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Bb(b,a,b.nodeName,c)};function Db(a){this.b=a;this.a=0}function Eb(a){a=a.match(Fb);for(var b=0;b<a.length;b++)Gb.test(a[b])&&a.splice(b,1);return new Db(a)}var Fb=RegExp("\\$?(?:(?![0-9-])[\\w-]+:)?(?![0-9-])[\\w-]+|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Gb=/^\s/;function C(a,b){return a.b[a.a+(b||0)]}function D(a){return a.b[a.a++]}function Hb(a){return a.b.length<=a.a};function E(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(zb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),zb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Ib(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Ab&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Jb(a,b,c,d,e){return(zb?Kb:Lb).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new F)}
function Kb(a,b,c,d,e){if(a instanceof Mb||8==a.g||c&&null===a.g){var f=b.all;if(!f)return e;a=Nb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)Ib(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||G(e,b);return e}Ob(a,b,c,d,e);return e}
function Lb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!x?(b=b.getElementsByName(d),t(b,function(b){a.a(b)&&G(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),t(b,function(b){b.className==d&&a.a(b)&&G(e,b)})):a instanceof H?Ob(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.b()),t(b,function(a){Ib(a,c,d)&&G(e,a)}));return e}
function Pb(a,b,c,d,e){var f;if((a instanceof Mb||8==a.g||c&&null===a.g)&&(f=b.childNodes)){var g=Nb(a);if("*"!=g&&(f=xa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=xa(f,function(a){return Ib(a,c,d)}));t(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||G(e,a)});return e}return Qb(a,b,c,d,e)}function Qb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Ib(b,c,d)&&a.a(b)&&G(e,b);return e}
function Ob(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Ib(b,c,d)&&a.a(b)&&G(e,b),Ob(a,b,c,d,e)}function Nb(a){if(a instanceof H){if(8==a.g)return"!";if(null===a.g)return"*"}return a.b()};function F(){this.b=this.a=null;this.m=0}function Rb(a){this.node=a;this.a=this.b=null}function Sb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f=null,g=0;c&&d;){var f=c.node,h=d.node;f==h||f instanceof Bb&&h instanceof Bb&&f.a==h.a?(f=c,c=c.a,d=d.a):0<jb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.m=g;return a}
F.prototype.unshift=function(a){a=new Rb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.m++};function G(a,b){var c=new Rb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.m++}function Tb(a){return(a=a.a)?a.node:null}F.prototype.f=function(){var a=Tb(this);return a?E(a):""};function Ub(a,b){return new Vb(a,!!b)}function Vb(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function I(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.c?b.b:b.a;return c.node};function J(a){this.j=a;this.b=this.h=!1;this.f=null}function L(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Wb(a,b){a.h=b}function Xb(a,b){a.b=b}function M(a,b){var c=a.a(b);return c instanceof F?+c.f():+c}function N(a,b){var c=a.a(b);return c instanceof F?c.f():""+c}function Yb(a,b){var c=a.a(b);return c instanceof F?!!c.m:!!c};function Zb(a,b,c){J.call(this,a.j);this.c=a;this.i=b;this.v=c;this.h=b.h||c.h;this.b=b.b||c.b;this.c==$b&&(c.b||c.h||4==c.j||0==c.j||!b.f?b.b||b.h||4==b.j||0==b.j||!c.f||(this.f={name:c.f.name,w:b}):this.f={name:b.f.name,w:c})}r(Zb,J);
function ac(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof F&&c instanceof F){e=Ub(b);for(d=I(e);d;d=I(e))for(b=Ub(c),f=I(b);f;f=I(b))if(a(E(d),E(f)))return!0;return!1}if(b instanceof F||c instanceof F){b instanceof F?e=b:(e=c,c=b);e=Ub(e);b=typeof c;for(d=I(e);d;d=I(e)){switch(b){case "number":d=+E(d);break;case "boolean":d=!!E(d);break;case "string":d=E(d);break;default:throw Error("Illegal primitive type for comparison.");}if(a(d,c))return!0}return!1}return e?"boolean"==typeof b||"boolean"==
typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Zb.prototype.a=function(a){return this.c.o(this.i,this.v,a)};Zb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+L(this.i);return a+=L(this.v)};function bc(a,b,c,d){this.a=a;this.M=b;this.j=c;this.o=d}bc.prototype.toString=function(){return this.a};var cc={};
function O(a,b,c,d){if(cc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new bc(a,b,c,d);return cc[a.toString()]=a}O("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});O("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});O("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});O("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});O("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});O("<",4,2,function(a,b,c){return ac(function(a,b){return a<b},a,b,c)});
O(">",4,2,function(a,b,c){return ac(function(a,b){return a>b},a,b,c)});O("<=",4,2,function(a,b,c){return ac(function(a,b){return a<=b},a,b,c)});O(">=",4,2,function(a,b,c){return ac(function(a,b){return a>=b},a,b,c)});var $b=O("=",3,2,function(a,b,c){return ac(function(a,b){return a==b},a,b,c,!0)});O("!=",3,2,function(a,b,c){return ac(function(a,b){return a!=b},a,b,c,!0)});O("and",2,2,function(a,b,c){return Yb(a,c)&&Yb(b,c)});O("or",1,2,function(a,b,c){return Yb(a,c)||Yb(b,c)});function dc(a,b){if(b.a.length&&4!=a.j)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");J.call(this,a.j);this.c=a;this.i=b;this.h=a.h;this.b=a.b}r(dc,J);dc.prototype.a=function(a){a=this.c.a(a);return ec(this.i,a)};dc.prototype.toString=function(){var a;a="Filter:"+L(this.c);return a+=L(this.i)};function fc(a,b){if(b.length<a.L)throw Error("Function "+a.l+" expects at least"+a.L+" arguments, "+b.length+" given");if(null!==a.C&&b.length>a.C)throw Error("Function "+a.l+" expects at most "+a.C+" arguments, "+b.length+" given");a.Y&&t(b,function(b,d){if(4!=b.j)throw Error("Argument "+d+" to function "+a.l+" is not of type Nodeset: "+b);});J.call(this,a.j);this.i=a;this.c=b;Wb(this,a.h||Aa(b,function(a){return a.h}));Xb(this,a.X&&!b.length||a.V&&!!b.length||Aa(b,function(a){return a.b}))}
r(fc,J);fc.prototype.a=function(a){return this.i.o.apply(null,Da(a,this.c))};fc.prototype.toString=function(){var a="Function: "+this.i;if(this.c.length)var b=za(this.c,function(a,b){return a+L(b)},"Arguments:"),a=a+L(b);return a};function gc(a,b,c,d,e,f,g,h,l){this.l=a;this.j=b;this.h=c;this.X=d;this.V=e;this.o=f;this.L=g;this.C=aa(h)?h:g;this.Y=!!l}gc.prototype.toString=function(){return this.l};var hc={};
function P(a,b,c,d,e,f,g,h){if(hc.hasOwnProperty(a))throw Error("Function already created: "+a+".");hc[a]=new gc(a,b,c,d,!1,e,f,g,h)}P("boolean",2,!1,!1,function(a,b){return Yb(b,a)},1);P("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);P("concat",3,!1,!1,function(a,b){return za(Ea(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);P("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);P("count",1,!1,!1,function(a,b){return b.a(a).m},1,1,!0);
P("false",2,!1,!1,function(){return!1},0);P("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);P("id",4,!1,!1,function(a,b){function c(a){if(zb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ca(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=N(b,a).split(/\s+/),f=[];t(d,function(a){a=c(a);!a||0<=wa(f,a)||f.push(a)});f.sort(jb);var g=new F;t(f,function(a){G(g,a)});return g},1);
P("lang",2,!1,!1,function(){return!1},1);P("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);P("local-name",3,!1,!0,function(a,b){var c=b?Tb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);P("name",3,!1,!0,function(a,b){var c=b?Tb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);P("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
P("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);P("not",2,!1,!1,function(a,b){return!Yb(b,a)},1);P("number",1,!1,!0,function(a,b){return b?M(b,a):+E(a.a)},0,1);P("position",1,!0,!1,function(a){return a.b},0);P("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);P("starts-with",2,!1,!1,function(a,b,c){return pa(N(b,a),N(c,a))},2);P("string",3,!1,!0,function(a,b){return b?N(b,a):E(a.a)},0,1);
P("string-length",1,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).length},0,1);P("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);if(Infinity==d)return a.substring(e);b=Math.round(d);return a.substring(e,c+b)},2,3);P("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
P("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);P("sum",1,!1,!1,function(a,b){for(var c=Ub(b.a(a)),d=0,e=I(c);e;e=I(c))d+=+E(e);return d},1,1,!0);P("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);P("true",2,!1,!1,function(){return!0},0);function H(a,b){this.c=a;this.f=aa(b)?b:null;this.g=null;switch(a){case "comment":this.g=8;break;case "text":this.g=3;break;case "processing-instruction":this.g=7;break;case "node":break;default:throw Error("Unexpected argument");}}function ic(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}H.prototype.a=function(a){return null===this.g||this.g==a.nodeType};H.prototype.b=function(){return this.c};
H.prototype.toString=function(){var a="Kind Test: "+this.c;null===this.f||(a+=L(this.f));return a};function jc(a){J.call(this,3);this.c=a.substring(1,a.length-1)}r(jc,J);jc.prototype.a=function(){return this.c};jc.prototype.toString=function(){return"Literal: "+this.c};function Mb(a,b){this.l=a.toLowerCase();this.f=b?b.toLowerCase():"http://www.w3.org/1999/xhtml"}Mb.prototype.a=function(a){var b=a.nodeType;return 1!=b&&2!=b?!1:"*"!=this.l&&this.l!=a.nodeName.toLowerCase()?!1:this.f==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Mb.prototype.b=function(){return this.l};Mb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.f?"":this.f+":")+this.l};function kc(a){J.call(this,1);this.c=a}r(kc,J);kc.prototype.a=function(){return this.c};kc.prototype.toString=function(){return"Number: "+this.c};function lc(a,b){J.call(this,a.j);this.i=a;this.c=b;this.h=a.h;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.B||c.c!=mc||(c=c.v,"*"!=c.b()&&(this.f={name:c.b(),w:null}))}}r(lc,J);function nc(){J.call(this,4)}r(nc,J);nc.prototype.a=function(a){var b=new F;a=a.a;9==a.nodeType?G(b,a):G(b,a.ownerDocument);return b};nc.prototype.toString=function(){return"Root Helper Expression"};function oc(){J.call(this,4)}r(oc,J);oc.prototype.a=function(a){var b=new F;G(b,a.a);return b};oc.prototype.toString=function(){return"Context Helper Expression"};
function pc(a){return"/"==a||"//"==a}lc.prototype.a=function(a){var b=this.i.a(a);if(!(b instanceof F))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.m;c++){var e=a[c],f=Ub(b,e.c.a),g;if(e.h||e.c!=qc)if(e.h||e.c!=rc)for(g=I(f),b=e.a(new yb(g));null!=(g=I(f));)g=e.a(new yb(g)),b=Sb(b,g);else g=I(f),b=e.a(new yb(g));else{for(g=I(f);(b=I(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new yb(g))}}return b};
lc.prototype.toString=function(){var a;a="Path Expression:"+L(this.i);if(this.c.length){var b=za(this.c,function(a,b){return a+L(b)},"Steps:");a+=L(b)}return a};function sc(a,b){this.a=a;this.b=!!b}
function ec(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Ub(b),f=b.m,g,h=0;g=I(e);h++){var l=a.b?f-h:h+1;g=d.a(new yb(g,l,f));if("number"==typeof g)l=l==g;else if("string"==typeof g||"boolean"==typeof g)l=!!g;else if(g instanceof F)l=0<g.m;else throw Error("Predicate.evaluate returned an unexpected type.");if(!l){l=e;g=l.f;var m=l.a;if(!m)throw Error("Next must be called at least once before remove.");var k=m.b,m=m.a;k?k.a=m:g.a=m;m?m.b=k:g.b=k;g.m--;l.a=null}}return b}
sc.prototype.toString=function(){return za(this.a,function(a,b){return a+L(b)},"Predicates:")};function tc(a,b,c,d){J.call(this,4);this.c=a;this.v=b;this.i=c||new sc([]);this.B=!!d;b=this.i;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=zb?a.toLowerCase():a,this.f={name:a,w:b.w});a:{a=this.i;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.h||1==c.j||0==c.j){a=!0;break a}a=!1}this.h=a}r(tc,J);
tc.prototype.a=function(a){var b=a.a,c=null,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.w?N(c.w,a):null,f=1);if(this.B)if(this.h||this.c!=uc)if(a=Ub((new tc(vc,new H("node"))).a(a)),b=I(a))for(c=this.o(b,d,e,f);null!=(b=I(a));)c=Sb(c,this.o(b,d,e,f));else c=new F;else c=Jb(this.v,b,d,e),c=ec(this.i,c,f);else c=this.o(a.a,d,e,f);return c};tc.prototype.o=function(a,b,c,d){a=this.c.f(this.v,a,b,c);return a=ec(this.i,a,d)};
tc.prototype.toString=function(){var a;a="Step:"+L("Operator: "+(this.B?"//":"/"));this.c.l&&(a+=L("Axis: "+this.c));a+=L(this.v);if(this.i.a.length){var b=za(this.i.a,function(a,b){return a+L(b)},"Predicates:");a+=L(b)}return a};function wc(a,b,c,d){this.l=a;this.f=b;this.a=c;this.b=d}wc.prototype.toString=function(){return this.l};var xc={};function Q(a,b,c,d){if(xc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new wc(a,b,c,!!d);return xc[a]=b}
Q("ancestor",function(a,b){for(var c=new F,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);Q("ancestor-or-self",function(a,b){var c=new F,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var mc=Q("attribute",function(a,b){var c=new F,d=a.b();if("style"==d&&b.style&&zb)return G(c,new Bb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof H&&null===a.g||"*"==d)for(var d=0,f;f=e[d];d++)zb?f.nodeValue&&G(c,Cb(b,f)):G(c,f);else(f=e.getNamedItem(d))&&(zb?f.nodeValue&&G(c,Cb(b,f)):G(c,f));return c},!1),uc=Q("child",function(a,b,c,d,e){return(zb?Pb:Qb).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new F)},!1,!0);Q("descendant",Jb,!1,!0);
var vc=Q("descendant-or-self",function(a,b,c,d){var e=new F;Ib(b,c,d)&&a.a(b)&&G(e,b);return Jb(a,b,c,d,e)},!1,!0),qc=Q("following",function(a,b,c,d){var e=new F;do for(var f=b;f=f.nextSibling;)Ib(f,c,d)&&a.a(f)&&G(e,f),e=Jb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new F,d=b;d=d.nextSibling;)a.a(d)&&G(c,d);return c},!1);Q("namespace",function(){return new F},!1);
var yc=Q("parent",function(a,b){var c=new F;if(9==b.nodeType)return c;if(2==b.nodeType)return G(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&G(c,d);return c},!1),rc=Q("preceding",function(a,b,c,d){var e=new F,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var l=[];for(b=f[g];b=b.previousSibling;)l.unshift(b);for(var m=0,k=l.length;m<k;m++)b=l[m],Ib(b,c,d)&&a.a(b)&&G(e,b),e=Jb(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new F,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var zc=Q("self",function(a,b){var c=new F;a.a(b)&&G(c,b);return c},!1);function Ac(a){J.call(this,1);this.c=a;this.h=a.h;this.b=a.b}r(Ac,J);Ac.prototype.a=function(a){return-M(this.c,a)};Ac.prototype.toString=function(){return"Unary Expression: -"+L(this.c)};function Bc(a){J.call(this,4);this.c=a;Wb(this,Aa(this.c,function(a){return a.h}));Xb(this,Aa(this.c,function(a){return a.b}))}r(Bc,J);Bc.prototype.a=function(a){var b=new F;t(this.c,function(c){c=c.a(a);if(!(c instanceof F))throw Error("Path expression must evaluate to NodeSet.");b=Sb(b,c)});return b};Bc.prototype.toString=function(){return za(this.c,function(a,b){return a+L(b)},"Union Expression:")};function Cc(a,b){this.a=a;this.b=b}function Dc(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=Ec(a);var d=D(a.a);if(!d)break;var e=(d=cc[d]||null)&&d.M;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].M;)b=new Zb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Zb(c.pop(),c.pop(),b);return b}function R(a,b){if(Hb(a.a))throw Error(b);}function Fc(a,b){var c=D(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Gc(a){a=D(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Hc(a){a=D(a.a);if(2>a.length)throw Error("Unclosed literal string");return new jc(a)}function Ic(a){var b=D(a.a),c=b.indexOf(":");if(-1==c)return new Mb(b);var d=b.substring(0,c);a=a.b(d);if(!a)throw Error("Namespace prefix not declared: "+d);b=b.substr(c+1);return new Mb(b,a)}
function Jc(a){var b,c=[],d;if(pc(C(a.a))){b=D(a.a);d=C(a.a);if("/"==b&&(Hb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new nc;d=new nc;R(a,"Missing next location step.");b=Kc(a,b);c.push(b)}else{a:{b=C(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":D(a.a);b=Dc(a);R(a,'unclosed "("');Fc(a,")");break;case '"':case "'":b=Hc(a);break;default:if(isNaN(+b))if(!ic(b)&&/(?![0-9])[\w]/.test(d)&&"("==C(a.a,1)){b=D(a.a);
b=hc[b]||null;D(a.a);for(d=[];")"!=C(a.a);){R(a,"Missing function argument list.");d.push(Dc(a));if(","!=C(a.a))break;D(a.a)}R(a,"Unclosed function argument list.");Gc(a);b=new fc(b,d)}else{b=null;break a}else b=new kc(+D(a.a))}"["==C(a.a)&&(d=new sc(Nc(a)),b=new dc(b,d))}if(b)if(pc(C(a.a)))d=b;else return b;else b=Kc(a,"/"),d=new oc,c.push(b)}for(;pc(C(a.a));)b=D(a.a),R(a,"Missing next location step."),b=Kc(a,b),c.push(b);return new lc(d,c)}
function Kc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==C(a.a))return d=new tc(zc,new H("node")),D(a.a),d;if(".."==C(a.a))return d=new tc(yc,new H("node")),D(a.a),d;var f;if("@"==C(a.a))f=mc,D(a.a),R(a,"Missing attribute name");else if("::"==C(a.a,1)){if(!/(?![0-9])[\w]/.test(C(a.a).charAt(0)))throw Error("Bad token: "+D(a.a));c=D(a.a);f=xc[c]||null;if(!f)throw Error("No axis with name: "+c);D(a.a);R(a,"Missing node name")}else f=uc;c=C(a.a);if(/(?![0-9])[\w]/.test(c.charAt(0)))if("("==
C(a.a,1)){if(!ic(c))throw Error("Invalid node type: "+c);c=D(a.a);if(!ic(c))throw Error("Invalid type name: "+c);Fc(a,"(");R(a,"Bad nodetype");e=C(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Hc(a);R(a,"Bad nodetype");Gc(a);c=new H(c,g)}else c=Ic(a);else if("*"==c)c=Ic(a);else throw Error("Bad token: "+D(a.a));e=new sc(Nc(a),f.a);return d||new tc(f,c,e,"//"==b)}
function Nc(a){for(var b=[];"["==C(a.a);){D(a.a);R(a,"Missing predicate expression.");var c=Dc(a);b.push(c);R(a,"Unclosed predicate expression.");Fc(a,"]")}return b}function Ec(a){if("-"==C(a.a))return D(a.a),new Ac(Ec(a));var b=Jc(a);if("|"!=C(a.a))a=b;else{for(b=[b];"|"==D(a.a);)R(a,"Missing next union location path."),b.push(Jc(a));a.a.a--;a=new Bc(b)}return a};function Oc(a){switch(a.nodeType){case 1:return ja(Pc,a);case 9:return Oc(a.documentElement);case 11:case 10:case 6:case 12:return Qc;default:return a.parentNode?Oc(a.parentNode):Qc}}function Qc(){return null}function Pc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Pc(a.parentNode,b):null};function Rc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Eb(a);if(Hb(c))throw Error("Invalid XPath expression.");b?ea(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var d=Dc(new Cc(c,b));if(!Hb(c))throw Error("Bad token: "+D(c));this.evaluate=function(a,b){var c=d.a(new yb(a));return new S(c,b)}}
function S(a,b){if(0==b)if(a instanceof F)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof F))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof F?a.f():""+a;break;case 1:this.numberValue=a instanceof F?+a.f():+a;break;case 3:this.booleanValue=a instanceof F?0<a.m:!!a;break;case 4:case 5:case 6:case 7:var d=
Ub(a);c=[];for(var e=I(d);e;e=I(d))c.push(e instanceof Bb?e.a:e);this.snapshotLength=a.m;this.invalidIteratorState=!1;break;case 8:case 9:d=Tb(a);this.singleNodeValue=d instanceof Bb?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}S.ANY_TYPE=0;S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function Sc(a){this.lookupNamespaceURI=Oc(a)}
function Tc(a){a=a||p;var b=a.document;b.evaluate||(a.XPathResult=S,b.evaluate=function(a,b,e,f){return(new Rc(a,e)).evaluate(b,f)},b.createExpression=function(a,b){return new Rc(a,b)},b.createNSResolver=function(a){return new Sc(a)})}ba("wgxpath.install",Tc);var T={};T.D=function(){var a={La:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
T.o=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(x||vb)&&Tc(gb(d));try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):T.D;if(x&&!Za(7))return d.evaluate.call(d,b,a,e,c,null);if(!x||9<=ab){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var l=g[h],m=l.namespaceURI;if(m&&!f[m]){var k=l.lookupPrefix(m);if(!k){var A=m.match(".*/(\\w+)/?$");A?k=A[1]:k="xhtml"}f[m]=k}}var K={},ma;for(ma in f)K[f[ma]]=ma;e=function(a){return K[a]||null}}try{return d.evaluate(b,
a,e,c,null)}catch(Lc){if("TypeError"===Lc.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):T.D,d.evaluate(b,a,e,c,null);throw Lc;}}catch(Mc){if(!y||"NS_ERROR_ILLEGAL_VALUE"!=Mc.name)throw new u(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Mc);}};T.F=function(a,b){if(!a||1!=a.nodeType)throw new u(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
T.s=function(a,b){var c=function(){var c=T.o(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||T.F(c,a);return c};
T.u=function(a,b){var c=function(){var c=T.o(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();t(c,function(b){T.F(b,a)});return c};function Uc(a){return(a=a.exec(Ma))?a[1]:""}var Vc=function(){if(sb)return Uc(/Firefox\/([0-9.]+)/);if(x||Ta||Sa)return Xa;if(wb)return Uc(/Chrome\/([0-9.]+)/);if(xb&&!(Ra()||w("iPad")||w("iPod")))return Uc(/Version\/([0-9.]+)/);if(tb||ub){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ma))return a[1]+"."+a[2]}else if(vb)return(a=Uc(/Android\s+([0-9.]+)/))?a:Uc(/Version\/([0-9.]+)/);return""}();var Wc={},Xc,Yc;function Zc(a){return $c?Xc(a):x?0<=sa(ab,a):Za(a)}function ad(a){return $c?Yc(a):vb?0<=sa(bd,a):0<=sa(Vc,a)}
var $c=function(){if(!y)return!1;var a=p.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(b){return!1}var c=a.classes,a=a.interfaces,d=c["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),c=c["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=c.platformVersion,f=c.version;Xc=function(a){return 0<=d.compare(e,""+a)};Yc=function(a){return 0<=d.compare(f,""+a)};return!0}(),cd=ub||tb,dd;
if(vb){var ed=/Android\s+([0-9\.]+)/.exec(Ma);dd=ed?ed[1]:"0"}else dd="0";var bd=dd,fd=x&&!(8<=ab),gd=x&&!(9<=ab);vb&&ad(2.3);vb&&ad(4);xb&&ad(6);function hd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}n=hd.prototype;n.clone=function(){return new hd(this.top,this.right,this.bottom,this.left)};n.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};n.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
n.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};n.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};n.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function U(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}n=U.prototype;n.clone=function(){return new U(this.left,this.top,this.width,this.height)};n.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};n.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
n.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};n.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};n.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function id(a){a=a?B(a):document;var b;(b=!x||9<=ab)||(b="CSS1Compat"==z(a).a.compatMode);return b?a.documentElement:a.body};function V(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}function jd(a,b){var c;if(c=fd&&"value"==b&&V(a,"OPTION"))c=null===kd(a,"value");c?(c=[],ob(a,c,!1),c=c.join("")):c=a[b];return c}var ld=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function md(a){var b=[];t(a.split(ld),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function kd(a,b){b=b.toLowerCase();if("style"==b)return md(a.style.cssText);if(fd&&"value"==b&&V(a,"INPUT"))return a.value;if(gd&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}
function nd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return V(a)?a:null}
function W(a,b){var c=ua(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=gd?"styleFloat":"cssFloat";var d;a:{d=c;var e=B(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||od(a,c);if(null===d)d=null;else if(0<=wa(Ga,c)){b:{var f=d.match(Ja);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ka))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Fa[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Ha,"#$1$1$2$2$3$3")),!Ia.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function od(a,b){var c=a.currentStyle||a.style,d=c[b];!aa(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?aa(d)?d:null:(c=nd(a))?od(c,b):null}
function pd(a,b,c){function d(a){var b=qd(a);return 0<b.height&&0<b.width?!0:V(a,"PATH")&&(0<b.height||0<b.width)?(a=W(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=W(a,"overflow")&&Aa(a.childNodes,function(a){return 3==a.nodeType||V(a)&&d(a)})}function e(a){return rd(a)==sd&&Ba(a.childNodes,function(a){return!V(a)||e(a)||!d(a)})}if(!V(a))throw Error("Argument to isShown must be of type Element");if(V(a,"BODY"))return!0;if(V(a,"OPTION")||V(a,"OPTGROUP"))return a=pb(a,function(a){return V(a,"SELECT")}),
!!a&&pd(a,!0,c);var f=td(a);if(f)return!!f.I&&0<f.rect.width&&0<f.rect.height&&pd(f.I,b,c);if(V(a,"INPUT")&&"hidden"==a.type.toLowerCase()||V(a,"NOSCRIPT"))return!1;f=W(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=ud(a))&&d(a)?!e(a):!1}function vd(a){function b(a){if("none"==W(a,"display"))return!1;a=nd(a);return!a||b(a)}return pd(a,!1,b)}var sd="hidden";
function rd(a){function b(a){function b(a){if(a==g)return!0;var d=W(a,"display");return pa(d,"inline")||"absolute"==c&&"static"==W(a,"position")?!1:!0}var c=W(a,"position");if("fixed"==c)return m=!0,a==g?null:g;for(a=nd(a);a&&!b(a);)a=nd(a);return a}function c(a){var b=a;if("visible"==l)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:W(b,"overflow-x"),y:W(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new db(f)).a;
a=fb(b);b=b.parentWindow||b.defaultView;a=x&&Za("10")&&b.pageYOffset!=a.scrollTop?new bb(a.scrollLeft,a.scrollTop):new bb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new bb(a.scrollLeft,a.scrollTop);return a}var e=wd(a),f=B(a),g=f.documentElement,h=f.body,l=W(g,"overflow"),m;for(a=b(a);a;a=b(a)){var k=c(a);if("visible"!=k.x||"visible"!=k.y){var A=qd(a);if(0==A.width||0==A.height)return sd;var K=e.right<A.left,ma=e.bottom<A.top;if(K&&"hidden"==k.x||ma&&"hidden"==k.y)return sd;if(K&&
"visible"!=k.x||ma&&"visible"!=k.y){K=d(a);ma=e.bottom<A.top-K.y;if(e.right<A.left-K.x&&"visible"!=k.x||ma&&"visible"!=k.x)return sd;e=rd(a);return e==sd?sd:"scroll"}K=e.left>=A.left+A.width;A=e.top>=A.top+A.height;if(K&&"hidden"==k.x||A&&"hidden"==k.y)return sd;if(K&&"visible"!=k.x||A&&"visible"!=k.y){if(m&&(k=d(a),e.left>=g.scrollWidth-k.x||e.right>=g.scrollHeight-k.y))return sd;e=rd(a);return e==sd?sd:"scroll"}}}return"none"}
function qd(a){var b=td(a);if(b)return b.rect;if(V(a,"HTML"))return a=B(a),a=(gb(a)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new cb(a.clientWidth,a.clientHeight),new U(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new U(0,0,0,0)}b=new U(c.left,c.top,c.right-c.left,c.bottom-c.top);x&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function td(a){var b=V(a,"MAP");if(!b&&!V(a,"AREA"))return null;var c=b?a:V(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name&&(d=T.s('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=qd(d),!b&&"default"!=a.shape.toLowerCase())){var f=xd(a);a=Math.min(Math.max(f.left,0),e.width);b=Math.min(Math.max(f.top,0),e.height);c=Math.min(f.width,e.width-a);f=Math.min(f.height,e.height-b);e=new U(a+e.left,b+e.top,c,f)}return{I:d,rect:e||new U(0,0,0,0)}}
function xd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new U(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new U(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new U(b,c,d-b,e-c)}return new U(0,0,0,0)}function wd(a){a=qd(a);return new hd(a.top,a.left+a.width,a.top+a.height,a.left)}
function yd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function zd(a){var b=[];Ad(a,b);a=ya(b,yd);return yd(a.join("\n")).replace(/\xa0/g," ")}
function Bd(a,b,c){if(V(a,"BR"))b.push("");else{var d=V(a,"TD"),e=W(a,"display"),f=!d&&!(0<=wa(Cd,e)),g=aa(a.previousElementSibling)?a.previousElementSibling:hb(a.previousSibling),g=g?W(g,"display"):"",h=W(a,"float")||W(a,"cssFloat")||W(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var l=vd(a),m=null,k=null;l&&(m=W(a,"white-space"),k=W(a,"text-transform"));t(a.childNodes,function(a){c(a,b,l,m,k)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||qa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Ad(a,b){Bd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?Dd(a,b,f,g):V(a)&&Ad(a,b)})}var Cd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Dd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";qa(c," ")&&pa(a," ")&&(a=a.substr(1));b.push(c+a)}
function ud(a){if(gd){if("relative"==W(a,"position"))return 1;a=W(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Ed(a)}function Ed(a){var b=1,c=W(a,"opacity");c&&(b=Number(c));(a=nd(a))&&(b*=Ed(a));return b};var Fd=!(x&&!Zc(10)),Gd=vb?!ad(4):!cd,Hd=x&&la.navigator.msPointerEnabled;function X(a,b,c){this.g=a;this.a=b;this.b=c}X.prototype.create=function(a){a=B(a);gd&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.g,this.a,this.b));return a};X.prototype.toString=function(){return this.g};function Y(a,b,c){X.call(this,a,b,c)}r(Y,X);
Y.prototype.create=function(a,b){if(!y&&this==Id)throw new u(9,"Browser does not support a mouse pixel scroll event.");var c=B(a),d;if(gd){d=c.createEventObject();d.altKey=b.altKey;d.ctrlKey=b.ctrlKey;d.metaKey=b.metaKey;d.shiftKey=b.shiftKey;d.button=b.button;d.clientX=b.clientX;d.clientY=b.clientY;c=function(a,b){Object.defineProperty(d,a,{get:function(){return b}})};if(this==Jd||this==Kd)if(Object.defineProperty){var e=this==Jd;c("fromElement",e?a:b.relatedTarget);c("toElement",e?b.relatedTarget:
a)}else d.relatedTarget=b.relatedTarget;this==Ld&&(Object.defineProperty?c("wheelDelta",b.wheelDelta):d.detail=b.wheelDelta)}else{e=gb(c);d=c.createEvent("MouseEvents");var f=1;this==Ld&&(y||(d.wheelDelta=b.wheelDelta),y&&(f=b.wheelDelta/-40));y&&this==Id&&(f=b.wheelDelta);d.initMouseEvent(this.g,this.a,this.b,e,f,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);if(x&&0===d.pageX&&0===d.pageY&&Object.defineProperty){var e=rb(z(a)),c=id(c),g=
b.clientX+e.scrollLeft-c.clientLeft,h=b.clientY+e.scrollTop-c.clientTop;Object.defineProperty(d,"pageX",{get:function(){return g}});Object.defineProperty(d,"pageY",{get:function(){return h}})}}return d};function Md(a,b,c){X.call(this,a,b,c)}r(Md,X);
Md.prototype.create=function(a,b){var c=B(a);if(y){var d=gb(c),e=b.charCode?0:b.keyCode,c=c.createEvent("KeyboardEvent");c.initKeyEvent(this.g,this.a,this.b,d,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,e,b.charCode);this.g==Nd&&b.preventDefault&&c.preventDefault()}else if(gd?c=c.createEventObject():(c=c.createEvent("Events"),c.initEvent(this.g,this.a,this.b)),c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.keyCode=b.charCode||b.keyCode,Ua||Ta)c.charCode=this==Nd?c.keyCode:
0;return c};function Od(a,b,c){X.call(this,a,b,c)}r(Od,X);
Od.prototype.create=function(a,b){function c(b){b=ya(b,function(b){return f.createTouch(g,a,b.identifier,b.pageX,b.pageY,b.screenX,b.screenY)});return f.createTouchList.apply(f,b)}function d(b){var c=ya(b,function(b){return{identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a}});c.item=function(a){return c[a]};return c}function e(a){return Gd?d(a):c(a)}if(!Fd)throw new u(9,"Browser does not support firing touch events.");
var f=B(a),g=gb(f),h=e(b.changedTouches),l=b.touches==b.changedTouches?h:e(b.touches),m=b.targetTouches==b.changedTouches?h:e(b.targetTouches),k;Gd?(k=f.createEvent("MouseEvents"),k.initMouseEvent(this.g,this.a,this.b,g,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=l,k.targetTouches=m,k.changedTouches=h,k.scale=b.scale,k.rotation=b.rotation):(k=f.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(l,m,h,this.g,g,0,0,b.clientX,b.clientY,
b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.g,this.a,this.b,g,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,l,m,h,b.scale,b.rotation),k.relatedTarget=b.relatedTarget);return k};function Pd(a,b,c){X.call(this,a,b,c)}r(Pd,X);
Pd.prototype.create=function(a,b){if(!Hd)throw new u(9,"Browser does not support MSGesture events.");var c=B(a),d=gb(c),c=c.createEvent("MSGestureEvent");c.initGestureEvent(this.g,this.a,this.b,d,1,0,0,b.clientX,b.clientY,0,0,b.translationX,b.translationY,b.scale,b.expansion,b.rotation,b.velocityX,b.velocityY,b.velocityExpansion,b.velocityAngular,(new Date).getTime(),b.relatedTarget);return c};function Qd(a,b,c){X.call(this,a,b,c)}r(Qd,X);
Qd.prototype.create=function(a,b){if(!Hd)throw new u(9,"Browser does not support MSPointer events.");var c=B(a),d=gb(c),c=c.createEvent("MSPointerEvent");c.initPointerEvent(this.g,this.a,this.b,d,0,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget,0,0,b.width,b.height,b.pressure,b.rotation,b.tiltX,b.tiltY,b.pointerId,b.pointerType,0,b.isPrimary);return c};
var Jd=new Y("mouseout",!0,!0),Kd=new Y("mouseover",!0,!0),Ld=new Y(y?"DOMMouseScroll":"mousewheel",!0,!0),Id=new Y("MozMousePixelScroll",!0,!0),Nd=new Md("keypress",!0,!0),Rd={f:new X("blur",!1,!1),c:new X("change",!0,!1),Ma:new X("focus",!1,!1),$:new X("focusin",!0,!1),aa:new X("focusout",!0,!1),ba:new X("input",!0,!1),Ba:new X("orientationchange",!1,!1),Ca:new X("propertychange",!1,!1),Da:new X("select",!0,!1),Ea:new X("submit",!0,!0),Fa:new X("textInput",!0,!0),i:new Y("click",!0,!0),v:new Y("contextmenu",
!0,!0),B:new Y("dblclick",!0,!0),fa:new Y("mousedown",!0,!0),ga:new Y("mousemove",!0,!1),ia:Jd,ja:Kd,la:new Y("mouseup",!0,!0),ma:Ld,ka:Id,ca:new Md("keydown",!0,!0),da:Nd,ea:new Md("keyup",!0,!0),Ga:new Od("touchend",!0,!0),Ha:new Od("touchmove",!0,!0),Ia:new Od("touchstart",!0,!0),na:new Pd("MSGestureChange",!0,!0),oa:new Pd("MSGestureEnd",!0,!0),pa:new Pd("MSGestureHold",!0,!0),qa:new Pd("MSGestureStart",!0,!0),ra:new Pd("MSGestureTap",!0,!0),ta:new Pd("MSInertiaStart",!0,!0),sa:new Qd("MSGotPointerCapture",
!0,!1),ua:new Qd("MSLostPointerCapture",!0,!1),va:new Qd("MSPointerCancel",!0,!0),wa:new Qd("MSPointerDown",!0,!0),xa:new Qd("MSPointerMove",!0,!0),ya:new Qd("MSPointerOver",!0,!0),Z:new Qd("MSPointerOut",!0,!0),za:new Qd("MSPointerUp",!0,!0)};function Sd(a){na.call(this,a)}r(Sd,na);Ua||y&&Zc(3.5)||x&&Zc(8);var Td={A:function(a){return!(!a.querySelectorAll||!a.querySelector)},s:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,"Compound class names not permitted");if(Td.A(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new u(32,"An invalid or illegal class name was specified");}var d=qb(z(b),"*",a,b);return d.length?d[0]:null},u:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,
"Compound class names not permitted");if(Td.A(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new u(32,"An invalid or illegal class name was specified");}return qb(z(b),"*",a,b)}};var Ud={s:function(a,b){if(!ea(b.querySelector)&&x&&Zc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);var c;try{c=b.querySelector(a)}catch(d){throw new u(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},u:function(a,b){if(!ea(b.querySelectorAll)&&x&&Zc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);try{return b.querySelectorAll(a)}catch(c){throw new u(32,
"An invalid or illegal selector was specified");}}};var Vd={A:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},s:function(a,b){var c=z(b),d=q(a)?c.a.getElementById(a):a;if(!d)return null;if(kd(d,"id")==a&&ib(b,d))return d;c=qb(c,"*");return Ca(c,function(c){return kd(c,"id")==a&&ib(b,c)})},u:function(a,b){if(!a)return[];if(Vd.A(b,a))try{return b.querySelectorAll("#"+Vd.S(a))}catch(c){return[]}var d=qb(z(b),"*",null,b);return xa(d,function(b){return kd(b,"id")==a})},S:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Wd={},Xd={};Wd.N=function(a,b,c){var d;try{d=Ud.u("a",b)}catch(e){d=qb(z(b),"A",null,b)}return Ca(d,function(b){b=zd(b);return c&&-1!=b.indexOf(a)||b==a})};Wd.J=function(a,b,c){var d;try{d=Ud.u("a",b)}catch(e){d=qb(z(b),"A",null,b)}return xa(d,function(b){b=zd(b);return c&&-1!=b.indexOf(a)||b==a})};Wd.s=function(a,b){return Wd.N(a,b,!1)};Wd.u=function(a,b){return Wd.J(a,b,!1)};Xd.s=function(a,b){return Wd.N(a,b,!0)};Xd.u=function(a,b){return Wd.J(a,b,!0)};var Yd={s:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},u:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Zd={className:Td,"class name":Td,css:Ud,"css selector":Ud,id:Vd,linkText:Wd,"link text":Wd,name:{s:function(a,b){var c=qb(z(b),"*",null,b);return Ca(c,function(b){return kd(b,"name")==a})},u:function(a,b){var c=qb(z(b),"*",null,b);return xa(c,function(b){return kd(b,"name")==a})}},partialLinkText:Xd,"partial link text":Xd,tagName:Yd,"tag name":Yd,xpath:T};
function $d(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Zd[c];if(d&&ea(d.s))return d.s(a[c],b||la.document)}throw Error("Unsupported locator strategy: "+c);};var ae={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Sd("Illegal Index: "+a);if(b.length<=c)throw new Sd("Index out of range: "+a);return[b[c]]},name:function(a,b){return xa(b,function(b){return jd(b,"name")==a})},value:function(a,b){return xa(b,function(b){return jd(b,"value")===a})}};function be(a,b){return(new RegExp(a)).test(b)}function ce(a,b){return(new RegExp(a,"i")).test(b)}function de(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var ee={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+de(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(de(a))).test(b)},regex:be,regexi:ce,regexpi:ce,regexp:be};function fe(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=fe(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Wc.ha&&ad(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={U:function(a,b){return pa(a,"//")?Z.O(a,b):pa(a,"document.")?Z.G(a,b):Z.H(a,b)},P:function(a,b){return ge(b||B(la),function(b){return b.alt==a})},R:function(a,b){return ge(b||B(la),function(b){return b.className==a})},G:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},T:function(a,b){return $d({id:a},b)},H:function(a,b){return Z.id(a,b)||Z.name(a,b)},l:function(a,b){var c=b||B(la);z(c);var d;d=eb(document,"*",null,c);c=a.split(" ");for(c[0]="name="+c[0];c.length;){var e=
c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=ae[d];if(!g)throw new Sd("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},W:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,h=g.$wdc_;h||(h=g.$wdc_={},h.K=ka());h.K||(h.K=ka());f=h;if(!(null!==f&&d in f))throw new u(10,"Element does not exist in cache");var l=f[d];if(null!==l&&"setInterval"in l){if(l.closed)throw delete f[d],new u(23,
"Window has been closed.");c=l}else{for(g=l;g;){if(g==e.documentElement){c=l;break a}g=g.parentNode}delete f[d];throw new u(10,"Element is no longer attached to the DOM");}}return c}catch(m){return null}},O:function(a,b){var c=qa(a,"/"),d={xpath:a};try{var e=$d(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return $d(d,b)}};Z.alt=Z.P;Z["class"]=Z.R;Z.dom=Z.G;Z.id=Z.T;Z.identifier=Z.H;Z.implicit=Z.U;
Z.link=function(a,b){for(var c=(b||B(la)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";y&&"1.8"<=Xa||Ua||x?g=fe(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Ua)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");var g=f,f=ra(g),h=a,g="glob",l=/^([a-zA-Z-]+):(.*)/.exec(h);if(l){var m=l[1],l=l[2];ee[m.toLowerCase()]&&(g=
m.toLowerCase(),h=l)}m=ee[g];if(!m)throw new Sd("Cannot find pattern matching strategy: "+g);"glob"==g?(0==h.indexOf("glob:")&&(h=h.substring(5)),m=ee.glob):"exact"==g&&0==h.indexOf("exact:")&&(h=h.substring(6));h=ja(m,h);h.Ja=g;if(h(f))return e}return null};Z.name=Z.l;Z.stored=Z.W;Z.xpath=Z.O;function he(a,b,c,d){var e=Z[a];if(!e)throw new Sd("Unrecognised locator type: '"+a+"'");c=e.call(null,b,c);if(null!=c)return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=he(a,b,f,d.frames[e]),null!=c))return c}return null}function ge(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType){if(b(e))return e;if(e=ge(e,b))return e}}return null};function ie(a){var b="";a&&(b=a.toUpperCase());return(b=Rd[b])?b:{create:function(b){b=B(b);gd&&b.createEventObject?b=b.createEventObject():(b=b.createEvent("HTMLEvents"),b.initEvent(a,!0,!0));return b},g:a}};ba("_",function(a,b){var c;if(q(a)){var d;(d=a.match(/^([A-Za-z]+)=.+/))?(d=d[1].toLowerCase(),d={type:d,string:a.substring(d.length+1)}):(d={string:"",type:""},d.string=a,d.type=pa(a,"//")?"xpath":pa(a,"document.")?"dom":"identifier");c=la||la;d=he(d.type,d.string,c.document,c);if(null==d)throw new Sd("Element "+a+" not found");c=d}else c=a;d=ie(b);if(!d)throw Error("Unable to find type for: "+b);var e=d.create(c,void 0);"isTrusted"in e||(e.isTrusted=!1);gd&&c.fireEvent?c.fireEvent("on"+d.g,e):c.dispatchEvent(e)});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
