function(){return function(){var l=this;function aa(a){return void 0!==a}function ba(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&aa(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"string"==typeof a}function da(a){return"function"==ca(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){ia=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.aa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Z=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var la=window;function ma(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(ma,Error);ma.prototype.name="CustomError";var na;function oa(a,b){return 0==a.lastIndexOf(b,0)}function pa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ra(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var x=m.exec(h)||["","",""],G=n.exec(k)||["","",""];if(0==x[0].length&&0==G[0].length)break;c=sa(0==x[1].length?0:parseInt(x[1],10),0==G[1].length?0:parseInt(G[1],10))||sa(0==x[2].length,0==G[2].length)||sa(x[2],G[2])}while(0==c)}return c}function sa(a,b){return a<b?-1:a>b?1:0}
function ta(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var ua=Array.prototype;function va(a,b){if(p(a))return p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function r(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function wa(a,b){for(var c=a.length,d=[],e=0,f=p(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}function xa(a,b,c){var d=c;r(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function ya(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function za(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Aa(a,b){var c;a:{c=a.length;for(var d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:p(a)?a.charAt(c):a[c]}function Ba(a){return ua.concat.apply(ua,arguments)}
function Ca(a,b,c){return 2>=arguments.length?ua.slice.call(a,b):ua.slice.call(a,b,c)};var Da={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ea="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Fa=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ga=/^#(?:[0-9a-f]{3}){1,2}$/i,Ha=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ia=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function t(a,b){this.code=a;this.a=u[a]||Ja;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}q(t,Error);var Ja="unknown error",u={15:"element not selectable",11:"element not visible"};u[31]=Ja;u[30]=Ja;u[24]="invalid cookie domain";u[29]="invalid element coordinates";u[12]="invalid element state";
u[32]="invalid selector";u[51]="invalid selector";u[52]="invalid selector";u[17]="javascript error";u[405]="unsupported operation";u[34]="move target out of bounds";u[27]="no such alert";u[7]="no such element";u[8]="no such frame";u[23]="no such window";u[28]="script timeout";u[33]="session not created";u[10]="stale element reference";u[21]="timeout";u[25]="unable to set cookie";u[26]="unexpected alert open";u[13]=Ja;u[9]="unknown command";t.prototype.toString=function(){return this.name+": "+this.message};var v;a:{var Ka=l.navigator;if(Ka){var La=Ka.userAgent;if(La){v=La;break a}}v=""}function w(a){return-1!=v.indexOf(a)};function Ma(){return w("Opera")||w("OPR")}function Na(){return(w("Chrome")||w("CriOS"))&&!Ma()&&!w("Edge")};function Oa(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var Pa=Ma(),y=w("Trident")||w("MSIE"),Qa=w("Edge"),Ra=w("Gecko")&&!(-1!=v.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Sa=-1!=v.toLowerCase().indexOf("webkit")&&!w("Edge");function Ta(){var a=v;if(Ra)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Qa)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Sa)return/WebKit\/(\S+)/.exec(a)}function Ua(){var a=l.document;return a?a.documentMode:void 0}
var Va=function(){if(Pa&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ta())&&(a=b?b[1]:"");return y&&(b=Ua(),b>parseFloat(a))?String(b):a}(),Wa={};function Xa(a){return Wa[a]||(Wa[a]=0<=ra(Va,a))}var Ya=l.document,Za=Ya&&y?Ua()||("CSS1Compat"==Ya.compatMode?parseInt(Va,10):5):void 0;!Ra&&!y||y&&9<=Za||Ra&&Xa("1.9.1");y&&Xa("9");function z(a,b){this.x=aa(a)?a:0;this.y=aa(b)?b:0}z.prototype.clone=function(){return new z(this.x,this.y)};z.prototype.toString=function(){return"("+this.x+", "+this.y+")"};z.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};z.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};z.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function $a(a,b){this.width=a;this.height=b}$a.prototype.clone=function(){return new $a(this.width,this.height)};$a.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};$a.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};$a.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
$a.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function A(a){return a?new ab(B(a)):na||(na=new ab)}
function bb(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=va(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;return a}return b}
function cb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function db(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function eb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=Za)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?fb(a,b):!c&&db(e,b)?-1*gb(a,b):!d&&db(f,a)?gb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,d)}function gb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return fb(d,a)}function fb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var hb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ib={IMG:" ",BR:"\n"};
function jb(a,b,c){if(!(a.nodeName in hb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ib)b.push(ib[a.nodeName]);else for(a=a.firstChild;a;)jb(a,b,c),a=a.nextSibling}function kb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function ab(a){this.a=a||l.document||document}function lb(a,b,c,d){return bb(a.a,b,c,d)};var mb=w("Firefox"),nb=Oa()||w("iPod"),ob=w("iPad"),pb=w("Android")&&!(Na()||w("Firefox")||Ma()||w("Silk")),qb=Na(),rb=w("Safari")&&!(Na()||w("Coast")||Ma()||w("Edge")||w("Silk")||w("Android"))&&!(Oa()||w("iPad")||w("iPod"));/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function sb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var tb=y&&!(9<=Za),ub=y&&!(8<=Za);function vb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function wb(a,b){var c=ub&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new vb(b,a,b.nodeName,c)};function xb(a){this.b=a;this.a=0}function yb(a){a=a.match(zb);for(var b=0;b<a.length;b++)Ab.test(a[b])&&a.splice(b,1);return new xb(a)}var zb=RegExp("\\$?(?:(?![0-9-])[\\w-]+:)?(?![0-9-])[\\w-]+|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Ab=/^\s/;function C(a,b){return a.b[a.a+(b||0)]}function D(a){return a.b[a.a++]}function Bb(a){return a.b.length<=a.a};function E(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(tb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),tb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Cb(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}ub&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Db(a,b,c,d,e){return(tb?Eb:Fb).call(null,a,b,p(c)?c:null,p(d)?d:null,e||new F)}
function Eb(a,b,c,d,e){if(a instanceof Gb||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=Hb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)Cb(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||H(e,b);return e}Ib(a,b,c,d,e);return e}
function Fb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!y?(b=b.getElementsByName(d),r(b,function(b){a.a(b)&&H(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),r(b,function(b){b.className==d&&a.a(b)&&H(e,b)})):a instanceof I?Ib(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),r(b,function(a){Cb(a,c,d)&&H(e,a)}));return e}
function Jb(a,b,c,d,e){var f;if((a instanceof Gb||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Hb(a);if("*"!=g&&(f=wa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=wa(f,function(a){return Cb(a,c,d)}));r(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||H(e,a)});return e}return Kb(a,b,c,d,e)}function Kb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Cb(b,c,d)&&a.a(b)&&H(e,b);return e}
function Ib(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Cb(b,c,d)&&a.a(b)&&H(e,b),Ib(a,b,c,d,e)}function Hb(a){if(a instanceof I){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function F(){this.b=this.a=null;this.l=0}function Lb(a){this.node=a;this.a=this.b=null}function Mb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f=null,g=0;c&&d;){var f=c.node,h=d.node;f==h||f instanceof vb&&h instanceof vb&&f.a==h.a?(f=c,c=c.a,d=d.a):0<eb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.l=g;return a}
F.prototype.unshift=function(a){a=new Lb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.l++};function H(a,b){var c=new Lb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.l++}function Nb(a){return(a=a.a)?a.node:null}F.prototype.f=function(){var a=Nb(this);return a?E(a):""};function Ob(a,b){return new Pb(a,!!b)}function Pb(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.c?b.b:b.a;return c.node};function K(a){this.i=a;this.b=this.g=!1;this.f=null}function L(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Qb(a,b){a.g=b}function Rb(a,b){a.b=b}function M(a,b){var c=a.a(b);return c instanceof F?+c.f():+c}function N(a,b){var c=a.a(b);return c instanceof F?c.f():""+c}function Sb(a,b){var c=a.a(b);return c instanceof F?!!c.l:!!c};function Tb(a,b,c){K.call(this,a.i);this.c=a;this.h=b;this.u=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==Ub&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,v:b}):this.f={name:b.f.name,v:c})}q(Tb,K);
function Vb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof F&&c instanceof F){e=Ob(b);for(d=J(e);d;d=J(e))for(b=Ob(c),f=J(b);f;f=J(b))if(a(E(d),E(f)))return!0;return!1}if(b instanceof F||c instanceof F){b instanceof F?e=b:(e=c,c=b);e=Ob(e);b=typeof c;for(d=J(e);d;d=J(e)){switch(b){case "number":d=+E(d);break;case "boolean":d=!!E(d);break;case "string":d=E(d);break;default:throw Error("Illegal primitive type for comparison.");}if(a(d,c))return!0}return!1}return e?"boolean"==typeof b||"boolean"==
typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Tb.prototype.a=function(a){return this.c.m(this.h,this.u,a)};Tb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+L(this.h);return a+=L(this.u)};function Wb(a,b,c,d){this.a=a;this.L=b;this.i=c;this.m=d}Wb.prototype.toString=function(){return this.a};var Xb={};
function O(a,b,c,d){if(Xb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Wb(a,b,c,d);return Xb[a.toString()]=a}O("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});O("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});O("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});O("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});O("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});O("<",4,2,function(a,b,c){return Vb(function(a,b){return a<b},a,b,c)});
O(">",4,2,function(a,b,c){return Vb(function(a,b){return a>b},a,b,c)});O("<=",4,2,function(a,b,c){return Vb(function(a,b){return a<=b},a,b,c)});O(">=",4,2,function(a,b,c){return Vb(function(a,b){return a>=b},a,b,c)});var Ub=O("=",3,2,function(a,b,c){return Vb(function(a,b){return a==b},a,b,c,!0)});O("!=",3,2,function(a,b,c){return Vb(function(a,b){return a!=b},a,b,c,!0)});O("and",2,2,function(a,b,c){return Sb(a,c)&&Sb(b,c)});O("or",1,2,function(a,b,c){return Sb(a,c)||Sb(b,c)});function Yb(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");K.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}q(Yb,K);Yb.prototype.a=function(a){a=this.c.a(a);return Zb(this.h,a)};Yb.prototype.toString=function(){var a;a="Filter:"+L(this.c);return a+=L(this.h)};function $b(a,b){if(b.length<a.K)throw Error("Function "+a.j+" expects at least"+a.K+" arguments, "+b.length+" given");if(null!==a.B&&b.length>a.B)throw Error("Function "+a.j+" expects at most "+a.B+" arguments, "+b.length+" given");a.X&&r(b,function(b,d){if(4!=b.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});K.call(this,a.i);this.h=a;this.c=b;Qb(this,a.g||ya(b,function(a){return a.g}));Rb(this,a.W&&!b.length||a.U&&!!b.length||ya(b,function(a){return a.b}))}
q($b,K);$b.prototype.a=function(a){return this.h.m.apply(null,Ba(a,this.c))};$b.prototype.toString=function(){var a="Function: "+this.h;if(this.c.length)var b=xa(this.c,function(a,b){return a+L(b)},"Arguments:"),a=a+L(b);return a};function ac(a,b,c,d,e,f,g,h,k){this.j=a;this.i=b;this.g=c;this.W=d;this.U=e;this.m=f;this.K=g;this.B=aa(h)?h:g;this.X=!!k}ac.prototype.toString=function(){return this.j};var bc={};
function P(a,b,c,d,e,f,g,h){if(bc.hasOwnProperty(a))throw Error("Function already created: "+a+".");bc[a]=new ac(a,b,c,d,!1,e,f,g,h)}P("boolean",2,!1,!1,function(a,b){return Sb(b,a)},1);P("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);P("concat",3,!1,!1,function(a,b){return xa(Ca(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);P("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);P("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
P("false",2,!1,!1,function(){return!1},0);P("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);P("id",4,!1,!1,function(a,b){function c(a){if(tb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Aa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=N(b,a).split(/\s+/),f=[];r(d,function(a){a=c(a);!a||0<=va(f,a)||f.push(a)});f.sort(eb);var g=new F;r(f,function(a){H(g,a)});return g},1);
P("lang",2,!1,!1,function(){return!1},1);P("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);P("local-name",3,!1,!0,function(a,b){var c=b?Nb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);P("name",3,!1,!0,function(a,b){var c=b?Nb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);P("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
P("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);P("not",2,!1,!1,function(a,b){return!Sb(b,a)},1);P("number",1,!1,!0,function(a,b){return b?M(b,a):+E(a.a)},0,1);P("position",1,!0,!1,function(a){return a.b},0);P("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);P("starts-with",2,!1,!1,function(a,b,c){return oa(N(b,a),N(c,a))},2);P("string",3,!1,!0,function(a,b){return b?N(b,a):E(a.a)},0,1);
P("string-length",1,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).length},0,1);P("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);if(Infinity==d)return a.substring(e);b=Math.round(d);return a.substring(e,c+b)},2,3);P("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
P("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);P("sum",1,!1,!1,function(a,b){for(var c=Ob(b.a(a)),d=0,e=J(c);e;e=J(c))d+=+E(e);return d},1,1,!0);P("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);P("true",2,!1,!1,function(){return!0},0);function I(a,b){this.h=a;this.c=aa(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function cc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}I.prototype.a=function(a){return null===this.b||this.b==a.nodeType};I.prototype.f=function(){return this.h};
I.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=L(this.c));return a};function dc(a){K.call(this,3);this.c=a.substring(1,a.length-1)}q(dc,K);dc.prototype.a=function(){return this.c};dc.prototype.toString=function(){return"Literal: "+this.c};function Gb(a,b){this.j=a.toLowerCase();this.c=b?b.toLowerCase():"http://www.w3.org/1999/xhtml"}Gb.prototype.a=function(a){var b=a.nodeType;return 1!=b&&2!=b?!1:"*"!=this.j&&this.j!=a.nodeName.toLowerCase()?!1:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Gb.prototype.f=function(){return this.j};Gb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.j};function ec(a){K.call(this,1);this.c=a}q(ec,K);ec.prototype.a=function(){return this.c};ec.prototype.toString=function(){return"Number: "+this.c};function fc(a,b){K.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.A||c.c!=gc||(c=c.u,"*"!=c.f()&&(this.f={name:c.f(),v:null}))}}q(fc,K);function hc(){K.call(this,4)}q(hc,K);hc.prototype.a=function(a){var b=new F;a=a.a;9==a.nodeType?H(b,a):H(b,a.ownerDocument);return b};hc.prototype.toString=function(){return"Root Helper Expression"};function ic(){K.call(this,4)}q(ic,K);ic.prototype.a=function(a){var b=new F;H(b,a.a);return b};ic.prototype.toString=function(){return"Context Helper Expression"};
function jc(a){return"/"==a||"//"==a}fc.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof F))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=Ob(b,e.c.a),g;if(e.g||e.c!=kc)if(e.g||e.c!=lc)for(g=J(f),b=e.a(new sb(g));null!=(g=J(f));)g=e.a(new sb(g)),b=Mb(b,g);else g=J(f),b=e.a(new sb(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new sb(g))}}return b};
fc.prototype.toString=function(){var a;a="Path Expression:"+L(this.h);if(this.c.length){var b=xa(this.c,function(a,b){return a+L(b)},"Steps:");a+=L(b)}return a};function mc(a,b){this.a=a;this.b=!!b}
function Zb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Ob(b),f=b.l,g,h=0;g=J(e);h++){var k=a.b?f-h:h+1;g=d.a(new sb(g,k,f));if("number"==typeof g)k=k==g;else if("string"==typeof g||"boolean"==typeof g)k=!!g;else if(g instanceof F)k=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;g=k.f;var m=k.a;if(!m)throw Error("Next must be called at least once before remove.");var n=m.b,m=m.a;n?n.a=m:g.a=m;m?m.b=n:g.b=n;g.l--;k.a=null}}return b}
mc.prototype.toString=function(){return xa(this.a,function(a,b){return a+L(b)},"Predicates:")};function nc(a,b,c,d){K.call(this,4);this.c=a;this.u=b;this.h=c||new mc([]);this.A=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=tb?a.toLowerCase():a,this.f={name:a,v:b.v});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}q(nc,K);
nc.prototype.a=function(a){var b=a.a,c=null,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.v?N(c.v,a):null,f=1);if(this.A)if(this.g||this.c!=oc)if(a=Ob((new nc(pc,new I("node"))).a(a)),b=J(a))for(c=this.m(b,d,e,f);null!=(b=J(a));)c=Mb(c,this.m(b,d,e,f));else c=new F;else c=Db(this.u,b,d,e),c=Zb(this.h,c,f);else c=this.m(a.a,d,e,f);return c};nc.prototype.m=function(a,b,c,d){a=this.c.f(this.u,a,b,c);return a=Zb(this.h,a,d)};
nc.prototype.toString=function(){var a;a="Step:"+L("Operator: "+(this.A?"//":"/"));this.c.j&&(a+=L("Axis: "+this.c));a+=L(this.u);if(this.h.a.length){var b=xa(this.h.a,function(a,b){return a+L(b)},"Predicates:");a+=L(b)}return a};function qc(a,b,c,d){this.j=a;this.f=b;this.a=c;this.b=d}qc.prototype.toString=function(){return this.j};var rc={};function Q(a,b,c,d){if(rc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new qc(a,b,c,!!d);return rc[a]=b}
Q("ancestor",function(a,b){for(var c=new F,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);Q("ancestor-or-self",function(a,b){var c=new F,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var gc=Q("attribute",function(a,b){var c=new F,d=a.f();if("style"==d&&b.style&&tb)return H(c,new vb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof I&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)tb?f.nodeValue&&H(c,wb(b,f)):H(c,f);else(f=e.getNamedItem(d))&&(tb?f.nodeValue&&H(c,wb(b,f)):H(c,f));return c},!1),oc=Q("child",function(a,b,c,d,e){return(tb?Jb:Kb).call(null,a,b,p(c)?c:null,p(d)?d:null,e||new F)},!1,!0);Q("descendant",Db,!1,!0);
var pc=Q("descendant-or-self",function(a,b,c,d){var e=new F;Cb(b,c,d)&&a.a(b)&&H(e,b);return Db(a,b,c,d,e)},!1,!0),kc=Q("following",function(a,b,c,d){var e=new F;do for(var f=b;f=f.nextSibling;)Cb(f,c,d)&&a.a(f)&&H(e,f),e=Db(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new F,d=b;d=d.nextSibling;)a.a(d)&&H(c,d);return c},!1);Q("namespace",function(){return new F},!1);
var sc=Q("parent",function(a,b){var c=new F;if(9==b.nodeType)return c;if(2==b.nodeType)return H(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&H(c,d);return c},!1),lc=Q("preceding",function(a,b,c,d){var e=new F,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var k=[];for(b=f[g];b=b.previousSibling;)k.unshift(b);for(var m=0,n=k.length;m<n;m++)b=k[m],Cb(b,c,d)&&a.a(b)&&H(e,b),e=Db(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new F,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var tc=Q("self",function(a,b){var c=new F;a.a(b)&&H(c,b);return c},!1);function wc(a){K.call(this,1);this.c=a;this.g=a.g;this.b=a.b}q(wc,K);wc.prototype.a=function(a){return-M(this.c,a)};wc.prototype.toString=function(){return"Unary Expression: -"+L(this.c)};function xc(a){K.call(this,4);this.c=a;Qb(this,ya(this.c,function(a){return a.g}));Rb(this,ya(this.c,function(a){return a.b}))}q(xc,K);xc.prototype.a=function(a){var b=new F;r(this.c,function(c){c=c.a(a);if(!(c instanceof F))throw Error("Path expression must evaluate to NodeSet.");b=Mb(b,c)});return b};xc.prototype.toString=function(){return xa(this.c,function(a,b){return a+L(b)},"Union Expression:")};function yc(a,b){this.a=a;this.b=b}function zc(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=Ac(a);var d=D(a.a);if(!d)break;var e=(d=Xb[d]||null)&&d.L;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].L;)b=new Tb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Tb(c.pop(),c.pop(),b);return b}function R(a,b){if(Bb(a.a))throw Error(b);}function Bc(a,b){var c=D(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Cc(a){a=D(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Dc(a){a=D(a.a);if(2>a.length)throw Error("Unclosed literal string");return new dc(a)}function Ec(a){var b=D(a.a),c=b.indexOf(":");if(-1==c)return new Gb(b);var d=b.substring(0,c);a=a.b(d);if(!a)throw Error("Namespace prefix not declared: "+d);b=b.substr(c+1);return new Gb(b,a)}
function Fc(a){var b,c=[],d;if(jc(C(a.a))){b=D(a.a);d=C(a.a);if("/"==b&&(Bb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new hc;d=new hc;R(a,"Missing next location step.");b=Gc(a,b);c.push(b)}else{a:{b=C(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":D(a.a);b=zc(a);R(a,'unclosed "("');Bc(a,")");break;case '"':case "'":b=Dc(a);break;default:if(isNaN(+b))if(!cc(b)&&/(?![0-9])[\w]/.test(d)&&"("==C(a.a,1)){b=D(a.a);
b=bc[b]||null;D(a.a);for(d=[];")"!=C(a.a);){R(a,"Missing function argument list.");d.push(zc(a));if(","!=C(a.a))break;D(a.a)}R(a,"Unclosed function argument list.");Cc(a);b=new $b(b,d)}else{b=null;break a}else b=new ec(+D(a.a))}"["==C(a.a)&&(d=new mc(Hc(a)),b=new Yb(b,d))}if(b)if(jc(C(a.a)))d=b;else return b;else b=Gc(a,"/"),d=new ic,c.push(b)}for(;jc(C(a.a));)b=D(a.a),R(a,"Missing next location step."),b=Gc(a,b),c.push(b);return new fc(d,c)}
function Gc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==C(a.a))return d=new nc(tc,new I("node")),D(a.a),d;if(".."==C(a.a))return d=new nc(sc,new I("node")),D(a.a),d;var f;if("@"==C(a.a))f=gc,D(a.a),R(a,"Missing attribute name");else if("::"==C(a.a,1)){if(!/(?![0-9])[\w]/.test(C(a.a).charAt(0)))throw Error("Bad token: "+D(a.a));c=D(a.a);f=rc[c]||null;if(!f)throw Error("No axis with name: "+c);D(a.a);R(a,"Missing node name")}else f=oc;c=C(a.a);if(/(?![0-9])[\w]/.test(c.charAt(0)))if("("==
C(a.a,1)){if(!cc(c))throw Error("Invalid node type: "+c);c=D(a.a);if(!cc(c))throw Error("Invalid type name: "+c);Bc(a,"(");R(a,"Bad nodetype");e=C(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Dc(a);R(a,"Bad nodetype");Cc(a);c=new I(c,g)}else c=Ec(a);else if("*"==c)c=Ec(a);else throw Error("Bad token: "+D(a.a));e=new mc(Hc(a),f.a);return d||new nc(f,c,e,"//"==b)}
function Hc(a){for(var b=[];"["==C(a.a);){D(a.a);R(a,"Missing predicate expression.");var c=zc(a);b.push(c);R(a,"Unclosed predicate expression.");Bc(a,"]")}return b}function Ac(a){if("-"==C(a.a))return D(a.a),new wc(Ac(a));var b=Fc(a);if("|"!=C(a.a))a=b;else{for(b=[b];"|"==D(a.a);)R(a,"Missing next union location path."),b.push(Fc(a));a.a.a--;a=new xc(b)}return a};function Ic(a){switch(a.nodeType){case 1:return ja(Jc,a);case 9:return Ic(a.documentElement);case 11:case 10:case 6:case 12:return Kc;default:return a.parentNode?Ic(a.parentNode):Kc}}function Kc(){return null}function Jc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Jc(a.parentNode,b):null};function Lc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=yb(a);if(Bb(c))throw Error("Invalid XPath expression.");b?da(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var d=zc(new yc(c,b));if(!Bb(c))throw Error("Bad token: "+D(c));this.evaluate=function(a,b){var c=d.a(new sb(a));return new S(c,b)}}
function S(a,b){if(0==b)if(a instanceof F)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof F))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof F?a.f():""+a;break;case 1:this.numberValue=a instanceof F?+a.f():+a;break;case 3:this.booleanValue=a instanceof F?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var d=
Ob(a);c=[];for(var e=J(d);e;e=J(d))c.push(e instanceof vb?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:d=Nb(a);this.singleNodeValue=d instanceof vb?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}S.ANY_TYPE=0;S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function Mc(a){this.lookupNamespaceURI=Ic(a)}
function Nc(a){a=a||l;var b=a.document;b.evaluate||(a.XPathResult=S,b.evaluate=function(a,b,e,f){return(new Lc(a,e)).evaluate(b,f)},b.createExpression=function(a,b){return new Lc(a,b)},b.createNSResolver=function(a){return new Mc(a)})}ba("wgxpath.install",Nc);var T={};T.C=function(){var a={ba:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
T.m=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(y||pb)&&Nc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):T.C;if(y&&!Xa(7))return d.evaluate.call(d,b,a,e,c,null);if(!y||9<=Za){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var k=g[h],m=k.namespaceURI;if(m&&!f[m]){var n=k.lookupPrefix(m);if(!n){var x=m.match(".*/(\\w+)/?$");x?n=x[1]:n="xhtml"}f[m]=n}}var G={},ha;for(ha in f)G[f[ha]]=ha;e=function(a){return G[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(uc){if("TypeError"===uc.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):T.C,d.evaluate(b,a,e,c,null);throw uc;}}catch(vc){if(!Ra||"NS_ERROR_ILLEGAL_VALUE"!=vc.name)throw new t(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+vc);}};T.D=function(a,b){if(!a||1!=a.nodeType)throw new t(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
T.o=function(a,b){var c=function(){var c=T.m(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||T.D(c,a);return c};
T.s=function(a,b){var c=function(){var c=T.m(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();r(c,function(b){T.D(b,a)});return c};function Oc(a){return(a=a.exec(v))?a[1]:""}var Pc=function(){if(mb)return Oc(/Firefox\/([0-9.]+)/);if(y||Qa||Pa)return Va;if(qb)return Oc(/Chrome\/([0-9.]+)/);if(rb&&!(Oa()||w("iPad")||w("iPod")))return Oc(/Version\/([0-9.]+)/);if(nb||ob){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(v))return a[1]+"."+a[2]}else if(pb)return(a=Oc(/Android\s+([0-9.]+)/))?a:Oc(/Version\/([0-9.]+)/);return""}();var Qc={},Rc,Sc;function Tc(a){return Uc?Rc(a):y?0<=ra(Za,a):Xa(a)}function Vc(a){return Uc?Sc(a):pb?0<=ra(Wc,a):0<=ra(Pc,a)}
var Uc=function(){if(!Ra)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(b){return!1}var c=a.classes,a=a.interfaces,d=c["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),c=c["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=c.platformVersion,f=c.version;Rc=function(a){return 0<=d.compare(e,""+a)};Sc=function(a){return 0<=d.compare(f,""+a)};return!0}(),Xc;if(pb){var Yc=/Android\s+([0-9\.]+)/.exec(v);Xc=Yc?Yc[1]:"0"}else Xc="0";
var Wc=Xc,Zc=y&&!(8<=Za),$c=y&&!(9<=Za);pb&&Vc(2.3);pb&&Vc(4);rb&&Vc(6);function ad(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}ad.prototype.clone=function(){return new ad(this.top,this.right,this.bottom,this.left)};ad.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};ad.prototype.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
ad.prototype.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};ad.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function U(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}U.prototype.clone=function(){return new U(this.left,this.top,this.width,this.height)};U.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};U.prototype.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
U.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};U.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function V(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}function bd(a,b){var c;if(c=Zc&&"value"==b&&V(a,"OPTION"))c=null===cd(a,"value");c?(c=[],jb(a,c,!1),c=c.join("")):c=a[b];return c}var dd=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function ed(a){var b=[];r(a.split(dd),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function cd(a,b){b=b.toLowerCase();if("style"==b)return ed(a.style.cssText);if(Zc&&"value"==b&&V(a,"INPUT"))return a.value;if($c&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}
function fd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return V(a)?a:null}
function W(a,b){var c=ta(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=$c?"styleFloat":"cssFloat";var d;a:{d=c;var e=B(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||gd(a,c);if(null===d)d=null;else if(0<=va(Ea,c)){b:{var f=d.match(Ha);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ia))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Da[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Fa,"#$1$1$2$2$3$3")),!Ga.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function gd(a,b){var c=a.currentStyle||a.style,d=c[b];!aa(d)&&da(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?aa(d)?d:null:(c=fd(a))?gd(c,b):null}
function hd(a,b,c){function d(a){var b=id(a);return 0<b.height&&0<b.width?!0:V(a,"PATH")&&(0<b.height||0<b.width)?(a=W(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=W(a,"overflow")&&ya(a.childNodes,function(a){return 3==a.nodeType||V(a)&&d(a)})}function e(a){return jd(a)==X&&za(a.childNodes,function(a){return!V(a)||e(a)||!d(a)})}if(!V(a))throw Error("Argument to isShown must be of type Element");if(V(a,"BODY"))return!0;if(V(a,"OPTION")||V(a,"OPTGROUP"))return a=kb(a,function(a){return V(a,"SELECT")}),
!!a&&hd(a,!0,c);var f=kd(a);if(f)return!!f.H&&0<f.rect.width&&0<f.rect.height&&hd(f.H,b,c);if(V(a,"INPUT")&&"hidden"==a.type.toLowerCase()||V(a,"NOSCRIPT"))return!1;f=W(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=ld(a))&&d(a)?!e(a):!1}function md(a){function b(a){if("none"==W(a,"display"))return!1;a=fd(a);return!a||b(a)}return hd(a,!1,b)}var X="hidden";
function jd(a){function b(a){function b(a){if(a==g)return!0;var d=W(a,"display");return oa(d,"inline")||"absolute"==c&&"static"==W(a,"position")?!1:!0}var c=W(a,"position");if("fixed"==c)return m=!0,a==g?null:g;for(a=fd(a);a&&!b(a);)a=fd(a);return a}function c(a){var b=a;if("visible"==k)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:W(b,"overflow-x"),y:W(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new ab(f)).a;
a=b.scrollingElement?b.scrollingElement:Sa||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=y&&Xa("10")&&b.pageYOffset!=a.scrollTop?new z(a.scrollLeft,a.scrollTop):new z(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new z(a.scrollLeft,a.scrollTop);return a}var e=nd(a),f=B(a),g=f.documentElement,h=f.body,k=W(g,"overflow"),m;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var x=id(a);if(0==x.width||0==x.height)return X;
var G=e.right<x.left,ha=e.bottom<x.top;if(G&&"hidden"==n.x||ha&&"hidden"==n.y)return X;if(G&&"visible"!=n.x||ha&&"visible"!=n.y){G=d(a);ha=e.bottom<x.top-G.y;if(e.right<x.left-G.x&&"visible"!=n.x||ha&&"visible"!=n.x)return X;e=jd(a);return e==X?X:"scroll"}G=e.left>=x.left+x.width;x=e.top>=x.top+x.height;if(G&&"hidden"==n.x||x&&"hidden"==n.y)return X;if(G&&"visible"!=n.x||x&&"visible"!=n.y){if(m&&(n=d(a),e.left>=g.scrollWidth-n.x||e.right>=g.scrollHeight-n.y))return X;e=jd(a);return e==X?X:"scroll"}}}return"none"}
function id(a){var b=kd(a);if(b)return b.rect;if(V(a,"HTML"))return a=B(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new $a(a.clientWidth,a.clientHeight),new U(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new U(0,0,0,0)}b=new U(c.left,c.top,c.right-c.left,c.bottom-c.top);y&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function kd(a){var b=V(a,"MAP");if(!b&&!V(a,"AREA"))return null;var c=b?a:V(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name&&(d=T.o('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=id(d),!b&&"default"!=a.shape.toLowerCase())){var f=od(a);a=Math.min(Math.max(f.left,0),e.width);b=Math.min(Math.max(f.top,0),e.height);c=Math.min(f.width,e.width-a);f=Math.min(f.height,e.height-b);e=new U(a+e.left,b+e.top,c,f)}return{H:d,rect:e||new U(0,0,0,0)}}
function od(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new U(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new U(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new U(b,c,d-b,e-c)}return new U(0,0,0,0)}function nd(a){a=id(a);return new ad(a.top,a.left+a.width,a.top+a.height,a.left)}
function pd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function qd(a){var b=[];rd(a,b);var c=b;a=c.length;for(var b=Array(a),c=p(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=pd.call(void 0,c[d]));return pd(b.join("\n")).replace(/\xa0/g," ")}
function sd(a,b,c){if(V(a,"BR"))b.push("");else{var d=V(a,"TD"),e=W(a,"display"),f=!d&&!(0<=va(td,e)),g=aa(a.previousElementSibling)?a.previousElementSibling:cb(a.previousSibling),g=g?W(g,"display"):"",h=W(a,"float")||W(a,"cssFloat")||W(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var k=md(a),m=null,n=null;k&&(m=W(a,"white-space"),n=W(a,"text-transform"));r(a.childNodes,function(a){c(a,b,k,m,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||pa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function rd(a,b){sd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?ud(a,b,f,g):V(a)&&rd(a,b)})}var td="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function ud(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";pa(c," ")&&oa(a," ")&&(a=a.substr(1));b.push(c+a)}
function ld(a){if($c){if("relative"==W(a,"position"))return 1;a=W(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return vd(a)}function vd(a){var b=1,c=W(a,"opacity");c&&(b=Number(c));(a=fd(a))&&(b*=vd(a));return b};function wd(a){ma.call(this,a)}q(wd,ma);Sa||Ra&&Tc(3.5)||y&&Tc(8);var xd={w:function(a){return!(!a.querySelectorAll||!a.querySelector)},o:function(a,b){if(!a)throw new t(32,"No class name specified");a=qa(a);if(-1!==a.indexOf(" "))throw new t(32,"Compound class names not permitted");if(xd.w(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new t(32,"An invalid or illegal class name was specified");}var d=lb(A(b),"*",a,b);return d.length?d[0]:null},s:function(a,b){if(!a)throw new t(32,"No class name specified");a=qa(a);if(-1!==a.indexOf(" "))throw new t(32,
"Compound class names not permitted");if(xd.w(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new t(32,"An invalid or illegal class name was specified");}return lb(A(b),"*",a,b)}};var yd={o:function(a,b){if(!da(b.querySelector)&&y&&Tc(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new t(32,"No selector specified");a=qa(a);var c;try{c=b.querySelector(a)}catch(d){throw new t(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},s:function(a,b){if(!da(b.querySelectorAll)&&y&&Tc(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new t(32,"No selector specified");a=qa(a);try{return b.querySelectorAll(a)}catch(c){throw new t(32,
"An invalid or illegal selector was specified");}}};var zd={w:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},o:function(a,b){var c=A(b),d=p(a)?c.a.getElementById(a):a;if(!d)return null;if(cd(d,"id")==a&&db(b,d))return d;c=lb(c,"*");return Aa(c,function(c){return cd(c,"id")==a&&db(b,c)})},s:function(a,b){if(!a)return[];if(zd.w(b,a))try{return b.querySelectorAll("#"+zd.R(a))}catch(c){return[]}var d=lb(A(b),"*",null,b);return wa(d,function(b){return cd(b,"id")==a})},R:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Y={},Ad={};Y.M=function(a,b,c){var d;try{d=yd.s("a",b)}catch(e){d=lb(A(b),"A",null,b)}return Aa(d,function(b){b=qd(b);return c&&-1!=b.indexOf(a)||b==a})};Y.I=function(a,b,c){var d;try{d=yd.s("a",b)}catch(e){d=lb(A(b),"A",null,b)}return wa(d,function(b){b=qd(b);return c&&-1!=b.indexOf(a)||b==a})};Y.o=function(a,b){return Y.M(a,b,!1)};Y.s=function(a,b){return Y.I(a,b,!1)};Ad.o=function(a,b){return Y.M(a,b,!0)};Ad.s=function(a,b){return Y.I(a,b,!0)};var Bd={o:function(a,b){if(""===a)throw new t(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},s:function(a,b){if(""===a)throw new t(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Cd={className:xd,"class name":xd,css:yd,"css selector":yd,id:zd,linkText:Y,"link text":Y,name:{o:function(a,b){var c=lb(A(b),"*",null,b);return Aa(c,function(b){return cd(b,"name")==a})},s:function(a,b){var c=lb(A(b),"*",null,b);return wa(c,function(b){return cd(b,"name")==a})}},partialLinkText:Ad,"partial link text":Ad,tagName:Bd,"tag name":Bd,xpath:T};
function Dd(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Cd[c];if(d&&da(d.o))return d.o(a[c],b||la.document)}throw Error("Unsupported locator strategy: "+c);};var Ed={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new wd("Illegal Index: "+a);if(b.length<=c)throw new wd("Index out of range: "+a);return[b[c]]},name:function(a,b){return wa(b,function(b){return bd(b,"name")==a})},value:function(a,b){return wa(b,function(b){return bd(b,"value")===a})}};function Fd(a,b){return(new RegExp(a)).test(b)}function Gd(a,b){return(new RegExp(a,"i")).test(b)}function Hd(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Id={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Hd(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Hd(a))).test(b)},regex:Fd,regexi:Gd,regexpi:Gd,regexp:Fd};function Jd(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=Jd(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Qc.Y&&Vc(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={T:function(a,b){return oa(a,"//")?Z.N(a,b):oa(a,"document.")?Z.F(a,b):Z.G(a,b)},O:function(a,b){return Kd(b||B(la),function(b){return b.alt==a})},P:function(a,b){return Kd(b||B(la),function(b){return b.className==a})},F:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},S:function(a,b){return Dd({id:a},b)},G:function(a,b){return Z.id(a,b)||Z.name(a,b)},j:function(a,b){var c=b||B(la);A(c);var d;d=bb(document,"*",null,c);c=a.split(" ");for(c[0]="name="+c[0];c.length;){var e=
c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=Ed[d];if(!g)throw new wd("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},V:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,h=g.$wdc_;h||(h=g.$wdc_={},h.J=ka());h.J||(h.J=ka());f=h;if(!(null!==f&&d in f))throw new t(10,"Element does not exist in cache");var k=f[d];if(null!==k&&"setInterval"in k){if(k.closed)throw delete f[d],new t(23,
"Window has been closed.");c=k}else{for(g=k;g;){if(g==e.documentElement){c=k;break a}g=g.parentNode}delete f[d];throw new t(10,"Element is no longer attached to the DOM");}}return c}catch(m){return null}},N:function(a,b){var c=pa(a,"/"),d={xpath:a};try{var e=Dd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Dd(d,b)}};Z.alt=Z.O;Z["class"]=Z.P;Z.dom=Z.F;Z.id=Z.S;Z.identifier=Z.G;Z.implicit=Z.T;
Z.link=function(a,b){for(var c=(b||B(la)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";Ra&&"1.8"<=Va||Sa||y?g=Jd(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Sa)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");var g=f,f=qa(g),h=a,g="glob",k=/^([a-zA-Z-]+):(.*)/.exec(h);if(k){var m=k[1],k=k[2];Id[m.toLowerCase()]&&(g=
m.toLowerCase(),h=k)}m=Id[g];if(!m)throw new wd("Cannot find pattern matching strategy: "+g);"glob"==g?(0==h.indexOf("glob:")&&(h=h.substring(5)),m=Id.glob):"exact"==g&&0==h.indexOf("exact:")&&(h=h.substring(6));h=ja(m,h);h.$=g;if(h(f))return e}return null};Z.name=Z.j;Z.stored=Z.V;Z.xpath=Z.N;function Ld(a,b,c,d){var e=Z[a];if(!e)throw new wd("Unrecognised locator type: '"+a+"'");c=e.call(null,b,c);if(null!=c)return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=Ld(a,b,f,d.frames[e]),null!=c))return c}return null}function Kd(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType){if(b(e))return e;if(e=Kd(e,b))return e}}return null};ba("_",function(a){var b,c=a.lastIndexOf("@");b=a.slice(c+1);c=a.slice(0,c);if(p(c)){var d;(d=c.match(/^([A-Za-z]+)=.+/))?(d=d[1].toLowerCase(),d={type:d,string:c.substring(d.length+1)}):(d={string:"",type:""},d.string=c,d.type=oa(c,"//")?"xpath":oa(c,"document.")?"dom":"identifier");var e=la||la;d=Ld(d.type,d.string,e.document,e);if(null==d)throw new wd("Element "+c+" not found");c=d}b=cd(c,b);if(null==b)throw new wd("Could not find element attribute: "+a);return b});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
