function(){return function(){var h,m=this;function p(a){return void 0!==a}function aa(a,b){var c=a.split("."),d=m;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return"string"==typeof a}function ca(a){return"number"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a,b,c){return a.call.apply(a.bind,arguments)}
function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ha(a,b,c){ha=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return ha.apply(null,arguments)}
function ia(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function t(a,b){function c(){}c.prototype=b.prototype;a.ea=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ca=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};var la=window;function ma(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}t(ma,Error);ma.prototype.name="CustomError";var na;function oa(a,b){return 0==a.lastIndexOf(b,0)}function pa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ra(a,b){for(var c=0,d=qa(String(a)).split("."),e=qa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",l=e[g]||"",n=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var z=n.exec(k)||["","",""],I=q.exec(l)||["","",""];if(0==z[0].length&&0==I[0].length)break;c=sa(0==z[1].length?0:parseInt(z[1],10),0==I[1].length?0:parseInt(I[1],10))||sa(0==z[2].length,0==I[2].length)||sa(z[2],I[2])}while(0==c)}return c}function sa(a,b){return a<b?-1:a>b?1:0}
function ta(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var ua=Array.prototype;function va(a,b){if(r(a))return r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function u(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function wa(a,b){for(var c=a.length,d=[],e=0,f=r(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}function xa(a,b,c){var d=c;u(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function ya(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function za(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Aa(a,b){var c;a:{c=a.length;for(var d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:r(a)?a.charAt(c):a[c]}function Ba(a){return ua.concat.apply(ua,arguments)}
function Ca(a,b,c){return 2>=arguments.length?ua.slice.call(a,b):ua.slice.call(a,b,c)};var Da={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ea="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Fa=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ga=/^#(?:[0-9a-f]{3}){1,2}$/i,Ha=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ia=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function v(a,b){this.code=a;this.a=w[a]||Ja;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}t(v,Error);var Ja="unknown error",w={15:"element not selectable",11:"element not visible"};w[31]=Ja;w[30]=Ja;w[24]="invalid cookie domain";w[29]="invalid element coordinates";w[12]="invalid element state";
w[32]="invalid selector";w[51]="invalid selector";w[52]="invalid selector";w[17]="javascript error";w[405]="unsupported operation";w[34]="move target out of bounds";w[27]="no such alert";w[7]="no such element";w[8]="no such frame";w[23]="no such window";w[28]="script timeout";w[33]="session not created";w[10]="stale element reference";w[21]="timeout";w[25]="unable to set cookie";w[26]="unexpected alert open";w[13]=Ja;w[9]="unknown command";v.prototype.toString=function(){return this.name+": "+this.message};var Ka;a:{var La=m.navigator;if(La){var Ma=La.userAgent;if(Ma){Ka=Ma;break a}}Ka=""}function x(a){return-1!=Ka.indexOf(a)};function Na(){return x("Opera")||x("OPR")}function Oa(){return(x("Chrome")||x("CriOS"))&&!Na()&&!x("Edge")};function Pa(){return x("iPhone")&&!x("iPod")&&!x("iPad")};var Qa=Na(),y=x("Trident")||x("MSIE"),Ra=x("Edge"),Sa=x("Gecko")&&!(-1!=Ka.toLowerCase().indexOf("webkit")&&!x("Edge"))&&!(x("Trident")||x("MSIE"))&&!x("Edge"),Ta=-1!=Ka.toLowerCase().indexOf("webkit")&&!x("Edge"),Ua=x("Macintosh"),Va=x("Windows");function Wa(){var a=Ka;if(Sa)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ra)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ta)return/WebKit\/(\S+)/.exec(a)}
function Xa(){var a=m.document;return a?a.documentMode:void 0}var Ya=function(){if(Qa&&m.opera){var a;var b=m.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Wa())&&(a=b?b[1]:"");return y&&(b=Xa(),b>parseFloat(a))?String(b):a}(),Za={};function $a(a){return Za[a]||(Za[a]=0<=ra(Ya,a))}var ab=m.document,bb=ab&&y?Xa()||("CSS1Compat"==ab.compatMode?parseInt(Ya,10):5):void 0;!Sa&&!y||y&&9<=bb||Sa&&$a("1.9.1");y&&$a("9");function cb(a,b){this.x=p(a)?a:0;this.y=p(b)?b:0}h=cb.prototype;h.clone=function(){return new cb(this.x,this.y)};h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){var c=ca(b)?b:a;this.x*=a;this.y*=c;return this};function db(a,b){this.width=a;this.height=b}h=db.prototype;h.clone=function(){return new db(this.width,this.height)};h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=ca(b)?b:a;this.width*=a;this.height*=c;return this};function eb(a){return a?new fb(A(a)):na||(na=new fb)}
function gb(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,k;if(k="function"==typeof e.split)k=0<=va(e.split(/\s+/),c);k&&(a[d++]=g)}a.length=d;return a}return b}
function hb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function ib(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function jb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=bb)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?kb(a,b):!c&&ib(e,b)?-1*lb(a,b):!d&&ib(f,a)?lb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=A(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,d)}function lb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return kb(d,a)}function kb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function A(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var mb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},nb={IMG:" ",BR:"\n"};
function ob(a,b,c){if(!(a.nodeName in mb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in nb)b.push(nb[a.nodeName]);else for(a=a.firstChild;a;)ob(a,b,c),a=a.nextSibling}function pb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function fb(a){this.a=a||m.document||document}function qb(a,b,c,d){return gb(a.a,b,c,d)}fb.prototype.contains=ib;var rb=x("Firefox"),sb=Pa()||x("iPod"),tb=x("iPad"),ub=x("Android")&&!(Oa()||x("Firefox")||Na()||x("Silk")),vb=Oa(),wb=x("Safari")&&!(Oa()||x("Coast")||Na()||x("Edge")||x("Silk")||x("Android"))&&!(Pa()||x("iPad")||x("iPod"));/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function xb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var yb=y&&!(9<=bb),zb=y&&!(8<=bb);function Ab(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Bb(a,b){var c=zb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Ab(b,a,b.nodeName,c)};function Cb(a){this.b=a;this.a=0}function Db(a){a=a.match(Eb);for(var b=0;b<a.length;b++)Fb.test(a[b])&&a.splice(b,1);return new Cb(a)}var Eb=RegExp("\\$?(?:(?![0-9-])[\\w-]+:)?(?![0-9-])[\\w-]+|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Fb=/^\s/;function B(a,b){return a.b[a.a+(b||0)]}function C(a){return a.b[a.a++]}function Gb(a){return a.b.length<=a.a};function D(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(yb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),yb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Hb(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}zb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Ib(a,b,c,d,e){return(yb?Jb:Kb).call(null,a,b,r(c)?c:null,r(d)?d:null,e||new E)}
function Jb(a,b,c,d,e){if(a instanceof Lb||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=Mb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],k=0;b=f[k++];)Hb(b,c,d)&&g.push(b);f=g}for(k=0;b=f[k++];)"*"==a&&"!"==b.tagName||F(e,b);return e}Nb(a,b,c,d,e);return e}
function Kb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!y?(b=b.getElementsByName(d),u(b,function(b){a.a(b)&&F(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),u(b,function(b){b.className==d&&a.a(b)&&F(e,b)})):a instanceof G?Nb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),u(b,function(a){Hb(a,c,d)&&F(e,a)}));return e}
function Ob(a,b,c,d,e){var f;if((a instanceof Lb||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Mb(a);if("*"!=g&&(f=wa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=wa(f,function(a){return Hb(a,c,d)}));u(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||F(e,a)});return e}return Pb(a,b,c,d,e)}function Pb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Hb(b,c,d)&&a.a(b)&&F(e,b);return e}
function Nb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Hb(b,c,d)&&a.a(b)&&F(e,b),Nb(a,b,c,d,e)}function Mb(a){if(a instanceof G){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function E(){this.b=this.a=null;this.s=0}function Qb(a){this.node=a;this.a=this.b=null}function Rb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f=null,g=0;c&&d;){var f=c.node,k=d.node;f==k||f instanceof Ab&&k instanceof Ab&&f.a==k.a?(f=c,c=c.a,d=d.a):0<jb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.s=g;return a}
E.prototype.unshift=function(a){a=new Qb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.s++};function F(a,b){var c=new Qb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.s++}function Sb(a){return(a=a.a)?a.node:null}E.prototype.f=function(){var a=Sb(this);return a?D(a):""};function Tb(a,b){return new Ub(a,!!b)}function Ub(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function H(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.c?b.b:b.a;return c.node};function J(a){this.m=a;this.b=this.i=!1;this.f=null}function K(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Vb(a,b){a.i=b}function Wb(a,b){a.b=b}function L(a,b){var c=a.a(b);return c instanceof E?+c.f():+c}function M(a,b){var c=a.a(b);return c instanceof E?c.f():""+c}function Xb(a,b){var c=a.a(b);return c instanceof E?!!c.s:!!c};function Yb(a,b,c){J.call(this,a.m);this.c=a;this.j=b;this.B=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==Zb&&(c.b||c.i||4==c.m||0==c.m||!b.f?b.b||b.i||4==b.m||0==b.m||!c.f||(this.f={name:c.f.name,C:b}):this.f={name:b.f.name,C:c})}t(Yb,J);
function $b(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof E&&c instanceof E){e=Tb(b);for(d=H(e);d;d=H(e))for(b=Tb(c),f=H(b);f;f=H(b))if(a(D(d),D(f)))return!0;return!1}if(b instanceof E||c instanceof E){b instanceof E?e=b:(e=c,c=b);e=Tb(e);b=typeof c;for(d=H(e);d;d=H(e)){switch(b){case "number":d=+D(d);break;case "boolean":d=!!D(d);break;case "string":d=D(d);break;default:throw Error("Illegal primitive type for comparison.");}if(a(d,c))return!0}return!1}return e?"boolean"==typeof b||"boolean"==
typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Yb.prototype.a=function(a){return this.c.u(this.j,this.B,a)};Yb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+K(this.j);return a+=K(this.B)};function ac(a,b,c,d){this.a=a;this.P=b;this.m=c;this.u=d}ac.prototype.toString=function(){return this.a};var bc={};
function N(a,b,c,d){if(bc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new ac(a,b,c,d);return bc[a.toString()]=a}N("div",6,1,function(a,b,c){return L(a,c)/L(b,c)});N("mod",6,1,function(a,b,c){return L(a,c)%L(b,c)});N("*",6,1,function(a,b,c){return L(a,c)*L(b,c)});N("+",5,1,function(a,b,c){return L(a,c)+L(b,c)});N("-",5,1,function(a,b,c){return L(a,c)-L(b,c)});N("<",4,2,function(a,b,c){return $b(function(a,b){return a<b},a,b,c)});
N(">",4,2,function(a,b,c){return $b(function(a,b){return a>b},a,b,c)});N("<=",4,2,function(a,b,c){return $b(function(a,b){return a<=b},a,b,c)});N(">=",4,2,function(a,b,c){return $b(function(a,b){return a>=b},a,b,c)});var Zb=N("=",3,2,function(a,b,c){return $b(function(a,b){return a==b},a,b,c,!0)});N("!=",3,2,function(a,b,c){return $b(function(a,b){return a!=b},a,b,c,!0)});N("and",2,2,function(a,b,c){return Xb(a,c)&&Xb(b,c)});N("or",1,2,function(a,b,c){return Xb(a,c)||Xb(b,c)});function cc(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");J.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}t(cc,J);cc.prototype.a=function(a){a=this.c.a(a);return dc(this.j,a)};cc.prototype.toString=function(){var a;a="Filter:"+K(this.c);return a+=K(this.j)};function ec(a,b){if(b.length<a.O)throw Error("Function "+a.o+" expects at least"+a.O+" arguments, "+b.length+" given");if(null!==a.G&&b.length>a.G)throw Error("Function "+a.o+" expects at most "+a.G+" arguments, "+b.length+" given");a.aa&&u(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});J.call(this,a.m);this.j=a;this.c=b;Vb(this,a.i||ya(b,function(a){return a.i}));Wb(this,a.$&&!b.length||a.Y&&!!b.length||ya(b,function(a){return a.b}))}
t(ec,J);ec.prototype.a=function(a){return this.j.u.apply(null,Ba(a,this.c))};ec.prototype.toString=function(){var a="Function: "+this.j;if(this.c.length)var b=xa(this.c,function(a,b){return a+K(b)},"Arguments:"),a=a+K(b);return a};function fc(a,b,c,d,e,f,g,k,l){this.o=a;this.m=b;this.i=c;this.$=d;this.Y=e;this.u=f;this.O=g;this.G=p(k)?k:g;this.aa=!!l}fc.prototype.toString=function(){return this.o};var gc={};
function O(a,b,c,d,e,f,g,k){if(gc.hasOwnProperty(a))throw Error("Function already created: "+a+".");gc[a]=new fc(a,b,c,d,!1,e,f,g,k)}O("boolean",2,!1,!1,function(a,b){return Xb(b,a)},1);O("ceiling",1,!1,!1,function(a,b){return Math.ceil(L(b,a))},1);O("concat",3,!1,!1,function(a,b){return xa(Ca(arguments,1),function(b,d){return b+M(d,a)},"")},2,null);O("contains",2,!1,!1,function(a,b,c){b=M(b,a);a=M(c,a);return-1!=b.indexOf(a)},2);O("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
O("false",2,!1,!1,function(){return!1},0);O("floor",1,!1,!1,function(a,b){return Math.floor(L(b,a))},1);O("id",4,!1,!1,function(a,b){function c(a){if(yb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Aa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=M(b,a).split(/\s+/),f=[];u(d,function(a){a=c(a);!a||0<=va(f,a)||f.push(a)});f.sort(jb);var g=new E;u(f,function(a){F(g,a)});return g},1);
O("lang",2,!1,!1,function(){return!1},1);O("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);O("local-name",3,!1,!0,function(a,b){var c=b?Sb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);O("name",3,!1,!0,function(a,b){var c=b?Sb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);O("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
O("normalize-space",3,!1,!0,function(a,b){return(b?M(b,a):D(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);O("not",2,!1,!1,function(a,b){return!Xb(b,a)},1);O("number",1,!1,!0,function(a,b){return b?L(b,a):+D(a.a)},0,1);O("position",1,!0,!1,function(a){return a.b},0);O("round",1,!1,!1,function(a,b){return Math.round(L(b,a))},1);O("starts-with",2,!1,!1,function(a,b,c){return oa(M(b,a),M(c,a))},2);O("string",3,!1,!0,function(a,b){return b?M(b,a):D(a.a)},0,1);
O("string-length",1,!1,!0,function(a,b){return(b?M(b,a):D(a.a)).length},0,1);O("substring",3,!1,!1,function(a,b,c,d){c=L(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?L(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=M(b,a);if(Infinity==d)return a.substring(e);b=Math.round(d);return a.substring(e,c+b)},2,3);O("substring-after",3,!1,!1,function(a,b,c){b=M(b,a);a=M(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
O("substring-before",3,!1,!1,function(a,b,c){b=M(b,a);a=M(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);O("sum",1,!1,!1,function(a,b){for(var c=Tb(b.a(a)),d=0,e=H(c);e;e=H(c))d+=+D(e);return d},1,1,!0);O("translate",3,!1,!1,function(a,b,c,d){b=M(b,a);c=M(c,a);var e=M(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);O("true",2,!1,!1,function(){return!0},0);function G(a,b){this.j=a;this.c=p(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function hc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}G.prototype.a=function(a){return null===this.b||this.b==a.nodeType};G.prototype.f=function(){return this.j};
G.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=K(this.c));return a};function ic(a){J.call(this,3);this.c=a.substring(1,a.length-1)}t(ic,J);ic.prototype.a=function(){return this.c};ic.prototype.toString=function(){return"Literal: "+this.c};function Lb(a,b){this.o=a.toLowerCase();this.c=b?b.toLowerCase():"http://www.w3.org/1999/xhtml"}Lb.prototype.a=function(a){var b=a.nodeType;return 1!=b&&2!=b?!1:"*"!=this.o&&this.o!=a.nodeName.toLowerCase()?!1:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Lb.prototype.f=function(){return this.o};Lb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function jc(a){J.call(this,1);this.c=a}t(jc,J);jc.prototype.a=function(){return this.c};jc.prototype.toString=function(){return"Number: "+this.c};function kc(a,b){J.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.F||c.c!=lc||(c=c.B,"*"!=c.f()&&(this.f={name:c.f(),C:null}))}}t(kc,J);function mc(){J.call(this,4)}t(mc,J);mc.prototype.a=function(a){var b=new E;a=a.a;9==a.nodeType?F(b,a):F(b,a.ownerDocument);return b};mc.prototype.toString=function(){return"Root Helper Expression"};function nc(){J.call(this,4)}t(nc,J);nc.prototype.a=function(a){var b=new E;F(b,a.a);return b};nc.prototype.toString=function(){return"Context Helper Expression"};
function oc(a){return"/"==a||"//"==a}kc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof E))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=Tb(b,e.c.a),g;if(e.i||e.c!=pc)if(e.i||e.c!=qc)for(g=H(f),b=e.a(new xb(g));null!=(g=H(f));)g=e.a(new xb(g)),b=Rb(b,g);else g=H(f),b=e.a(new xb(g));else{for(g=H(f);(b=H(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new xb(g))}}return b};
kc.prototype.toString=function(){var a;a="Path Expression:"+K(this.j);if(this.c.length){var b=xa(this.c,function(a,b){return a+K(b)},"Steps:");a+=K(b)}return a};function rc(a,b){this.a=a;this.b=!!b}
function dc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Tb(b),f=b.s,g,k=0;g=H(e);k++){var l=a.b?f-k:k+1;g=d.a(new xb(g,l,f));if("number"==typeof g)l=l==g;else if("string"==typeof g||"boolean"==typeof g)l=!!g;else if(g instanceof E)l=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!l){l=e;g=l.f;var n=l.a;if(!n)throw Error("Next must be called at least once before remove.");var q=n.b,n=n.a;q?q.a=n:g.a=n;n?n.b=q:g.b=q;g.s--;l.a=null}}return b}
rc.prototype.toString=function(){return xa(this.a,function(a,b){return a+K(b)},"Predicates:")};function sc(a,b,c,d){J.call(this,4);this.c=a;this.B=b;this.j=c||new rc([]);this.F=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=yb?a.toLowerCase():a,this.f={name:a,C:b.C});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}t(sc,J);
sc.prototype.a=function(a){var b=a.a,c=null,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.C?M(c.C,a):null,f=1);if(this.F)if(this.i||this.c!=tc)if(a=Tb((new sc(uc,new G("node"))).a(a)),b=H(a))for(c=this.u(b,d,e,f);null!=(b=H(a));)c=Rb(c,this.u(b,d,e,f));else c=new E;else c=Ib(this.B,b,d,e),c=dc(this.j,c,f);else c=this.u(a.a,d,e,f);return c};sc.prototype.u=function(a,b,c,d){a=this.c.f(this.B,a,b,c);return a=dc(this.j,a,d)};
sc.prototype.toString=function(){var a;a="Step:"+K("Operator: "+(this.F?"//":"/"));this.c.o&&(a+=K("Axis: "+this.c));a+=K(this.B);if(this.j.a.length){var b=xa(this.j.a,function(a,b){return a+K(b)},"Predicates:");a+=K(b)}return a};function vc(a,b,c,d){this.o=a;this.f=b;this.a=c;this.b=d}vc.prototype.toString=function(){return this.o};var wc={};function P(a,b,c,d){if(wc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new vc(a,b,c,!!d);return wc[a]=b}
P("ancestor",function(a,b){for(var c=new E,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);P("ancestor-or-self",function(a,b){var c=new E,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var lc=P("attribute",function(a,b){var c=new E,d=a.f();if("style"==d&&b.style&&yb)return F(c,new Ab(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof G&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)yb?f.nodeValue&&F(c,Bb(b,f)):F(c,f);else(f=e.getNamedItem(d))&&(yb?f.nodeValue&&F(c,Bb(b,f)):F(c,f));return c},!1),tc=P("child",function(a,b,c,d,e){return(yb?Ob:Pb).call(null,a,b,r(c)?c:null,r(d)?d:null,e||new E)},!1,!0);P("descendant",Ib,!1,!0);
var uc=P("descendant-or-self",function(a,b,c,d){var e=new E;Hb(b,c,d)&&a.a(b)&&F(e,b);return Ib(a,b,c,d,e)},!1,!0),pc=P("following",function(a,b,c,d){var e=new E;do for(var f=b;f=f.nextSibling;)Hb(f,c,d)&&a.a(f)&&F(e,f),e=Ib(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);P("following-sibling",function(a,b){for(var c=new E,d=b;d=d.nextSibling;)a.a(d)&&F(c,d);return c},!1);P("namespace",function(){return new E},!1);
var xc=P("parent",function(a,b){var c=new E;if(9==b.nodeType)return c;if(2==b.nodeType)return F(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&F(c,d);return c},!1),qc=P("preceding",function(a,b,c,d){var e=new E,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var l=[];for(b=f[g];b=b.previousSibling;)l.unshift(b);for(var n=0,q=l.length;n<q;n++)b=l[n],Hb(b,c,d)&&a.a(b)&&F(e,b),e=Ib(a,b,c,d,e)}return e},!0,!0);
P("preceding-sibling",function(a,b){for(var c=new E,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var yc=P("self",function(a,b){var c=new E;a.a(b)&&F(c,b);return c},!1);function zc(a){J.call(this,1);this.c=a;this.i=a.i;this.b=a.b}t(zc,J);zc.prototype.a=function(a){return-L(this.c,a)};zc.prototype.toString=function(){return"Unary Expression: -"+K(this.c)};function Ac(a){J.call(this,4);this.c=a;Vb(this,ya(this.c,function(a){return a.i}));Wb(this,ya(this.c,function(a){return a.b}))}t(Ac,J);Ac.prototype.a=function(a){var b=new E;u(this.c,function(c){c=c.a(a);if(!(c instanceof E))throw Error("Path expression must evaluate to NodeSet.");b=Rb(b,c)});return b};Ac.prototype.toString=function(){return xa(this.c,function(a,b){return a+K(b)},"Union Expression:")};function Bc(a,b){this.a=a;this.b=b}function Cc(a){for(var b,c=[];;){Q(a,"Missing right hand side of binary expression.");b=Dc(a);var d=C(a.a);if(!d)break;var e=(d=bc[d]||null)&&d.P;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].P;)b=new Yb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Yb(c.pop(),c.pop(),b);return b}function Q(a,b){if(Gb(a.a))throw Error(b);}function Ec(a,b){var c=C(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Hc(a){a=C(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Ic(a){a=C(a.a);if(2>a.length)throw Error("Unclosed literal string");return new ic(a)}function Jc(a){var b=C(a.a),c=b.indexOf(":");if(-1==c)return new Lb(b);var d=b.substring(0,c);a=a.b(d);if(!a)throw Error("Namespace prefix not declared: "+d);b=b.substr(c+1);return new Lb(b,a)}
function Kc(a){var b,c=[],d;if(oc(B(a.a))){b=C(a.a);d=B(a.a);if("/"==b&&(Gb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new mc;d=new mc;Q(a,"Missing next location step.");b=Lc(a,b);c.push(b)}else{a:{b=B(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":C(a.a);b=Cc(a);Q(a,'unclosed "("');Ec(a,")");break;case '"':case "'":b=Ic(a);break;default:if(isNaN(+b))if(!hc(b)&&/(?![0-9])[\w]/.test(d)&&"("==B(a.a,1)){b=C(a.a);
b=gc[b]||null;C(a.a);for(d=[];")"!=B(a.a);){Q(a,"Missing function argument list.");d.push(Cc(a));if(","!=B(a.a))break;C(a.a)}Q(a,"Unclosed function argument list.");Hc(a);b=new ec(b,d)}else{b=null;break a}else b=new jc(+C(a.a))}"["==B(a.a)&&(d=new rc(Mc(a)),b=new cc(b,d))}if(b)if(oc(B(a.a)))d=b;else return b;else b=Lc(a,"/"),d=new nc,c.push(b)}for(;oc(B(a.a));)b=C(a.a),Q(a,"Missing next location step."),b=Lc(a,b),c.push(b);return new kc(d,c)}
function Lc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==B(a.a))return d=new sc(yc,new G("node")),C(a.a),d;if(".."==B(a.a))return d=new sc(xc,new G("node")),C(a.a),d;var f;if("@"==B(a.a))f=lc,C(a.a),Q(a,"Missing attribute name");else if("::"==B(a.a,1)){if(!/(?![0-9])[\w]/.test(B(a.a).charAt(0)))throw Error("Bad token: "+C(a.a));c=C(a.a);f=wc[c]||null;if(!f)throw Error("No axis with name: "+c);C(a.a);Q(a,"Missing node name")}else f=tc;c=B(a.a);if(/(?![0-9])[\w]/.test(c.charAt(0)))if("("==
B(a.a,1)){if(!hc(c))throw Error("Invalid node type: "+c);c=C(a.a);if(!hc(c))throw Error("Invalid type name: "+c);Ec(a,"(");Q(a,"Bad nodetype");e=B(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Ic(a);Q(a,"Bad nodetype");Hc(a);c=new G(c,g)}else c=Jc(a);else if("*"==c)c=Jc(a);else throw Error("Bad token: "+C(a.a));e=new rc(Mc(a),f.a);return d||new sc(f,c,e,"//"==b)}
function Mc(a){for(var b=[];"["==B(a.a);){C(a.a);Q(a,"Missing predicate expression.");var c=Cc(a);b.push(c);Q(a,"Unclosed predicate expression.");Ec(a,"]")}return b}function Dc(a){if("-"==B(a.a))return C(a.a),new zc(Dc(a));var b=Kc(a);if("|"!=B(a.a))a=b;else{for(b=[b];"|"==C(a.a);)Q(a,"Missing next union location path."),b.push(Kc(a));a.a.a--;a=new Ac(b)}return a};function Nc(a){switch(a.nodeType){case 1:return ia(Oc,a);case 9:return Nc(a.documentElement);case 11:case 10:case 6:case 12:return Pc;default:return a.parentNode?Nc(a.parentNode):Pc}}function Pc(){return null}function Oc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Oc(a.parentNode,b):null};function Qc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Db(a);if(Gb(c))throw Error("Invalid XPath expression.");b?da(b)||(b=ha(b.lookupNamespaceURI,b)):b=function(){return null};var d=Cc(new Bc(c,b));if(!Gb(c))throw Error("Bad token: "+C(c));this.evaluate=function(a,b){var c=d.a(new xb(a));return new R(c,b)}}
function R(a,b){if(0==b)if(a instanceof E)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof E))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof E?a.f():""+a;break;case 1:this.numberValue=a instanceof E?+a.f():+a;break;case 3:this.booleanValue=a instanceof E?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var d=
Tb(a);c=[];for(var e=H(d);e;e=H(d))c.push(e instanceof Ab?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:d=Sb(a);this.singleNodeValue=d instanceof Ab?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}R.ANY_TYPE=0;R.NUMBER_TYPE=1;R.STRING_TYPE=2;R.BOOLEAN_TYPE=3;R.UNORDERED_NODE_ITERATOR_TYPE=4;R.ORDERED_NODE_ITERATOR_TYPE=5;R.UNORDERED_NODE_SNAPSHOT_TYPE=6;R.ORDERED_NODE_SNAPSHOT_TYPE=7;R.ANY_UNORDERED_NODE_TYPE=8;R.FIRST_ORDERED_NODE_TYPE=9;function Rc(a){this.lookupNamespaceURI=Nc(a)}
function Sc(a){a=a||m;var b=a.document;b.evaluate||(a.XPathResult=R,b.evaluate=function(a,b,e,f){return(new Qc(a,e)).evaluate(b,f)},b.createExpression=function(a,b){return new Qc(a,b)},b.createNSResolver=function(a){return new Rc(a)})}aa("wgxpath.install",Sc);var S={};S.H=function(){var a={fa:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
S.u=function(a,b,c){var d=A(a);if(!d.documentElement)return null;(y||ub)&&Sc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):S.H;if(y&&!$a(7))return d.evaluate.call(d,b,a,e,c,null);if(!y||9<=bb){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var l=g[k],n=l.namespaceURI;if(n&&!f[n]){var q=l.lookupPrefix(n);if(!q){var z=n.match(".*/(\\w+)/?$");z?q=z[1]:q="xhtml"}f[n]=q}}var I={},ja;for(ja in f)I[f[ja]]=ja;e=function(a){return I[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(Fc){if("TypeError"===Fc.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):S.H,d.evaluate(b,a,e,c,null);throw Fc;}}catch(Gc){if(!Sa||"NS_ERROR_ILLEGAL_VALUE"!=Gc.name)throw new v(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Gc);}};S.I=function(a,b){if(!a||1!=a.nodeType)throw new v(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
S.v=function(a,b){var c=function(){var c=S.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||S.I(c,a);return c};
S.w=function(a,b){var c=function(){var c=S.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();u(c,function(b){S.I(b,a)});return c};function Tc(a){return(a=a.exec(Ka))?a[1]:""}var Uc=function(){if(rb)return Tc(/Firefox\/([0-9.]+)/);if(y||Ra||Qa)return Ya;if(vb)return Tc(/Chrome\/([0-9.]+)/);if(wb&&!(Pa()||x("iPad")||x("iPod")))return Tc(/Version\/([0-9.]+)/);if(sb||tb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ka))return a[1]+"."+a[2]}else if(ub)return(a=Tc(/Android\s+([0-9.]+)/))?a:Tc(/Version\/([0-9.]+)/);return""}();var Vc={},Wc,Xc;function Yc(a){return Zc?Wc(a):y?0<=ra(bb,a):$a(a)}function $c(a){return Zc?Xc(a):ub?0<=ra(ad,a):0<=ra(Uc,a)}
var Zc=function(){if(!Sa)return!1;var a=m.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(b){return!1}var c=a.classes,a=a.interfaces,d=c["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),c=c["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=c.platformVersion,f=c.version;Wc=function(a){return 0<=d.compare(e,""+a)};Xc=function(a){return 0<=d.compare(f,""+a)};return!0}(),bd;if(ub){var cd=/Android\s+([0-9\.]+)/.exec(Ka);bd=cd?cd[1]:"0"}else bd="0";
var ad=bd,dd=y&&!(8<=bb),ed=y&&!(9<=bb);ub&&$c(2.3);ub&&$c(4);wb&&$c(6);function fd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=fd.prototype;h.clone=function(){return new fd(this.top,this.right,this.bottom,this.left)};h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof fd?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.scale=function(a,b){var c=ca(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function T(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=T.prototype;h.clone=function(){return new T(this.left,this.top,this.width,this.height)};h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof T?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=ca(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function U(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}function gd(a,b){var c;if(c=dd&&"value"==b&&U(a,"OPTION"))c=null===hd(a,"value");c?(c=[],ob(a,c,!1),c=c.join("")):c=a[b];return c}var id=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function jd(a){var b=[];u(a.split(id),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function hd(a,b){b=b.toLowerCase();if("style"==b)return jd(a.style.cssText);if(dd&&"value"==b&&U(a,"INPUT"))return a.value;if(ed&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}
function kd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return U(a)?a:null}
function V(a,b){var c=ta(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=ed?"styleFloat":"cssFloat";var d;a:{d=c;var e=A(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||ld(a,c);if(null===d)d=null;else if(0<=va(Ea,c)){b:{var f=d.match(Ha);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ia))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Da[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Fa,"#$1$1$2$2$3$3")),!Ga.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function ld(a,b){var c=a.currentStyle||a.style,d=c[b];!p(d)&&da(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?p(d)?d:null:(c=kd(a))?ld(c,b):null}
function md(a,b,c){function d(a){var b=nd(a);return 0<b.height&&0<b.width?!0:U(a,"PATH")&&(0<b.height||0<b.width)?(a=V(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=V(a,"overflow")&&ya(a.childNodes,function(a){return 3==a.nodeType||U(a)&&d(a)})}function e(a){return od(a)==W&&za(a.childNodes,function(a){return!U(a)||e(a)||!d(a)})}if(!U(a))throw Error("Argument to isShown must be of type Element");if(U(a,"BODY"))return!0;if(U(a,"OPTION")||U(a,"OPTGROUP"))return a=pb(a,function(a){return U(a,"SELECT")}),
!!a&&md(a,!0,c);var f=pd(a);if(f)return!!f.L&&0<f.rect.width&&0<f.rect.height&&md(f.L,b,c);if(U(a,"INPUT")&&"hidden"==a.type.toLowerCase()||U(a,"NOSCRIPT"))return!1;f=V(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=qd(a))&&d(a)?!e(a):!1}function rd(a){function b(a){if("none"==V(a,"display"))return!1;a=kd(a);return!a||b(a)}return md(a,!1,b)}var W="hidden";
function od(a){function b(a){function b(a){if(a==g)return!0;var d=V(a,"display");return oa(d,"inline")||"absolute"==c&&"static"==V(a,"position")?!1:!0}var c=V(a,"position");if("fixed"==c)return n=!0,a==g?null:g;for(a=kd(a);a&&!b(a);)a=kd(a);return a}function c(a){var b=a;if("visible"==l)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:V(b,"overflow-x"),y:V(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new fb(f)).a;
a=b.scrollingElement?b.scrollingElement:Ta||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=y&&$a("10")&&b.pageYOffset!=a.scrollTop?new cb(a.scrollLeft,a.scrollTop):new cb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new cb(a.scrollLeft,a.scrollTop);return a}var e=sd(a),f=A(a),g=f.documentElement,k=f.body,l=V(g,"overflow"),n;for(a=b(a);a;a=b(a)){var q=c(a);if("visible"!=q.x||"visible"!=q.y){var z=nd(a);if(0==z.width||0==z.height)return W;
var I=e.right<z.left,ja=e.bottom<z.top;if(I&&"hidden"==q.x||ja&&"hidden"==q.y)return W;if(I&&"visible"!=q.x||ja&&"visible"!=q.y){I=d(a);ja=e.bottom<z.top-I.y;if(e.right<z.left-I.x&&"visible"!=q.x||ja&&"visible"!=q.x)return W;e=od(a);return e==W?W:"scroll"}I=e.left>=z.left+z.width;z=e.top>=z.top+z.height;if(I&&"hidden"==q.x||z&&"hidden"==q.y)return W;if(I&&"visible"!=q.x||z&&"visible"!=q.y){if(n&&(q=d(a),e.left>=g.scrollWidth-q.x||e.right>=g.scrollHeight-q.y))return W;e=od(a);return e==W?W:"scroll"}}}return"none"}
function nd(a){var b=pd(a);if(b)return b.rect;if(U(a,"HTML"))return a=A(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new db(a.clientWidth,a.clientHeight),new T(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new T(0,0,0,0)}b=new T(c.left,c.top,c.right-c.left,c.bottom-c.top);y&&a.ownerDocument.body&&(a=A(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function pd(a){var b=U(a,"MAP");if(!b&&!U(a,"AREA"))return null;var c=b?a:U(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name&&(d=S.v('/descendant::*[@usemap = "#'+c.name+'"]',A(c)))&&(e=nd(d),!b&&"default"!=a.shape.toLowerCase())){var f=td(a);a=Math.min(Math.max(f.left,0),e.width);b=Math.min(Math.max(f.top,0),e.height);c=Math.min(f.width,e.width-a);f=Math.min(f.height,e.height-b);e=new T(a+e.left,b+e.top,c,f)}return{L:d,rect:e||new T(0,0,0,0)}}
function td(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new T(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new T(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new T(b,c,d-b,e-c)}return new T(0,0,0,0)}function sd(a){a=nd(a);return new fd(a.top,a.left+a.width,a.top+a.height,a.left)}
function ud(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function vd(a){var b=[];wd(a,b);var c=b;a=c.length;for(var b=Array(a),c=r(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=ud.call(void 0,c[d]));return ud(b.join("\n")).replace(/\xa0/g," ")}
function xd(a,b,c){if(U(a,"BR"))b.push("");else{var d=U(a,"TD"),e=V(a,"display"),f=!d&&!(0<=va(yd,e)),g=p(a.previousElementSibling)?a.previousElementSibling:hb(a.previousSibling),g=g?V(g,"display"):"",k=V(a,"float")||V(a,"cssFloat")||V(a,"styleFloat");!f||"run-in"==g&&"none"==k||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var l=rd(a),n=null,q=null;l&&(n=V(a,"white-space"),q=V(a,"text-transform"));u(a.childNodes,function(a){c(a,b,l,n,q)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||pa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function wd(a,b){xd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?zd(a,b,f,g):U(a)&&wd(a,b)})}var yd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function zd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";pa(c," ")&&oa(a," ")&&(a=a.substr(1));b.push(c+a)}
function qd(a){if(ed){if("relative"==V(a,"position"))return 1;a=V(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return Ad(a)}function Ad(a){var b=1,c=V(a,"opacity");c&&(b=Number(c));(a=kd(a))&&(b*=Ad(a));return b};var Bd={D:function(a){return!(!a.querySelectorAll||!a.querySelector)},v:function(a,b){if(!a)throw new v(32,"No class name specified");a=qa(a);if(-1!==a.indexOf(" "))throw new v(32,"Compound class names not permitted");if(Bd.D(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new v(32,"An invalid or illegal class name was specified");}var d=qb(eb(b),"*",a,b);return d.length?d[0]:null},w:function(a,b){if(!a)throw new v(32,"No class name specified");a=qa(a);if(-1!==a.indexOf(" "))throw new v(32,
"Compound class names not permitted");if(Bd.D(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new v(32,"An invalid or illegal class name was specified");}return qb(eb(b),"*",a,b)}};var Cd={v:function(a,b){if(!da(b.querySelector)&&y&&Yc(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new v(32,"No selector specified");a=qa(a);var c;try{c=b.querySelector(a)}catch(d){throw new v(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},w:function(a,b){if(!da(b.querySelectorAll)&&y&&Yc(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new v(32,"No selector specified");a=qa(a);try{return b.querySelectorAll(a)}catch(c){throw new v(32,
"An invalid or illegal selector was specified");}}};var Dd={D:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},v:function(a,b){var c=eb(b),d=r(a)?c.a.getElementById(a):a;if(!d)return null;if(hd(d,"id")==a&&ib(b,d))return d;c=qb(c,"*");return Aa(c,function(c){return hd(c,"id")==a&&ib(b,c)})},w:function(a,b){if(!a)return[];if(Dd.D(b,a))try{return b.querySelectorAll("#"+Dd.V(a))}catch(c){return[]}var d=qb(eb(b),"*",null,b);return wa(d,function(b){return hd(b,"id")==a})},V:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var X={},Ed={};X.R=function(a,b,c){var d;try{d=Cd.w("a",b)}catch(e){d=qb(eb(b),"A",null,b)}return Aa(d,function(b){b=vd(b);return c&&-1!=b.indexOf(a)||b==a})};X.M=function(a,b,c){var d;try{d=Cd.w("a",b)}catch(e){d=qb(eb(b),"A",null,b)}return wa(d,function(b){b=vd(b);return c&&-1!=b.indexOf(a)||b==a})};X.v=function(a,b){return X.R(a,b,!1)};X.w=function(a,b){return X.M(a,b,!1)};Ed.v=function(a,b){return X.R(a,b,!0)};Ed.w=function(a,b){return X.M(a,b,!0)};var Fd={v:function(a,b){if(""===a)throw new v(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},w:function(a,b){if(""===a)throw new v(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Gd={className:Bd,"class name":Bd,css:Cd,"css selector":Cd,id:Dd,linkText:X,"link text":X,name:{v:function(a,b){var c=qb(eb(b),"*",null,b);return Aa(c,function(b){return hd(b,"name")==a})},w:function(a,b){var c=qb(eb(b),"*",null,b);return wa(c,function(b){return hd(b,"name")==a})}},partialLinkText:Ed,"partial link text":Ed,tagName:Fd,"tag name":Fd,xpath:S};
function Hd(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Gd[c];if(d&&da(d.v))return d.v(a[c],b||la.document)}throw Error("Unsupported locator strategy: "+c);};Ta||Zc&&$c(3.6);y&&Yc(10);ub&&$c(4);function Id(a,b){this.A={};this.l=[];this.b=this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)Jd(this,arguments[d],arguments[d+1])}else if(a){var e;if(a instanceof Id)for(d=Kd(a),Ld(a),e=[],c=0;c<a.l.length;c++)e.push(a.A[a.l[c]]);else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)Jd(this,d[c],e[c])}}function Kd(a){Ld(a);return a.l.concat()}
Id.prototype.clear=function(){this.A={};this.b=this.a=this.l.length=0};function Ld(a){if(a.a!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];Object.prototype.hasOwnProperty.call(a.A,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.a!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],Object.prototype.hasOwnProperty.call(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}Id.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.A,a)?this.A[a]:b};
function Jd(a,b,c){Object.prototype.hasOwnProperty.call(a.A,b)||(a.a++,a.l.push(b),a.b++);a.A[b]=c}Id.prototype.forEach=function(a,b){for(var c=Kd(this),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};Id.prototype.clone=function(){return new Id(this)};var Md={};function Y(a,b,c){ea(a)&&(a=Sa?a.g:a.h);a=new Nd(a);!b||b in Md&&!c||(Md[b]={key:a,shift:!1},c&&(Md[c]={key:a,shift:!0}));return a}function Nd(a){this.code=a}Y(8);Y(9);Y(13);var Od=Y(16),Pd=Y(17),Qd=Y(18);Y(19);Y(20);Y(27);Y(32," ");Y(33);Y(34);Y(35);Y(36);Y(37);Y(38);Y(39);Y(40);Y(44);Y(45);Y(46);Y(48,"0",")");Y(49,"1","!");Y(50,"2","@");Y(51,"3","#");Y(52,"4","$");Y(53,"5","%");Y(54,"6","^");Y(55,"7","&");Y(56,"8","*");Y(57,"9","(");Y(65,"a","A");Y(66,"b","B");Y(67,"c","C");Y(68,"d","D");
Y(69,"e","E");Y(70,"f","F");Y(71,"g","G");Y(72,"h","H");Y(73,"i","I");Y(74,"j","J");Y(75,"k","K");Y(76,"l","L");Y(77,"m","M");Y(78,"n","N");Y(79,"o","O");Y(80,"p","P");Y(81,"q","Q");Y(82,"r","R");Y(83,"s","S");Y(84,"t","T");Y(85,"u","U");Y(86,"v","V");Y(87,"w","W");Y(88,"x","X");Y(89,"y","Y");Y(90,"z","Z");var Rd=Y(Va?{g:91,h:91}:Ua?{g:224,h:91}:{g:0,h:91});Y(Va?{g:92,h:92}:Ua?{g:224,h:93}:{g:0,h:92});Y(Va?{g:93,h:93}:Ua?{g:0,h:0}:{g:93,h:null});Y({g:96,h:96},"0");Y({g:97,h:97},"1");
Y({g:98,h:98},"2");Y({g:99,h:99},"3");Y({g:100,h:100},"4");Y({g:101,h:101},"5");Y({g:102,h:102},"6");Y({g:103,h:103},"7");Y({g:104,h:104},"8");Y({g:105,h:105},"9");Y({g:106,h:106},"*");Y({g:107,h:107},"+");Y({g:109,h:109},"-");Y({g:110,h:110},".");Y({g:111,h:111},"/");Y(144);Y(112);Y(113);Y(114);Y(115);Y(116);Y(117);Y(118);Y(119);Y(120);Y(121);Y(122);Y(123);Y({g:107,h:187},"=","+");Y(108,",");Y({g:109,h:189},"-","_");Y(188,",","<");Y(190,".",">");Y(191,"/","?");Y(192,"`","~");Y(219,"[","{");
Y(220,"\\","|");Y(221,"]","}");Y({g:59,h:186},";",":");Y(222,"'",'"');var Sd=new Id;Jd(Sd,1,Od);Jd(Sd,2,Pd);Jd(Sd,4,Qd);Jd(Sd,8,Rd);(function(a){var b=new Id;u(Kd(a),function(c){Jd(b,a.get(c).code,c)});return b})(Sd);Sa&&Yc(12);function Td(a){ma.call(this,a)}t(Td,ma);Ta||Sa&&Yc(3.5)||y&&Yc(8);var Ud={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Td("Illegal Index: "+a);if(b.length<=c)throw new Td("Index out of range: "+a);return[b[c]]},name:function(a,b){return wa(b,function(b){return gd(b,"name")==a})},value:function(a,b){return wa(b,function(b){return gd(b,"value")===a})}};function Vd(a,b){return(new RegExp(a)).test(b)}function Wd(a,b){return(new RegExp(a,"i")).test(b)}function Xd(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Yd={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Xd(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Xd(a))).test(b)},regex:Vd,regexi:Wd,regexpi:Wd,regexp:Vd};function Zd(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=Zd(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Vc.ba&&$c(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={X:function(a,b){return oa(a,"//")?Z.S(a,b):oa(a,"document.")?Z.J(a,b):Z.K(a,b)},T:function(a,b){return $d(b||A(la),function(b){return b.alt==a})},U:function(a,b){return $d(b||A(la),function(b){return b.className==a})},J:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},W:function(a,b){return Hd({id:a},b)},K:function(a,b){return Z.id(a,b)||Z.name(a,b)},o:function(a,b){var c=b||A(la);eb(c);var d;d=gb(document,"*",null,c);c=a.split(" ");for(c[0]="name="+c[0];c.length;){var e=
c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=Ud[d];if(!g)throw new Td("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},Z:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,k=g.$wdc_;k||(k=g.$wdc_={},k.N=ka());k.N||(k.N=ka());f=k;if(!(null!==f&&d in f))throw new v(10,"Element does not exist in cache");var l=f[d];if(null!==l&&"setInterval"in l){if(l.closed)throw delete f[d],new v(23,
"Window has been closed.");c=l}else{for(g=l;g;){if(g==e.documentElement){c=l;break a}g=g.parentNode}delete f[d];throw new v(10,"Element is no longer attached to the DOM");}}return c}catch(n){return null}},S:function(a,b){var c=pa(a,"/"),d={xpath:a};try{var e=Hd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Hd(d,b)}};Z.alt=Z.T;Z["class"]=Z.U;Z.dom=Z.J;Z.id=Z.W;Z.identifier=Z.K;Z.implicit=Z.X;
Z.link=function(a,b){for(var c=(b||A(la)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";Sa&&"1.8"<=Ya||Ta||y?g=Zd(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Ta)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");var g=f,f=qa(g),k=a,g="glob",l=/^([a-zA-Z-]+):(.*)/.exec(k);if(l){var n=l[1],l=l[2];Yd[n.toLowerCase()]&&(g=
n.toLowerCase(),k=l)}n=Yd[g];if(!n)throw new Td("Cannot find pattern matching strategy: "+g);"glob"==g?(0==k.indexOf("glob:")&&(k=k.substring(5)),n=Yd.glob):"exact"==g&&0==k.indexOf("exact:")&&(k=k.substring(6));k=ia(n,k);k.da=g;if(k(f))return e}return null};Z.name=Z.o;Z.stored=Z.Z;Z.xpath=Z.S;function ae(a,b,c,d){var e=Z[a];if(!e)throw new Td("Unrecognised locator type: '"+a+"'");c=e.call(null,b,c);if(null!=c)return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=ae(a,b,f,d.frames[e]),null!=c))return c}return null}function $d(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType){if(b(e))return e;if(e=$d(e,b))return e}}return null};aa("_",function(a){if(r(a)&&r(a)){var b;(b=a.match(/^([A-Za-z]+)=.+/))?(b=b[1].toLowerCase(),b={type:b,string:a.substring(b.length+1)}):(b={string:"",type:""},b.string=a,b.type=oa(a,"//")?"xpath":oa(a,"document.")?"dom":"identifier");var c=la||la;b=ae(b.type,b.string,c.document,c);if(null==b)throw new Td("Element "+a+" not found");a=b}if(!p(a.options))throw new Td("Specified element is not a Select (has no options)");for(b=0;b<a.options.length;b++)if(a.options[b].selected)return!0;return!1});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
