function(){return function(){var l,p=this;function aa(a){return void 0!==a}function ba(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&aa(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){return"function"==ca(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){ja=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return ja.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function r(a,b){function c(){}c.prototype=b.prototype;a.aa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Z=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ma=window;function na(a){if(Error.captureStackTrace)Error.captureStackTrace(this,na);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(na,Error);na.prototype.name="CustomError";var oa;function pa(a,b){return 0==a.lastIndexOf(b,0)}function qa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function sa(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",k=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var y=m.exec(h)||["","",""],H=n.exec(k)||["","",""];if(0==y[0].length&&0==H[0].length)break;c=ta(0==y[1].length?0:parseInt(y[1],10),0==H[1].length?0:parseInt(H[1],10))||ta(0==y[2].length,0==H[2].length)||ta(y[2],H[2])}while(0==c)}return c}function ta(a,b){return a<b?-1:a>b?1:0}
function ua(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var va=Array.prototype;function wa(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function t(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function xa(a,b){for(var c=a.length,d=[],e=0,f=q(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}function ya(a,b,c){var d=c;t(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function za(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Aa(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Ba(a,b){var c;a:{c=a.length;for(var d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:q(a)?a.charAt(c):a[c]}function Ca(a){return va.concat.apply(va,arguments)}
function Da(a,b,c){return 2>=arguments.length?va.slice.call(a,b):va.slice.call(a,b,c)};var Ea={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Fa="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ga=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ha=/^#(?:[0-9a-f]{3}){1,2}$/i,Ia=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ja=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function u(a,b){this.code=a;this.a=v[a]||Ka;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}r(u,Error);var Ka="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=Ka;v[30]=Ka;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=Ka;v[9]="unknown command";u.prototype.toString=function(){return this.name+": "+this.message};var w;a:{var La=p.navigator;if(La){var Ma=La.userAgent;if(Ma){w=Ma;break a}}w=""}function x(a){return-1!=w.indexOf(a)};function Na(){return x("Opera")||x("OPR")}function Oa(){return(x("Chrome")||x("CriOS"))&&!Na()&&!x("Edge")};function Pa(){return x("iPhone")&&!x("iPod")&&!x("iPad")};var Qa=Na(),z=x("Trident")||x("MSIE"),Ra=x("Edge"),Sa=x("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge"))&&!(x("Trident")||x("MSIE"))&&!x("Edge"),Ta=-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge");function Ua(){var a=w;if(Sa)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ra)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ta)return/WebKit\/(\S+)/.exec(a)}function Va(){var a=p.document;return a?a.documentMode:void 0}
var Wa=function(){if(Qa&&p.opera){var a;var b=p.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ua())&&(a=b?b[1]:"");return z&&(b=Va(),b>parseFloat(a))?String(b):a}(),Xa={};function Ya(a){return Xa[a]||(Xa[a]=0<=sa(Wa,a))}var Za=p.document,$a=Za&&z?Va()||("CSS1Compat"==Za.compatMode?parseInt(Wa,10):5):void 0;!Sa&&!z||z&&9<=$a||Sa&&Ya("1.9.1");z&&Ya("9");function ab(a,b){this.x=aa(a)?a:0;this.y=aa(b)?b:0}l=ab.prototype;l.clone=function(){return new ab(this.x,this.y)};l.toString=function(){return"("+this.x+", "+this.y+")"};l.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};l.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};l.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};l.scale=function(a,b){var c=da(b)?b:a;this.x*=a;this.y*=c;return this};function bb(a,b){this.width=a;this.height=b}l=bb.prototype;l.clone=function(){return new bb(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
l.scale=function(a,b){var c=da(b)?b:a;this.width*=a;this.height*=c;return this};function A(a){return a?new cb(B(a)):oa||(oa=new cb)}
function db(a,b,c,d){a=d||a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;g=b[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=wa(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;return a}return b}
function eb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function fb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function gb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z&&!(9<=$a)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?hb(a,b):!c&&fb(e,b)?-1*ib(a,b):!d&&fb(f,a)?ib(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(p.Range.START_TO_END,d)}function ib(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return hb(d,a)}function hb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var jb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},kb={IMG:" ",BR:"\n"};
function lb(a,b,c){if(!(a.nodeName in jb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in kb)b.push(kb[a.nodeName]);else for(a=a.firstChild;a;)lb(a,b,c),a=a.nextSibling}function mb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function cb(a){this.a=a||p.document||document}function nb(a,b,c,d){return db(a.a,b,c,d)};var ob=x("Firefox"),pb=Pa()||x("iPod"),qb=x("iPad"),rb=x("Android")&&!(Oa()||x("Firefox")||Na()||x("Silk")),sb=Oa(),tb=x("Safari")&&!(Oa()||x("Coast")||Na()||x("Edge")||x("Silk")||x("Android"))&&!(Pa()||x("iPad")||x("iPod"));/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function ub(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var vb=z&&!(9<=$a),wb=z&&!(8<=$a);function xb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function yb(a,b){var c=wb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new xb(b,a,b.nodeName,c)};function zb(a){this.b=a;this.a=0}function Ab(a){a=a.match(Bb);for(var b=0;b<a.length;b++)Cb.test(a[b])&&a.splice(b,1);return new zb(a)}var Bb=RegExp("\\$?(?:(?![0-9-])[\\w-]+:)?(?![0-9-])[\\w-]+|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Cb=/^\s/;function C(a,b){return a.b[a.a+(b||0)]}function D(a){return a.b[a.a++]}function Db(a){return a.b.length<=a.a};function E(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(vb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),vb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Eb(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}wb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Fb(a,b,c,d,e){return(vb?Gb:Hb).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new F)}
function Gb(a,b,c,d,e){if(a instanceof Ib||8==a.a||c&&null===a.a){var f=b.all;if(!f)return e;a=Jb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)Eb(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||G(e,b);return e}Kb(a,b,c,d,e);return e}
function Hb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!z?(b=b.getElementsByName(d),t(b,function(b){a.b(b)&&G(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),t(b,function(b){b.className==d&&a.b(b)&&G(e,b)})):a instanceof I?Kb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),t(b,function(a){Eb(a,c,d)&&G(e,a)}));return e}
function Lb(a,b,c,d,e){var f;if((a instanceof Ib||8==a.a||c&&null===a.a)&&(f=b.childNodes)){var g=Jb(a);if("*"!=g&&(f=xa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=xa(f,function(a){return Eb(a,c,d)}));t(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||G(e,a)});return e}return Mb(a,b,c,d,e)}function Mb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Eb(b,c,d)&&a.b(b)&&G(e,b);return e}
function Kb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Eb(b,c,d)&&a.b(b)&&G(e,b),Kb(a,b,c,d,e)}function Jb(a){if(a instanceof I){if(8==a.a)return"!";if(null===a.a)return"*"}return a.f()};function F(){this.b=this.a=null;this.l=0}function Nb(a){this.node=a;this.a=this.b=null}function Ob(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f=null,g=0;c&&d;){var f=c.node,h=d.node;f==h||f instanceof xb&&h instanceof xb&&f.a==h.a?(f=c,c=c.a,d=d.a):0<gb(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.l=g;return a}
F.prototype.unshift=function(a){a=new Nb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.l++};function G(a,b){var c=new Nb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.l++}function Pb(a){return(a=a.a)?a.node:null}F.prototype.f=function(){var a=Pb(this);return a?E(a):""};function Qb(a,b){return new Rb(a,!!b)}function Rb(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function J(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.c?b.b:b.a;return c.node};function K(a){this.i=a;this.b=this.g=!1;this.f=null}function L(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Sb(a,b){a.g=b}function Tb(a,b){a.b=b}function M(a,b){var c=a.a(b);return c instanceof F?+c.f():+c}function N(a,b){var c=a.a(b);return c instanceof F?c.f():""+c}function Ub(a,b){var c=a.a(b);return c instanceof F?!!c.l:!!c};function Vb(a,b,c){K.call(this,a.i);this.c=a;this.h=b;this.u=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==Wb&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,v:b}):this.f={name:b.f.name,v:c})}r(Vb,K);
function Xb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof F&&c instanceof F){e=Qb(b);for(d=J(e);d;d=J(e))for(b=Qb(c),f=J(b);f;f=J(b))if(a(E(d),E(f)))return!0;return!1}if(b instanceof F||c instanceof F){b instanceof F?e=b:(e=c,c=b);e=Qb(e);b=typeof c;for(d=J(e);d;d=J(e)){switch(b){case "number":d=+E(d);break;case "boolean":d=!!E(d);break;case "string":d=E(d);break;default:throw Error("Illegal primitive type for comparison.");}if(a(d,c))return!0}return!1}return e?"boolean"==typeof b||"boolean"==
typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Vb.prototype.a=function(a){return this.c.m(this.h,this.u,a)};Vb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+L(this.h);return a+=L(this.u)};function Yb(a,b,c,d){this.a=a;this.L=b;this.i=c;this.m=d}Yb.prototype.toString=function(){return this.a};var Zb={};
function O(a,b,c,d){if(Zb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Yb(a,b,c,d);return Zb[a.toString()]=a}O("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});O("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});O("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});O("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});O("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});O("<",4,2,function(a,b,c){return Xb(function(a,b){return a<b},a,b,c)});
O(">",4,2,function(a,b,c){return Xb(function(a,b){return a>b},a,b,c)});O("<=",4,2,function(a,b,c){return Xb(function(a,b){return a<=b},a,b,c)});O(">=",4,2,function(a,b,c){return Xb(function(a,b){return a>=b},a,b,c)});var Wb=O("=",3,2,function(a,b,c){return Xb(function(a,b){return a==b},a,b,c,!0)});O("!=",3,2,function(a,b,c){return Xb(function(a,b){return a!=b},a,b,c,!0)});O("and",2,2,function(a,b,c){return Ub(a,c)&&Ub(b,c)});O("or",1,2,function(a,b,c){return Ub(a,c)||Ub(b,c)});function $b(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");K.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}r($b,K);$b.prototype.a=function(a){a=this.c.a(a);return ac(this.h,a)};$b.prototype.toString=function(){var a;a="Filter:"+L(this.c);return a+=L(this.h)};function bc(a,b){if(b.length<a.K)throw Error("Function "+a.j+" expects at least"+a.K+" arguments, "+b.length+" given");if(null!==a.B&&b.length>a.B)throw Error("Function "+a.j+" expects at most "+a.B+" arguments, "+b.length+" given");a.X&&t(b,function(b,d){if(4!=b.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});K.call(this,a.i);this.h=a;this.c=b;Sb(this,a.g||za(b,function(a){return a.g}));Tb(this,a.W&&!b.length||a.U&&!!b.length||za(b,function(a){return a.b}))}
r(bc,K);bc.prototype.a=function(a){return this.h.m.apply(null,Ca(a,this.c))};bc.prototype.toString=function(){var a="Function: "+this.h;if(this.c.length)var b=ya(this.c,function(a,b){return a+L(b)},"Arguments:"),a=a+L(b);return a};function cc(a,b,c,d,e,f,g,h,k){this.j=a;this.i=b;this.g=c;this.W=d;this.U=e;this.m=f;this.K=g;this.B=aa(h)?h:g;this.X=!!k}cc.prototype.toString=function(){return this.j};var dc={};
function P(a,b,c,d,e,f,g,h){if(dc.hasOwnProperty(a))throw Error("Function already created: "+a+".");dc[a]=new cc(a,b,c,d,!1,e,f,g,h)}P("boolean",2,!1,!1,function(a,b){return Ub(b,a)},1);P("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);P("concat",3,!1,!1,function(a,b){return ya(Da(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);P("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);P("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
P("false",2,!1,!1,function(){return!1},0);P("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);P("id",4,!1,!1,function(a,b){function c(a){if(vb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ba(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=N(b,a).split(/\s+/),f=[];t(d,function(a){a=c(a);!a||0<=wa(f,a)||f.push(a)});f.sort(gb);var g=new F;t(f,function(a){G(g,a)});return g},1);
P("lang",2,!1,!1,function(){return!1},1);P("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);P("local-name",3,!1,!0,function(a,b){var c=b?Pb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);P("name",3,!1,!0,function(a,b){var c=b?Pb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);P("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
P("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);P("not",2,!1,!1,function(a,b){return!Ub(b,a)},1);P("number",1,!1,!0,function(a,b){return b?M(b,a):+E(a.a)},0,1);P("position",1,!0,!1,function(a){return a.b},0);P("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);P("starts-with",2,!1,!1,function(a,b,c){return pa(N(b,a),N(c,a))},2);P("string",3,!1,!0,function(a,b){return b?N(b,a):E(a.a)},0,1);
P("string-length",1,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).length},0,1);P("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);if(Infinity==d)return a.substring(e);b=Math.round(d);return a.substring(e,c+b)},2,3);P("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
P("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);P("sum",1,!1,!1,function(a,b){for(var c=Qb(b.a(a)),d=0,e=J(c);e;e=J(c))d+=+E(e);return d},1,1,!0);P("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);P("true",2,!1,!1,function(){return!0},0);function I(a,b){this.h=a;this.c=aa(b)?b:null;this.a=null;switch(a){case "comment":this.a=8;break;case "text":this.a=3;break;case "processing-instruction":this.a=7;break;case "node":break;default:throw Error("Unexpected argument");}}function ec(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}I.prototype.b=function(a){return null===this.a||this.a==a.nodeType};I.prototype.f=function(){return this.h};
I.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=L(this.c));return a};function fc(a){K.call(this,3);this.c=a.substring(1,a.length-1)}r(fc,K);fc.prototype.a=function(){return this.c};fc.prototype.toString=function(){return"Literal: "+this.c};function Ib(a,b){this.j=a.toLowerCase();this.c=b?b.toLowerCase():"http://www.w3.org/1999/xhtml"}Ib.prototype.b=function(a){var b=a.nodeType;return 1!=b&&2!=b?!1:"*"!=this.j&&this.j!=a.nodeName.toLowerCase()?!1:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ib.prototype.f=function(){return this.j};Ib.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.j};function gc(a){K.call(this,1);this.c=a}r(gc,K);gc.prototype.a=function(){return this.c};gc.prototype.toString=function(){return"Number: "+this.c};function hc(a,b){K.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.A||c.c!=ic||(c=c.u,"*"!=c.f()&&(this.f={name:c.f(),v:null}))}}r(hc,K);function jc(){K.call(this,4)}r(jc,K);jc.prototype.a=function(a){var b=new F;a=a.a;9==a.nodeType?G(b,a):G(b,a.ownerDocument);return b};jc.prototype.toString=function(){return"Root Helper Expression"};function kc(){K.call(this,4)}r(kc,K);kc.prototype.a=function(a){var b=new F;G(b,a.a);return b};kc.prototype.toString=function(){return"Context Helper Expression"};
function lc(a){return"/"==a||"//"==a}hc.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof F))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=Qb(b,e.c.a),g;if(e.g||e.c!=mc)if(e.g||e.c!=nc)for(g=J(f),b=e.a(new ub(g));null!=(g=J(f));)g=e.a(new ub(g)),b=Ob(b,g);else g=J(f),b=e.a(new ub(g));else{for(g=J(f);(b=J(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new ub(g))}}return b};
hc.prototype.toString=function(){var a;a="Path Expression:"+L(this.h);if(this.c.length){var b=ya(this.c,function(a,b){return a+L(b)},"Steps:");a+=L(b)}return a};function oc(a,b){this.a=a;this.b=!!b}
function ac(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=Qb(b),f=b.l,g,h=0;g=J(e);h++){var k=a.b?f-h:h+1;g=d.a(new ub(g,k,f));if("number"==typeof g)k=k==g;else if("string"==typeof g||"boolean"==typeof g)k=!!g;else if(g instanceof F)k=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;g=k.f;var m=k.a;if(!m)throw Error("Next must be called at least once before remove.");var n=m.b,m=m.a;n?n.a=m:g.a=m;m?m.b=n:g.b=n;g.l--;k.a=null}}return b}
oc.prototype.toString=function(){return ya(this.a,function(a,b){return a+L(b)},"Predicates:")};function pc(a,b,c,d){K.call(this,4);this.c=a;this.u=b;this.h=c||new oc([]);this.A=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=vb?a.toLowerCase():a,this.f={name:a,v:b.v});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}r(pc,K);
pc.prototype.a=function(a){var b=a.a,c=null,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.v?N(c.v,a):null,f=1);if(this.A)if(this.g||this.c!=qc)if(a=Qb((new pc(rc,new I("node"))).a(a)),b=J(a))for(c=this.m(b,d,e,f);null!=(b=J(a));)c=Ob(c,this.m(b,d,e,f));else c=new F;else c=Fb(this.u,b,d,e),c=ac(this.h,c,f);else c=this.m(a.a,d,e,f);return c};pc.prototype.m=function(a,b,c,d){a=this.c.f(this.u,a,b,c);return a=ac(this.h,a,d)};
pc.prototype.toString=function(){var a;a="Step:"+L("Operator: "+(this.A?"//":"/"));this.c.j&&(a+=L("Axis: "+this.c));a+=L(this.u);if(this.h.a.length){var b=ya(this.h.a,function(a,b){return a+L(b)},"Predicates:");a+=L(b)}return a};function sc(a,b,c,d){this.j=a;this.f=b;this.a=c;this.b=d}sc.prototype.toString=function(){return this.j};var tc={};function Q(a,b,c,d){if(tc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new sc(a,b,c,!!d);return tc[a]=b}
Q("ancestor",function(a,b){for(var c=new F,d=b;d=d.parentNode;)a.b(d)&&c.unshift(d);return c},!0);Q("ancestor-or-self",function(a,b){var c=new F,d=b;do a.b(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var ic=Q("attribute",function(a,b){var c=new F,d=a.f();if("style"==d&&b.style&&vb)return G(c,new xb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof I&&null===a.a||"*"==d)for(var d=0,f;f=e[d];d++)vb?f.nodeValue&&G(c,yb(b,f)):G(c,f);else(f=e.getNamedItem(d))&&(vb?f.nodeValue&&G(c,yb(b,f)):G(c,f));return c},!1),qc=Q("child",function(a,b,c,d,e){return(vb?Lb:Mb).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new F)},!1,!0);Q("descendant",Fb,!1,!0);
var rc=Q("descendant-or-self",function(a,b,c,d){var e=new F;Eb(b,c,d)&&a.b(b)&&G(e,b);return Fb(a,b,c,d,e)},!1,!0),mc=Q("following",function(a,b,c,d){var e=new F;do for(var f=b;f=f.nextSibling;)Eb(f,c,d)&&a.b(f)&&G(e,f),e=Fb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new F,d=b;d=d.nextSibling;)a.b(d)&&G(c,d);return c},!1);Q("namespace",function(){return new F},!1);
var uc=Q("parent",function(a,b){var c=new F;if(9==b.nodeType)return c;if(2==b.nodeType)return G(c,b.ownerElement),c;var d=b.parentNode;a.b(d)&&G(c,d);return c},!1),nc=Q("preceding",function(a,b,c,d){var e=new F,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var k=[];for(b=f[g];b=b.previousSibling;)k.unshift(b);for(var m=0,n=k.length;m<n;m++)b=k[m],Eb(b,c,d)&&a.b(b)&&G(e,b),e=Fb(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new F,d=b;d=d.previousSibling;)a.b(d)&&c.unshift(d);return c},!0);var vc=Q("self",function(a,b){var c=new F;a.b(b)&&G(c,b);return c},!1);function wc(a){K.call(this,1);this.c=a;this.g=a.g;this.b=a.b}r(wc,K);wc.prototype.a=function(a){return-M(this.c,a)};wc.prototype.toString=function(){return"Unary Expression: -"+L(this.c)};function xc(a){K.call(this,4);this.c=a;Sb(this,za(this.c,function(a){return a.g}));Tb(this,za(this.c,function(a){return a.b}))}r(xc,K);xc.prototype.a=function(a){var b=new F;t(this.c,function(c){c=c.a(a);if(!(c instanceof F))throw Error("Path expression must evaluate to NodeSet.");b=Ob(b,c)});return b};xc.prototype.toString=function(){return ya(this.c,function(a,b){return a+L(b)},"Union Expression:")};function yc(a,b){this.a=a;this.b=b}function Bc(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=Cc(a);var d=D(a.a);if(!d)break;var e=(d=Zb[d]||null)&&d.L;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].L;)b=new Vb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Vb(c.pop(),c.pop(),b);return b}function R(a,b){if(Db(a.a))throw Error(b);}function Dc(a,b){var c=D(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Ec(a){a=D(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Fc(a){a=D(a.a);if(2>a.length)throw Error("Unclosed literal string");return new fc(a)}function Gc(a){var b=D(a.a),c=b.indexOf(":");if(-1==c)return new Ib(b);var d=b.substring(0,c);a=a.b(d);if(!a)throw Error("Namespace prefix not declared: "+d);b=b.substr(c+1);return new Ib(b,a)}
function Hc(a){var b,c=[],d;if(lc(C(a.a))){b=D(a.a);d=C(a.a);if("/"==b&&(Db(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new jc;d=new jc;R(a,"Missing next location step.");b=Ic(a,b);c.push(b)}else{a:{b=C(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":D(a.a);b=Bc(a);R(a,'unclosed "("');Dc(a,")");break;case '"':case "'":b=Fc(a);break;default:if(isNaN(+b))if(!ec(b)&&/(?![0-9])[\w]/.test(d)&&"("==C(a.a,1)){b=D(a.a);
b=dc[b]||null;D(a.a);for(d=[];")"!=C(a.a);){R(a,"Missing function argument list.");d.push(Bc(a));if(","!=C(a.a))break;D(a.a)}R(a,"Unclosed function argument list.");Ec(a);b=new bc(b,d)}else{b=null;break a}else b=new gc(+D(a.a))}"["==C(a.a)&&(d=new oc(Jc(a)),b=new $b(b,d))}if(b)if(lc(C(a.a)))d=b;else return b;else b=Ic(a,"/"),d=new kc,c.push(b)}for(;lc(C(a.a));)b=D(a.a),R(a,"Missing next location step."),b=Ic(a,b),c.push(b);return new hc(d,c)}
function Ic(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==C(a.a))return d=new pc(vc,new I("node")),D(a.a),d;if(".."==C(a.a))return d=new pc(uc,new I("node")),D(a.a),d;var f;if("@"==C(a.a))f=ic,D(a.a),R(a,"Missing attribute name");else if("::"==C(a.a,1)){if(!/(?![0-9])[\w]/.test(C(a.a).charAt(0)))throw Error("Bad token: "+D(a.a));c=D(a.a);f=tc[c]||null;if(!f)throw Error("No axis with name: "+c);D(a.a);R(a,"Missing node name")}else f=qc;c=C(a.a);if(/(?![0-9])[\w]/.test(c.charAt(0)))if("("==
C(a.a,1)){if(!ec(c))throw Error("Invalid node type: "+c);c=D(a.a);if(!ec(c))throw Error("Invalid type name: "+c);Dc(a,"(");R(a,"Bad nodetype");e=C(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Fc(a);R(a,"Bad nodetype");Ec(a);c=new I(c,g)}else c=Gc(a);else if("*"==c)c=Gc(a);else throw Error("Bad token: "+D(a.a));e=new oc(Jc(a),f.a);return d||new pc(f,c,e,"//"==b)}
function Jc(a){for(var b=[];"["==C(a.a);){D(a.a);R(a,"Missing predicate expression.");var c=Bc(a);b.push(c);R(a,"Unclosed predicate expression.");Dc(a,"]")}return b}function Cc(a){if("-"==C(a.a))return D(a.a),new wc(Cc(a));var b=Hc(a);if("|"!=C(a.a))a=b;else{for(b=[b];"|"==D(a.a);)R(a,"Missing next union location path."),b.push(Hc(a));a.a.a--;a=new xc(b)}return a};function Kc(a){switch(a.nodeType){case 1:return ka(Lc,a);case 9:return Kc(a.documentElement);case 11:case 10:case 6:case 12:return Mc;default:return a.parentNode?Kc(a.parentNode):Mc}}function Mc(){return null}function Lc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Lc(a.parentNode,b):null};function Nc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Ab(a);if(Db(c))throw Error("Invalid XPath expression.");b?ea(b)||(b=ja(b.lookupNamespaceURI,b)):b=function(){return null};var d=Bc(new yc(c,b));if(!Db(c))throw Error("Bad token: "+D(c));this.evaluate=function(a,b){var c=d.a(new ub(a));return new S(c,b)}}
function S(a,b){if(0==b)if(a instanceof F)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof F))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof F?a.f():""+a;break;case 1:this.numberValue=a instanceof F?+a.f():+a;break;case 3:this.booleanValue=a instanceof F?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var d=
Qb(a);c=[];for(var e=J(d);e;e=J(d))c.push(e instanceof xb?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:d=Pb(a);this.singleNodeValue=d instanceof xb?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}S.ANY_TYPE=0;S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function Oc(a){this.lookupNamespaceURI=Kc(a)}
function Pc(a){a=a||p;var b=a.document;b.evaluate||(a.XPathResult=S,b.evaluate=function(a,b,e,f){return(new Nc(a,e)).evaluate(b,f)},b.createExpression=function(a,b){return new Nc(a,b)},b.createNSResolver=function(a){return new Oc(a)})}ba("wgxpath.install",Pc);var T={};T.C=function(){var a={ba:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
T.m=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(z||rb)&&Pc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):T.C;if(z&&!Ya(7))return d.evaluate.call(d,b,a,e,c,null);if(!z||9<=$a){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var k=g[h],m=k.namespaceURI;if(m&&!f[m]){var n=k.lookupPrefix(m);if(!n){var y=m.match(".*/(\\w+)/?$");y?n=y[1]:n="xhtml"}f[m]=n}}var H={},ia;for(ia in f)H[f[ia]]=ia;e=function(a){return H[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(zc){if("TypeError"===zc.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):T.C,d.evaluate(b,a,e,c,null);throw zc;}}catch(Ac){if(!Sa||"NS_ERROR_ILLEGAL_VALUE"!=Ac.name)throw new u(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Ac);}};T.D=function(a,b){if(!a||1!=a.nodeType)throw new u(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
T.o=function(a,b){var c=function(){var c=T.m(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||T.D(c,a);return c};
T.s=function(a,b){var c=function(){var c=T.m(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();t(c,function(b){T.D(b,a)});return c};function Qc(a){return(a=a.exec(w))?a[1]:""}var Rc=function(){if(ob)return Qc(/Firefox\/([0-9.]+)/);if(z||Ra||Qa)return Wa;if(sb)return Qc(/Chrome\/([0-9.]+)/);if(tb&&!(Pa()||x("iPad")||x("iPod")))return Qc(/Version\/([0-9.]+)/);if(pb||qb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(w))return a[1]+"."+a[2]}else if(rb)return(a=Qc(/Android\s+([0-9.]+)/))?a:Qc(/Version\/([0-9.]+)/);return""}();var Sc={},Tc,Uc;function Vc(a){return Wc?Tc(a):z?0<=sa($a,a):Ya(a)}function Xc(a){return Wc?Uc(a):rb?0<=sa(Yc,a):0<=sa(Rc,a)}
var Wc=function(){if(!Sa)return!1;var a=p.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(b){return!1}var c=a.classes,a=a.interfaces,d=c["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),c=c["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),e=c.platformVersion,f=c.version;Tc=function(a){return 0<=d.compare(e,""+a)};Uc=function(a){return 0<=d.compare(f,""+a)};return!0}(),Zc;if(rb){var $c=/Android\s+([0-9\.]+)/.exec(w);Zc=$c?$c[1]:"0"}else Zc="0";
var Yc=Zc,ad=z&&!(8<=$a),bd=z&&!(9<=$a);rb&&Xc(2.3);rb&&Xc(4);tb&&Xc(6);function cd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=cd.prototype;l.clone=function(){return new cd(this.top,this.right,this.bottom,this.left)};l.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};l.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function U(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}l=U.prototype;l.clone=function(){return new U(this.left,this.top,this.width,this.height)};l.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};l.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
l.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};l.scale=function(a,b){var c=da(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function V(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}function dd(a,b){var c;if(c=ad&&"value"==b&&V(a,"OPTION"))c=null===ed(a,"value");c?(c=[],lb(a,c,!1),c=c.join("")):c=a[b];return c}var fd=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function gd(a){var b=[];t(a.split(fd),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function ed(a,b){b=b.toLowerCase();if("style"==b)return gd(a.style.cssText);if(ad&&"value"==b&&V(a,"INPUT"))return a.value;if(bd&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}
function hd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return V(a)?a:null}
function W(a,b){var c=ua(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=bd?"styleFloat":"cssFloat";var d;a:{d=c;var e=B(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||id(a,c);if(null===d)d=null;else if(0<=wa(Fa,c)){b:{var f=d.match(Ia);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ja))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Ea[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Ga,"#$1$1$2$2$3$3")),!Ha.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function id(a,b){var c=a.currentStyle||a.style,d=c[b];!aa(d)&&ea(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?aa(d)?d:null:(c=hd(a))?id(c,b):null}
function jd(a,b,c){function d(a){var b=kd(a);return 0<b.height&&0<b.width?!0:V(a,"PATH")&&(0<b.height||0<b.width)?(a=W(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=W(a,"overflow")&&za(a.childNodes,function(a){return 3==a.nodeType||V(a)&&d(a)})}function e(a){return ld(a)==X&&Aa(a.childNodes,function(a){return!V(a)||e(a)||!d(a)})}if(!V(a))throw Error("Argument to isShown must be of type Element");if(V(a,"BODY"))return!0;if(V(a,"OPTION")||V(a,"OPTGROUP"))return a=mb(a,function(a){return V(a,"SELECT")}),
!!a&&jd(a,!0,c);var f=md(a);if(f)return!!f.H&&0<f.rect.width&&0<f.rect.height&&jd(f.H,b,c);if(V(a,"INPUT")&&"hidden"==a.type.toLowerCase()||V(a,"NOSCRIPT"))return!1;f=W(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=nd(a))&&d(a)?!e(a):!1}function od(a){function b(a){if("none"==W(a,"display"))return!1;a=hd(a);return!a||b(a)}return jd(a,!1,b)}var X="hidden";
function ld(a){function b(a){function b(a){if(a==g)return!0;var d=W(a,"display");return pa(d,"inline")||"absolute"==c&&"static"==W(a,"position")?!1:!0}var c=W(a,"position");if("fixed"==c)return m=!0,a==g?null:g;for(a=hd(a);a&&!b(a);)a=hd(a);return a}function c(a){var b=a;if("visible"==k)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:W(b,"overflow-x"),y:W(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new cb(f)).a;
a=b.scrollingElement?b.scrollingElement:Ta||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=z&&Ya("10")&&b.pageYOffset!=a.scrollTop?new ab(a.scrollLeft,a.scrollTop):new ab(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new ab(a.scrollLeft,a.scrollTop);return a}var e=pd(a),f=B(a),g=f.documentElement,h=f.body,k=W(g,"overflow"),m;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var y=kd(a);if(0==y.width||0==y.height)return X;
var H=e.right<y.left,ia=e.bottom<y.top;if(H&&"hidden"==n.x||ia&&"hidden"==n.y)return X;if(H&&"visible"!=n.x||ia&&"visible"!=n.y){H=d(a);ia=e.bottom<y.top-H.y;if(e.right<y.left-H.x&&"visible"!=n.x||ia&&"visible"!=n.x)return X;e=ld(a);return e==X?X:"scroll"}H=e.left>=y.left+y.width;y=e.top>=y.top+y.height;if(H&&"hidden"==n.x||y&&"hidden"==n.y)return X;if(H&&"visible"!=n.x||y&&"visible"!=n.y){if(m&&(n=d(a),e.left>=g.scrollWidth-n.x||e.right>=g.scrollHeight-n.y))return X;e=ld(a);return e==X?X:"scroll"}}}return"none"}
function kd(a){var b=md(a);if(b)return b.rect;if(V(a,"HTML"))return a=B(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new bb(a.clientWidth,a.clientHeight),new U(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new U(0,0,0,0)}b=new U(c.left,c.top,c.right-c.left,c.bottom-c.top);z&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function md(a){var b=V(a,"MAP");if(!b&&!V(a,"AREA"))return null;var c=b?a:V(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name&&(d=T.o('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=kd(d),!b&&"default"!=a.shape.toLowerCase())){var f=qd(a);a=Math.min(Math.max(f.left,0),e.width);b=Math.min(Math.max(f.top,0),e.height);c=Math.min(f.width,e.width-a);f=Math.min(f.height,e.height-b);e=new U(a+e.left,b+e.top,c,f)}return{H:d,rect:e||new U(0,0,0,0)}}
function qd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new U(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new U(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new U(b,c,d-b,e-c)}return new U(0,0,0,0)}function pd(a){a=kd(a);return new cd(a.top,a.left+a.width,a.top+a.height,a.left)}
function rd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function sd(a){var b=[];td(a,b);var c=b;a=c.length;for(var b=Array(a),c=q(c)?c.split(""):c,d=0;d<a;d++)d in c&&(b[d]=rd.call(void 0,c[d]));return rd(b.join("\n")).replace(/\xa0/g," ")}
function ud(a,b,c){if(V(a,"BR"))b.push("");else{var d=V(a,"TD"),e=W(a,"display"),f=!d&&!(0<=wa(vd,e)),g=aa(a.previousElementSibling)?a.previousElementSibling:eb(a.previousSibling),g=g?W(g,"display"):"",h=W(a,"float")||W(a,"cssFloat")||W(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var k=od(a),m=null,n=null;k&&(m=W(a,"white-space"),n=W(a,"text-transform"));t(a.childNodes,function(a){c(a,b,k,m,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||qa(a," ")||
(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function td(a,b){ud(a,b,function(a,b,e,f,g){3==a.nodeType&&e?wd(a,b,f,g):V(a)&&td(a,b)})}var vd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function wd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";qa(c," ")&&pa(a," ")&&(a=a.substr(1));b.push(c+a)}
function nd(a){if(bd){if("relative"==W(a,"position"))return 1;a=W(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return xd(a)}function xd(a){var b=1,c=W(a,"opacity");c&&(b=Number(c));(a=hd(a))&&(b*=xd(a));return b};z&&Vc(10);rb&&Xc(4);function yd(a,b,c){this.a=a;this.b=b;this.f=c}yd.prototype.create=function(a){a=B(a);bd&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.a,this.b,this.f));return a};yd.prototype.toString=function(){return this.a};var zd=new yd("change",!0,!1),Ad=new yd("focus",!1,!1),Bd=new yd("select",!0,!1);function Cd(a,b){var c=b.create(a,void 0);"isTrusted"in c||(c.isTrusted=!1);bd&&a.fireEvent?a.fireEvent("on"+b.a,c):a.dispatchEvent(c)};function Dd(a){na.call(this,a)}r(Dd,na);Ta||Sa&&Vc(3.5)||z&&Vc(8);var Ed={w:function(a){return!(!a.querySelectorAll||!a.querySelector)},o:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,"Compound class names not permitted");if(Ed.w(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new u(32,"An invalid or illegal class name was specified");}var d=nb(A(b),"*",a,b);return d.length?d[0]:null},s:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,
"Compound class names not permitted");if(Ed.w(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new u(32,"An invalid or illegal class name was specified");}return nb(A(b),"*",a,b)}};var Fd={o:function(a,b){if(!ea(b.querySelector)&&z&&Vc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);var c;try{c=b.querySelector(a)}catch(d){throw new u(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},s:function(a,b){if(!ea(b.querySelectorAll)&&z&&Vc(8)&&!fa(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);try{return b.querySelectorAll(a)}catch(c){throw new u(32,
"An invalid or illegal selector was specified");}}};var Gd={w:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},o:function(a,b){var c=A(b),d=q(a)?c.a.getElementById(a):a;if(!d)return null;if(ed(d,"id")==a&&fb(b,d))return d;c=nb(c,"*");return Ba(c,function(c){return ed(c,"id")==a&&fb(b,c)})},s:function(a,b){if(!a)return[];if(Gd.w(b,a))try{return b.querySelectorAll("#"+Gd.R(a))}catch(c){return[]}var d=nb(A(b),"*",null,b);return xa(d,function(b){return ed(b,"id")==a})},R:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Y={},Hd={};Y.M=function(a,b,c){var d;try{d=Fd.s("a",b)}catch(e){d=nb(A(b),"A",null,b)}return Ba(d,function(b){b=sd(b);return c&&-1!=b.indexOf(a)||b==a})};Y.I=function(a,b,c){var d;try{d=Fd.s("a",b)}catch(e){d=nb(A(b),"A",null,b)}return xa(d,function(b){b=sd(b);return c&&-1!=b.indexOf(a)||b==a})};Y.o=function(a,b){return Y.M(a,b,!1)};Y.s=function(a,b){return Y.I(a,b,!1)};Hd.o=function(a,b){return Y.M(a,b,!0)};Hd.s=function(a,b){return Y.I(a,b,!0)};var Id={o:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},s:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Jd={className:Ed,"class name":Ed,css:Fd,"css selector":Fd,id:Gd,linkText:Y,"link text":Y,name:{o:function(a,b){var c=nb(A(b),"*",null,b);return Ba(c,function(b){return ed(b,"name")==a})},s:function(a,b){var c=nb(A(b),"*",null,b);return xa(c,function(b){return ed(b,"name")==a})}},partialLinkText:Hd,"partial link text":Hd,tagName:Id,"tag name":Id,xpath:T};
function Kd(a,b){var c;a:{for(c in a)if(a.hasOwnProperty(c))break a;c=null}if(c){var d=Jd[c];if(d&&ea(d.o))return d.o(a[c],b||ma.document)}throw Error("Unsupported locator strategy: "+c);};var Ld={index:function(a,b){var c=Number(a);if(isNaN(c)||0>c)throw new Dd("Illegal Index: "+a);if(b.length<=c)throw new Dd("Index out of range: "+a);return[b[c]]},name:function(a,b){return xa(b,function(b){return dd(b,"name")==a})},value:function(a,b){return xa(b,function(b){return dd(b,"value")===a})}};function Md(a,b){return(new RegExp(a)).test(b)}function Nd(a,b){return(new RegExp(a,"i")).test(b)}function Od(a){a=a.replace(/([.^$+(){}\[\]\\|])/g,"\\$1");a=a.replace(/\?/g,"(.|[\r\n])");return a=a.replace(/\*/g,"(.|[\r\n])*")}var Pd={exact:function(a,b){return-1!=b.indexOf(a)},glob:function(a,b){return(new RegExp("^"+Od(a)+"$")).test(b)},globcontains:function(a,b){return(new RegExp(Od(a))).test(b)},regex:Md,regexi:Nd,regexpi:Nd,regexp:Md};function Qd(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";var c;if(3==a.nodeType)return c=a.data,b||(c=c.replace(/\n|\r|\t/g," ")),c.replace(/&nbsp/," ");if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.tagName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);f&&(c+=Qd(f,d))}if("P"==a.tagName||"BR"==a.tagName||"HR"==a.tagName||"DIV"==a.tagName)c+="\n";c=c.replace(/&nbsp/," ");Sc.Y&&Xc(9)&&(c=c.replace(/&#100;/," "));return c}return""}
;var Z={T:function(a,b){return pa(a,"//")?Z.N(a,b):pa(a,"document.")?Z.F(a,b):Z.G(a,b)},O:function(a,b){return Rd(b||B(ma),function(b){return b.alt==a})},P:function(a,b){return Rd(b||B(ma),function(b){return b.className==a})},F:function(a){var b=null;try{b=eval(a)}catch(c){return null}return b?b:null},S:function(a,b){return Kd({id:a},b)},G:function(a,b){return Z.id(a,b)||Z.name(a,b)},j:function(a,b){var c=b||B(ma);A(c);var d;d=db(document,"*",null,c);c=a.split(" ");for(c[0]="name="+c[0];c.length;){var e=
c.shift(),f=d;d="value";var g=e.match(/^([A-Za-z]+)=(.+)/);g&&(d=g[1].toLowerCase(),e=g[2]);g=Ld[d];if(!g)throw new Dd("Unrecognised element-filter type: '"+d+"'");d=g(e,f)}return 0<d.length?d[0]:null},V:function(a,b){try{var c;a:{var d=a,d=decodeURIComponent(d),e=b||document,f,g=e||document,h=g.$wdc_;h||(h=g.$wdc_={},h.J=la());h.J||(h.J=la());f=h;if(!(null!==f&&d in f))throw new u(10,"Element does not exist in cache");var k=f[d];if(null!==k&&"setInterval"in k){if(k.closed)throw delete f[d],new u(23,
"Window has been closed.");c=k}else{for(g=k;g;){if(g==e.documentElement){c=k;break a}g=g.parentNode}delete f[d];throw new u(10,"Element is no longer attached to the DOM");}}return c}catch(m){return null}},N:function(a,b){var c=qa(a,"/"),d={xpath:a};try{var e=Kd(d,b);if(e||!c)return e}catch(f){if(!c)throw f;}d={xpath:a.substring(0,a.length-1)};return Kd(d,b)}};Z.alt=Z.O;Z["class"]=Z.P;Z.dom=Z.F;Z.id=Z.S;Z.identifier=Z.G;Z.implicit=Z.T;
Z.link=function(a,b){for(var c=(b||B(ma)).getElementsByTagName("a"),d=0;d<c.length;d++){var e=c[d],f=e,g="";Sa&&"1.8"<=Wa||Ta||z?g=Qd(f,!1):f.textContent?g=f.textContent:f.innerText&&(g=f.innerText);f=g=g.replace(/\r\n|\r/g,"\n");f=f.replace(/\ +/g," ");g=new RegExp(String.fromCharCode(160),"g");if(Ta)for(g=String.fromCharCode(160);-1!=f.indexOf(g);)f=f.replace(g," ");else f=f.replace(g," ");var g=f,f=ra(g),h=a,g="glob",k=/^([a-zA-Z-]+):(.*)/.exec(h);if(k){var m=k[1],k=k[2];Pd[m.toLowerCase()]&&(g=
m.toLowerCase(),h=k)}m=Pd[g];if(!m)throw new Dd("Cannot find pattern matching strategy: "+g);"glob"==g?(0==h.indexOf("glob:")&&(h=h.substring(5)),m=Pd.glob):"exact"==g&&0==h.indexOf("exact:")&&(h=h.substring(6));h=ka(m,h);h.$=g;if(h(f))return e}return null};Z.name=Z.j;Z.stored=Z.V;Z.xpath=Z.N;function Sd(a,b,c,d){var e=Z[a];if(!e)throw new Dd("Unrecognised locator type: '"+a+"'");c=e.call(null,b,c);if(null!=c)return c;if(!d)return null;for(e=0;e<d.frames.length;e++){var f;try{f=d.frames[e].document}catch(g){}if(f&&(c=Sd(a,b,f,d.frames[e]),null!=c))return c}return null}function Rd(a,b){for(var c=a.childNodes.length,d=0;d<c;d++){var e=a.childNodes[d];if(1==e.nodeType){if(b(e))return e;if(e=Rd(e,b))return e}}return null};var Td=Td||function(){};ba("_",function(a,b){var c;if(q(a)){(c=a.match(/^([A-Za-z]+)=.+/))?(c=c[1].toLowerCase(),c={type:c,string:a.substring(c.length+1)}):(c={string:"",type:""},c.string=a,c.type=pa(a,"//")?"xpath":pa(a,"document.")?"dom":"identifier");var d=ma||ma;c=Sd(c.type,c.string,d.document,d);if(null==c)throw new Dd("Element "+a+" not found");}else c=a;Cd(c,Ad);Cd(c,Bd);var e=ed(c,"maxlength"),d=b;null!=e&&(e=parseInt(e,0),b.length>e&&(d=b.substr(0,e)));V(c,"BODY")?c.ownerDocument&&c.ownerDocument.designMode&&"on"==
(new String(c.ownerDocument.designMode)).toLowerCase()&&(c.innerHTML=d):Sa&&Wc&&Vc(8)?Td(c).value=d:c.value=d;try{Cd(c,zd)}catch(f){}});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
