/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Click#getInnerhtml <em>Innerhtml</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClick()
 * @model
 * @generated
 */
public interface Click extends Action
{
  /**
   * Returns the value of the '<em><b>Innerhtml</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Innerhtml</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Innerhtml</em>' attribute.
   * @see #setInnerhtml(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClick_Innerhtml()
   * @model
   * @generated
   */
  String getInnerhtml();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Click#getInnerhtml <em>Innerhtml</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Innerhtml</em>' attribute.
   * @see #getInnerhtml()
   * @generated
   */
  void setInnerhtml(String value);

} // Click
