/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Delete#getObjName <em>Obj Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDelete()
 * @model
 * @generated
 */
public interface Delete extends Action
{
  /**
   * Returns the value of the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj Name</em>' attribute.
   * @see #setObjName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDelete_ObjName()
   * @model
   * @generated
   */
  String getObjName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Delete#getObjName <em>Obj Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj Name</em>' attribute.
   * @see #getObjName()
   * @generated
   */
  void setObjName(String value);

} // Delete
