/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do Wait</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DoWait#getMillisec <em>Millisec</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDoWait()
 * @model
 * @generated
 */
public interface DoWait extends Action
{
  /**
   * Returns the value of the '<em><b>Millisec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Millisec</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Millisec</em>' attribute.
   * @see #setMillisec(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDoWait_Millisec()
   * @model
   * @generated
   */
  int getMillisec();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DoWait#getMillisec <em>Millisec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Millisec</em>' attribute.
   * @see #getMillisec()
   * @generated
   */
  void setMillisec(int value);

} // DoWait
