/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Execute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Execute#getSubProcedureName <em>Sub Procedure Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExecute()
 * @model
 * @generated
 */
public interface Execute extends Structure
{
  /**
   * Returns the value of the '<em><b>Sub Procedure Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Procedure Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Procedure Name</em>' attribute.
   * @see #setSubProcedureName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExecute_SubProcedureName()
   * @model
   * @generated
   */
  String getSubProcedureName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Execute#getSubProcedureName <em>Sub Procedure Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Procedure Name</em>' attribute.
   * @see #getSubProcedureName()
   * @generated
   */
  void setSubProcedureName(String value);

} // Execute
