/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MainImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMain()
   * @generated
   */
  int MAIN = 0;

  /**
   * The feature id for the '<em><b>File Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__FILE_NAME = 0;

  /**
   * The feature id for the '<em><b>Browser Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__BROWSER_NAME = 1;

  /**
   * The feature id for the '<em><b>Orders</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__ORDERS = 2;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StructureImpl <em>Structure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StructureImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStructure()
   * @generated
   */
  int STRUCTURE = 2;

  /**
   * The number of structural features of the '<em>Structure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCTURE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 3;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ObjectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 4;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__OBJ_NAME = 0;

  /**
   * The feature id for the '<em><b>Htmltype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__HTMLTYPE = 1;

  /**
   * The feature id for the '<em><b>Object Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__OBJECT_DEF = 2;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.HTMLTYPEImpl <em>HTMLTYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.HTMLTYPEImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHTMLTYPE()
   * @generated
   */
  int HTMLTYPE = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTMLTYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>HTMLTYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTMLTYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CollectionImpl <em>Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CollectionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollection()
   * @generated
   */
  int COLLECTION = 6;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__OBJ = 0;

  /**
   * The feature id for the '<em><b>Htmltype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__HTMLTYPE = 1;

  /**
   * The feature id for the '<em><b>Object Rule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__OBJECT_RULE = 2;

  /**
   * The number of structural features of the '<em>Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SubProcedureImpl <em>Sub Procedure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SubProcedureImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubProcedure()
   * @generated
   */
  int SUB_PROCEDURE = 7;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROCEDURE__OBJ_NAME = OBJECT__OBJ_NAME;

  /**
   * The feature id for the '<em><b>Htmltype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROCEDURE__HTMLTYPE = OBJECT__HTMLTYPE;

  /**
   * The feature id for the '<em><b>Object Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROCEDURE__OBJECT_DEF = OBJECT__OBJECT_DEF;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROCEDURE__ACTIONS = OBJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sub Procedure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_PROCEDURE_FEATURE_COUNT = OBJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RefreshImpl <em>Refresh</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RefreshImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRefresh()
   * @generated
   */
  int REFRESH = 8;

  /**
   * The number of structural features of the '<em>Refresh</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFRESH_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NavigateImpl <em>Navigate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NavigateImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNavigate()
   * @generated
   */
  int NAVIGATE = 9;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE__URL = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Navigate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StoreImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStore()
   * @generated
   */
  int STORE = 10;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__OBJ_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__OBJ = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ReDefineImpl <em>Re Define</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ReDefineImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getReDefine()
   * @generated
   */
  int RE_DEFINE = 11;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RE_DEFINE__OBJ_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RE_DEFINE__OBJ = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Re Define</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RE_DEFINE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DeleteImpl <em>Delete</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DeleteImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelete()
   * @generated
   */
  int DELETE = 12;

  /**
   * The feature id for the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE__OBJ_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionSelectImpl <em>Action Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionSelectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getActionSelect()
   * @generated
   */
  int ACTION_SELECT = 13;

  /**
   * The feature id for the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_SELECT__OPTION = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Xpath</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_SELECT__XPATH = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Action Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_SELECT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ClickImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 14;

  /**
   * The feature id for the '<em><b>Object</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__OBJECT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FillImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFill()
   * @generated
   */
  int FILL = 15;

  /**
   * The feature id for the '<em><b>Nametag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__NAMETAG = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__CONTENT = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckBoxImpl <em>Check Box</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CheckBoxImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckBox()
   * @generated
   */
  int CHECK_BOX = 16;

  /**
   * The feature id for the '<em><b>Nametag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BOX__NAMETAG = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>New Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BOX__NEW_VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Check Box</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_BOX_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RickrollImpl <em>Rickroll</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RickrollImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRickroll()
   * @generated
   */
  int RICKROLL = 17;

  /**
   * The number of structural features of the '<em>Rickroll</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RICKROLL_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DoWaitImpl <em>Do Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DoWaitImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoWait()
   * @generated
   */
  int DO_WAIT = 18;

  /**
   * The feature id for the '<em><b>Millisec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_WAIT__MILLISEC = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Do Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_WAIT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IsInImpl <em>Is In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IsInImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIsIn()
   * @generated
   */
  int IS_IN = 19;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_IN__OBJ = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_IN__BODY = CONDITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_IN__TEXT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Is In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_IN_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
   * @generated
   */
  int NOT = 20;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__COND = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
   * @generated
   */
  int IF = 21;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COND = STRUCTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action Then</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ACTION_THEN = STRUCTURE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action Else</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ACTION_ELSE = STRUCTURE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = STRUCTURE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 22;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__COND = STRUCTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__MILLISECONDS = STRUCTURE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__ACTIONS = STRUCTURE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = STRUCTURE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DoAllImpl <em>Do All</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DoAllImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoAll()
   * @generated
   */
  int DO_ALL = 23;

  /**
   * The feature id for the '<em><b>Coll</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_ALL__COLL = STRUCTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Todo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_ALL__TODO = STRUCTURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Do All</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_ALL_FEATURE_COUNT = STRUCTURE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExecuteImpl <em>Execute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExecuteImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecute()
   * @generated
   */
  int EXECUTE = 24;

  /**
   * The feature id for the '<em><b>Sub Procedure Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTE__SUB_PROCEDURE_NAME = STRUCTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Subprocedure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTE__SUBPROCEDURE = STRUCTURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Execute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTE_FEATURE_COUNT = STRUCTURE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Main#getFileName <em>File Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main#getFileName()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_FileName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Main#getBrowserName <em>Browser Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Browser Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main#getBrowserName()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_BrowserName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Main#getOrders <em>Orders</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Orders</em>'.
   * @see org.xtext.example.mydsl.myDsl.Main#getOrders()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Orders();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Structure <em>Structure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Structure</em>'.
   * @see org.xtext.example.mydsl.myDsl.Structure
   * @generated
   */
  EClass getStructure();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see org.xtext.example.mydsl.myDsl.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Object#getObjName <em>Obj Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Object#getObjName()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_ObjName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Object#getHtmltype <em>Htmltype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Htmltype</em>'.
   * @see org.xtext.example.mydsl.myDsl.Object#getHtmltype()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Htmltype();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Object#getObjectDef <em>Object Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Object Def</em>'.
   * @see org.xtext.example.mydsl.myDsl.Object#getObjectDef()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_ObjectDef();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.HTMLTYPE <em>HTMLTYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>HTMLTYPE</em>'.
   * @see org.xtext.example.mydsl.myDsl.HTMLTYPE
   * @generated
   */
  EClass getHTMLTYPE();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.HTMLTYPE#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.HTMLTYPE#getType()
   * @see #getHTMLTYPE()
   * @generated
   */
  EAttribute getHTMLTYPE_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Collection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection
   * @generated
   */
  EClass getCollection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Collection#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Obj</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getObj()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_Obj();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Collection#getHtmltype <em>Htmltype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Htmltype</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getHtmltype()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_Htmltype();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Collection#getObjectRule <em>Object Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Object Rule</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collection#getObjectRule()
   * @see #getCollection()
   * @generated
   */
  EAttribute getCollection_ObjectRule();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SubProcedure <em>Sub Procedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Procedure</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubProcedure
   * @generated
   */
  EClass getSubProcedure();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.SubProcedure#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubProcedure#getActions()
   * @see #getSubProcedure()
   * @generated
   */
  EReference getSubProcedure_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Refresh <em>Refresh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Refresh</em>'.
   * @see org.xtext.example.mydsl.myDsl.Refresh
   * @generated
   */
  EClass getRefresh();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Navigate <em>Navigate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navigate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Navigate
   * @generated
   */
  EClass getNavigate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Navigate#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.myDsl.Navigate#getUrl()
   * @see #getNavigate()
   * @generated
   */
  EAttribute getNavigate_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Store#getObjName <em>Obj Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store#getObjName()
   * @see #getStore()
   * @generated
   */
  EAttribute getStore_ObjName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Store#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.xtext.example.mydsl.myDsl.Store#getObj()
   * @see #getStore()
   * @generated
   */
  EReference getStore_Obj();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ReDefine <em>Re Define</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Re Define</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReDefine
   * @generated
   */
  EClass getReDefine();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ReDefine#getObjName <em>Obj Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReDefine#getObjName()
   * @see #getReDefine()
   * @generated
   */
  EAttribute getReDefine_ObjName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ReDefine#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.xtext.example.mydsl.myDsl.ReDefine#getObj()
   * @see #getReDefine()
   * @generated
   */
  EReference getReDefine_Obj();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Delete <em>Delete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete</em>'.
   * @see org.xtext.example.mydsl.myDsl.Delete
   * @generated
   */
  EClass getDelete();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Delete#getObjName <em>Obj Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obj Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Delete#getObjName()
   * @see #getDelete()
   * @generated
   */
  EAttribute getDelete_ObjName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ActionSelect <em>Action Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Select</em>'.
   * @see org.xtext.example.mydsl.myDsl.ActionSelect
   * @generated
   */
  EClass getActionSelect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ActionSelect#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option</em>'.
   * @see org.xtext.example.mydsl.myDsl.ActionSelect#getOption()
   * @see #getActionSelect()
   * @generated
   */
  EAttribute getActionSelect_Option();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ActionSelect#getXpath <em>Xpath</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xpath</em>'.
   * @see org.xtext.example.mydsl.myDsl.ActionSelect#getXpath()
   * @see #getActionSelect()
   * @generated
   */
  EAttribute getActionSelect_Xpath();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.myDsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Click#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object</em>'.
   * @see org.xtext.example.mydsl.myDsl.Click#getObject()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Object();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fill#getNametag <em>Nametag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nametag</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill#getNametag()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_Nametag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fill#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fill#getContent()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CheckBox <em>Check Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check Box</em>'.
   * @see org.xtext.example.mydsl.myDsl.CheckBox
   * @generated
   */
  EClass getCheckBox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CheckBox#getNametag <em>Nametag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nametag</em>'.
   * @see org.xtext.example.mydsl.myDsl.CheckBox#getNametag()
   * @see #getCheckBox()
   * @generated
   */
  EAttribute getCheckBox_Nametag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CheckBox#getNewValue <em>New Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>New Value</em>'.
   * @see org.xtext.example.mydsl.myDsl.CheckBox#getNewValue()
   * @see #getCheckBox()
   * @generated
   */
  EAttribute getCheckBox_NewValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rickroll <em>Rickroll</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rickroll</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rickroll
   * @generated
   */
  EClass getRickroll();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DoWait <em>Do Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Do Wait</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoWait
   * @generated
   */
  EClass getDoWait();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DoWait#getMillisec <em>Millisec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Millisec</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoWait#getMillisec()
   * @see #getDoWait()
   * @generated
   */
  EAttribute getDoWait_Millisec();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.IsIn <em>Is In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Is In</em>'.
   * @see org.xtext.example.mydsl.myDsl.IsIn
   * @generated
   */
  EClass getIsIn();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.IsIn#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.xtext.example.mydsl.myDsl.IsIn#getObj()
   * @see #getIsIn()
   * @generated
   */
  EReference getIsIn_Obj();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IsIn#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.IsIn#getBody()
   * @see #getIsIn()
   * @generated
   */
  EAttribute getIsIn_Body();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.IsIn#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.myDsl.IsIn#getText()
   * @see #getIsIn()
   * @generated
   */
  EAttribute getIsIn_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Not#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not#getCond()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Cond();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.xtext.example.mydsl.myDsl.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCond()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Cond();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.If#getActionThen <em>Action Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action Then</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getActionThen()
   * @see #getIf()
   * @generated
   */
  EReference getIf_ActionThen();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.If#getActionElse <em>Action Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action Else</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getActionElse()
   * @see #getIf()
   * @generated
   */
  EReference getIf_ActionElse();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Loop#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop#getCond()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Cond();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Loop#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop#getMilliseconds()
   * @see #getLoop()
   * @generated
   */
  EAttribute getLoop_Milliseconds();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Loop#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop#getActions()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DoAll <em>Do All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Do All</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoAll
   * @generated
   */
  EClass getDoAll();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.DoAll#getColl <em>Coll</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coll</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoAll#getColl()
   * @see #getDoAll()
   * @generated
   */
  EReference getDoAll_Coll();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.DoAll#getTodo <em>Todo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Todo</em>'.
   * @see org.xtext.example.mydsl.myDsl.DoAll#getTodo()
   * @see #getDoAll()
   * @generated
   */
  EReference getDoAll_Todo();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Execute <em>Execute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Execute</em>'.
   * @see org.xtext.example.mydsl.myDsl.Execute
   * @generated
   */
  EClass getExecute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Execute#getSubProcedureName <em>Sub Procedure Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sub Procedure Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Execute#getSubProcedureName()
   * @see #getExecute()
   * @generated
   */
  EAttribute getExecute_SubProcedureName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Execute#getSubprocedure <em>Subprocedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subprocedure</em>'.
   * @see org.xtext.example.mydsl.myDsl.Execute#getSubprocedure()
   * @see #getExecute()
   * @generated
   */
  EReference getExecute_Subprocedure();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MainImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>File Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__FILE_NAME = eINSTANCE.getMain_FileName();

    /**
     * The meta object literal for the '<em><b>Browser Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__BROWSER_NAME = eINSTANCE.getMain_BrowserName();

    /**
     * The meta object literal for the '<em><b>Orders</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__ORDERS = eINSTANCE.getMain_Orders();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StructureImpl <em>Structure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StructureImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStructure()
     * @generated
     */
    EClass STRUCTURE = eINSTANCE.getStructure();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ObjectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Obj Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__OBJ_NAME = eINSTANCE.getObject_ObjName();

    /**
     * The meta object literal for the '<em><b>Htmltype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__HTMLTYPE = eINSTANCE.getObject_Htmltype();

    /**
     * The meta object literal for the '<em><b>Object Def</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__OBJECT_DEF = eINSTANCE.getObject_ObjectDef();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.HTMLTYPEImpl <em>HTMLTYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.HTMLTYPEImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHTMLTYPE()
     * @generated
     */
    EClass HTMLTYPE = eINSTANCE.getHTMLTYPE();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HTMLTYPE__TYPE = eINSTANCE.getHTMLTYPE_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CollectionImpl <em>Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CollectionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollection()
     * @generated
     */
    EClass COLLECTION = eINSTANCE.getCollection();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__OBJ = eINSTANCE.getCollection_Obj();

    /**
     * The meta object literal for the '<em><b>Htmltype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__HTMLTYPE = eINSTANCE.getCollection_Htmltype();

    /**
     * The meta object literal for the '<em><b>Object Rule</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION__OBJECT_RULE = eINSTANCE.getCollection_ObjectRule();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SubProcedureImpl <em>Sub Procedure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SubProcedureImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubProcedure()
     * @generated
     */
    EClass SUB_PROCEDURE = eINSTANCE.getSubProcedure();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_PROCEDURE__ACTIONS = eINSTANCE.getSubProcedure_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RefreshImpl <em>Refresh</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RefreshImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRefresh()
     * @generated
     */
    EClass REFRESH = eINSTANCE.getRefresh();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NavigateImpl <em>Navigate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NavigateImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNavigate()
     * @generated
     */
    EClass NAVIGATE = eINSTANCE.getNavigate();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAVIGATE__URL = eINSTANCE.getNavigate_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StoreImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>Obj Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE__OBJ_NAME = eINSTANCE.getStore_ObjName();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE__OBJ = eINSTANCE.getStore_Obj();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ReDefineImpl <em>Re Define</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ReDefineImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getReDefine()
     * @generated
     */
    EClass RE_DEFINE = eINSTANCE.getReDefine();

    /**
     * The meta object literal for the '<em><b>Obj Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RE_DEFINE__OBJ_NAME = eINSTANCE.getReDefine_ObjName();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RE_DEFINE__OBJ = eINSTANCE.getReDefine_Obj();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DeleteImpl <em>Delete</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DeleteImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelete()
     * @generated
     */
    EClass DELETE = eINSTANCE.getDelete();

    /**
     * The meta object literal for the '<em><b>Obj Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELETE__OBJ_NAME = eINSTANCE.getDelete_ObjName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionSelectImpl <em>Action Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionSelectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getActionSelect()
     * @generated
     */
    EClass ACTION_SELECT = eINSTANCE.getActionSelect();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_SELECT__OPTION = eINSTANCE.getActionSelect_Option();

    /**
     * The meta object literal for the '<em><b>Xpath</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_SELECT__XPATH = eINSTANCE.getActionSelect_Xpath();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ClickImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__OBJECT = eINSTANCE.getClick_Object();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FillImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Nametag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__NAMETAG = eINSTANCE.getFill_Nametag();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__CONTENT = eINSTANCE.getFill_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CheckBoxImpl <em>Check Box</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CheckBoxImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCheckBox()
     * @generated
     */
    EClass CHECK_BOX = eINSTANCE.getCheckBox();

    /**
     * The meta object literal for the '<em><b>Nametag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_BOX__NAMETAG = eINSTANCE.getCheckBox_Nametag();

    /**
     * The meta object literal for the '<em><b>New Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_BOX__NEW_VALUE = eINSTANCE.getCheckBox_NewValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RickrollImpl <em>Rickroll</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RickrollImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRickroll()
     * @generated
     */
    EClass RICKROLL = eINSTANCE.getRickroll();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DoWaitImpl <em>Do Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DoWaitImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoWait()
     * @generated
     */
    EClass DO_WAIT = eINSTANCE.getDoWait();

    /**
     * The meta object literal for the '<em><b>Millisec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DO_WAIT__MILLISEC = eINSTANCE.getDoWait_Millisec();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IsInImpl <em>Is In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IsInImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIsIn()
     * @generated
     */
    EClass IS_IN = eINSTANCE.getIsIn();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_IN__OBJ = eINSTANCE.getIsIn_Obj();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IS_IN__BODY = eINSTANCE.getIsIn_Body();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IS_IN__TEXT = eINSTANCE.getIsIn_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__COND = eINSTANCE.getNot_Cond();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COND = eINSTANCE.getIf_Cond();

    /**
     * The meta object literal for the '<em><b>Action Then</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ACTION_THEN = eINSTANCE.getIf_ActionThen();

    /**
     * The meta object literal for the '<em><b>Action Else</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ACTION_ELSE = eINSTANCE.getIf_ActionElse();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__COND = eINSTANCE.getLoop_Cond();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP__MILLISECONDS = eINSTANCE.getLoop_Milliseconds();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__ACTIONS = eINSTANCE.getLoop_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DoAllImpl <em>Do All</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DoAllImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDoAll()
     * @generated
     */
    EClass DO_ALL = eINSTANCE.getDoAll();

    /**
     * The meta object literal for the '<em><b>Coll</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_ALL__COLL = eINSTANCE.getDoAll_Coll();

    /**
     * The meta object literal for the '<em><b>Todo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_ALL__TODO = eINSTANCE.getDoAll_Todo();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExecuteImpl <em>Execute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExecuteImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExecute()
     * @generated
     */
    EClass EXECUTE = eINSTANCE.getExecute();

    /**
     * The meta object literal for the '<em><b>Sub Procedure Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXECUTE__SUB_PROCEDURE_NAME = eINSTANCE.getExecute_SubProcedureName();

    /**
     * The meta object literal for the '<em><b>Subprocedure</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXECUTE__SUBPROCEDURE = eINSTANCE.getExecute_Subprocedure();

  }

} //MyDslPackage
